<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "animations" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class AnimationsDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'animations')->first();

        if (!$section) {
            $this->command?->warn("Section 'animations' not found — skipping AnimationsDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Fade In Up',
                'slug' => 'fade-in-up-animation',
                'description' => 'An element that fades in while sliding up slightly, a very common entrance animation.',
                'storage_path' => 'animations/fade-in-up-animation',
                'customizable_vars' => [
                    '--box-color' => '#6366f1',
                ],
                'tags' => [
                    'entrance',
                    'fade',
                    'keyframes',
                ],
            ],
            [
                'title' => 'Bounce Loop',
                'slug' => 'bounce-loop-animation',
                'description' => 'An element that bounces continuously up and down, like a notification dot or scroll cue.',
                'storage_path' => 'animations/bounce-loop-animation',
                'customizable_vars' => [
                    '--ball-color' => '#f59e0b',
                ],
                'tags' => [
                    'bounce',
                    'loop',
                    'playful',
                ],
            ],
            [
                'title' => 'Pulse Glow',
                'slug' => 'pulse-glow-animation',
                'description' => 'A circular element with a continuously pulsing glow, often used for live/recording indicators.',
                'storage_path' => 'animations/pulse-glow-animation',
                'customizable_vars' => [
                    '--pulse-color' => '#ef4444',
                ],
                'tags' => [
                    'pulse',
                    'live-indicator',
                    'glow',
                ],
            ],
            [
                'title' => 'Typewriter Text',
                'slug' => 'typewriter-text-animation',
                'description' => 'Text that types itself out character by character using JS, with a blinking cursor.',
                'storage_path' => 'animations/typewriter-text-animation',
                'customizable_vars' => [
                    '--text-color' => '#111827',
                ],
                'tags' => [
                    'typewriter',
                    'javascript',
                    'text-effect',
                ],
            ],
            [
                'title' => 'Staggered List Reveal',
                'slug' => 'staggered-list-animation',
                'description' => 'List items that fade/slide in one after another with a staggered animation-delay.',
                'storage_path' => 'animations/staggered-list-animation',
                'customizable_vars' => [
                    '--accent' => '#0ea5e9',
                ],
                'tags' => [
                    'stagger',
                    'list',
                    'sequential',
                ],
            ],
            [
                'title' => 'Rotating Ring Loader',
                'slug' => 'rotating-loader-animation',
                'description' => 'A classic spinning ring loader animation built purely with CSS border tricks.',
                'storage_path' => 'animations/rotating-loader-animation',
                'customizable_vars' => [
                    '--ring-color' => '#8b5cf6',
                ],
                'tags' => [
                    'loader',
                    'spinner',
                    'css-only',
                ],
            ],
            [
                'title' => 'Flip Reveal Card',
                'slug' => 'flip-card-reveal-animation',
                'description' => 'A card that flips 180 degrees on hover to reveal hidden content on the back, pure CSS 3D transform.',
                'storage_path' => 'animations/flip-card-reveal-animation',
                'customizable_vars' => [
                    '--front-color' => '#1e293b',
                    '--back-color' => '#f59e0b',
                ],
                'tags' => [
                    '3d-flip',
                    'hover',
                    'reveal',
                ],
            ],
            [
                'title' => 'Scroll Reveal',
                'slug' => 'scroll-reveal-animation',
                'description' => 'Elements that fade/slide into view as they enter the viewport on scroll, using IntersectionObserver.',
                'storage_path' => 'animations/scroll-reveal-animation',
                'customizable_vars' => [
                    '--box-color' => '#16a34a',
                ],
                'tags' => [
                    'scroll',
                    'intersection-observer',
                    'javascript',
                ],
            ],
            [
                'title' => 'Morphing Blob Shape',
                'slug' => 'morphing-blob-animation',
                'description' => 'An organic shape that continuously morphs its border-radius, creating a liquid-like animated blob.',
                'storage_path' => 'animations/morphing-blob-animation',
                'customizable_vars' => [
                    '--blob-color' => '#ec4899',
                ],
                'tags' => [
                    'morph',
                    'organic',
                    'liquid',
                ],
            ],
            [
                'title' => 'Shimmering Gradient Text',
                'slug' => 'text-gradient-shimmer-animation',
                'description' => 'Heading text with a moving gradient shimmer effect using background-clip and animated background-position.',
                'storage_path' => 'animations/text-gradient-shimmer-animation',
                'customizable_vars' => [
                    '--g1' => '#6366f1',
                    '--g2' => '#ec4899',
                    '--g3' => '#f59e0b',
                ],
                'tags' => [
                    'text-gradient',
                    'shimmer',
                    'heading',
                ],
            ],
            [
                'title' => '3D Tilt on Mouse Move',
                'slug' => 'card-tilt-3d-animation',
                'description' => 'A card that tilts in 3D following the cursor position, using JS mouse coordinates and CSS perspective.',
                'storage_path' => 'animations/card-tilt-3d-animation',
                'customizable_vars' => [
                    '--card-bg' => '#1e293b',
                ],
                'tags' => [
                    '3d-tilt',
                    'javascript',
                    'mousemove',
                    'perspective',
                ],
            ],
            [
                'title' => 'Animated SVG Wave',
                'slug' => 'wave-svg-animation',
                'description' => 'A continuously scrolling wave shape using an animated SVG path translateX, common for hero section dividers.',
                'storage_path' => 'animations/wave-svg-animation',
                'customizable_vars' => [],
                'tags' => [
                    'svg',
                    'wave',
                    'hero-divider',
                ],
            ],
            [
                'title' => 'Counting Number Animation',
                'slug' => 'counting-numbers-animation',
                'description' => 'A number that animates counting up from 0 to a target value when the page loads, via JS.',
                'storage_path' => 'animations/counting-numbers-animation',
                'customizable_vars' => [
                    '--num-color' => '#6366f1',
                ],
                'tags' => [
                    'counter',
                    'javascript',
                    'stats',
                ],
            ],
            [
                'title' => 'Expanding Ripple Background',
                'slug' => 'ripple-background-animation',
                'description' => 'Concentric circles continuously expanding outward from center, like a radar/sonar ping effect.',
                'storage_path' => 'animations/ripple-background-animation',
                'customizable_vars' => [
                    '--ping-color' => '#22c55e',
                ],
                'tags' => [
                    'ripple',
                    'radar',
                    'ping',
                ],
            ],
            [
                'title' => 'Hover Icon Bounce Grid',
                'slug' => 'hover-icon-bounce-animation',
                'description' => 'A grid of icons that each bounce playfully on individual hover, demonstrating per-item hover animation.',
                'storage_path' => 'animations/hover-icon-bounce-animation',
                'customizable_vars' => [
                    '--bg-color' => '#fef3c7',
                ],
                'tags' => [
                    'hover',
                    'icon-grid',
                    'bounce',
                ],
            ],
            [
                'title' => 'Smooth Drag Reorder',
                'slug' => 'drag-reorder-animation',
                'description' => 'List items that can be dragged to reorder, with smooth repositioning, using the native HTML5 drag-and-drop API.',
                'storage_path' => 'animations/drag-reorder-animation',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'drag-and-drop',
                    'javascript',
                    'reorder',
                ],
            ],
            [
                'title' => 'Three Dots Loading',
                'slug' => 'loading-dots-animation',
                'description' => 'The classic three-dot \'typing\' loading indicator with staggered bounce, common in chat apps.',
                'storage_path' => 'animations/loading-dots-animation',
                'customizable_vars' => [
                    '--dot-color' => '#6b7280',
                ],
                'tags' => [
                    'loading',
                    'dots',
                    'chat-indicator',
                ],
            ],
            [
                'title' => 'Parallax Scroll Layers',
                'slug' => 'parallax-scroll-animation',
                'description' => 'Two background layers that move at different speeds as the page scrolls, creating depth via JS scroll listener.',
                'storage_path' => 'animations/parallax-scroll-animation',
                'customizable_vars' => [
                    '--back-color' => '#93c5fd',
                ],
                'tags' => [
                    'parallax',
                    'scroll',
                    'javascript',
                    'depth',
                ],
            ],
            [
                'title' => 'Attention Shake on Load',
                'slug' => 'attention-shake-animation',
                'description' => 'An element that briefly shakes once on page load to draw attention, a one-time (not infinite) animation.',
                'storage_path' => 'animations/attention-shake-animation',
                'customizable_vars' => [
                    '--badge-bg' => '#fbbf24',
                ],
                'tags' => [
                    'shake',
                    'attention',
                    'one-time',
                ],
            ],
            [
                'title' => 'SVG Line Draw',
                'slug' => 'svg-path-draw-animation',
                'description' => 'An SVG checkmark/path that appears to draw itself using stroke-dasharray and stroke-dashoffset animation.',
                'storage_path' => 'animations/svg-path-draw-animation',
                'customizable_vars' => [
                    '--stroke-color' => '#16a34a',
                ],
                'tags' => [
                    'svg',
                    'stroke-animation',
                    'checkmark',
                ],
            ],
            [
                'title' => 'Background Color Cycle',
                'slug' => 'background-color-cycle-animation',
                'description' => 'A full-screen background that smoothly cycles through a sequence of colors continuously.',
                'storage_path' => 'animations/background-color-cycle-animation',
                'customizable_vars' => [],
                'tags' => [
                    'background',
                    'color-cycle',
                    'ambient',
                ],
            ],
            [
                'title' => 'Cursor Follow Dot',
                'slug' => 'magnetic-cursor-follow-animation',
                'description' => 'A small dot that smoothly trails the mouse cursor anywhere on the page, using JS and CSS transitions.',
                'storage_path' => 'animations/magnetic-cursor-follow-animation',
                'customizable_vars' => [
                    '--dot-color' => '#f43f5e',
                ],
                'tags' => [
                    'cursor-follow',
                    'javascript',
                    'custom-cursor',
                ],
            ],
            [
                'title' => 'Skeleton Loading Shimmer',
                'slug' => 'skeleton-shimmer-animation',
                'description' => 'Gray placeholder blocks with a moving shimmer highlight, simulating content that\'s still loading.',
                'storage_path' => 'animations/skeleton-shimmer-animation',
                'customizable_vars' => [],
                'tags' => [
                    'skeleton',
                    'shimmer',
                    'loading-placeholder',
                ],
            ],
            [
                'title' => 'Smooth Accordion Expand',
                'slug' => 'accordion-expand-animation',
                'description' => 'A collapsible panel that smoothly animates its height open/closed using JS-measured scrollHeight.',
                'storage_path' => 'animations/accordion-expand-animation',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'accordion',
                    'javascript',
                    'expand-collapse',
                ],
            ],
            [
                'title' => 'Confetti Burst on Click',
                'slug' => 'confetti-burst-animation',
                'description' => 'Clicking a button triggers a small burst of colorful confetti squares animating outward, built in pure JS+CSS.',
                'storage_path' => 'animations/confetti-burst-animation',
                'customizable_vars' => [],
                'tags' => [
                    'confetti',
                    'javascript',
                    'celebration',
                    'click-trigger',
                ],
            ],
            [
                'title' => 'Breathing Scale Effect',
                'slug' => 'breathing-scale-animation',
                'description' => 'An element that gently scales up and down in a slow, calming \'breathing\' loop.',
                'storage_path' => 'animations/breathing-scale-animation',
                'customizable_vars' => [
                    '--circle-color' => '#38bdf8',
                ],
                'tags' => [
                    'breathing',
                    'calm',
                    'scale-loop',
                ],
            ],
            [
                'title' => 'Slide-In Toast Notification',
                'slug' => 'slide-in-notification-animation',
                'description' => 'A toast that slides in from the right edge, pauses, then slides back out automatically, on a JS timer.',
                'storage_path' => 'animations/slide-in-notification-animation',
                'customizable_vars' => [
                    '--toast-bg' => '#16a34a',
                ],
                'tags' => [
                    'toast',
                    'slide-in',
                    'javascript',
                    'notification',
                ],
            ],
            [
                'title' => 'Infinite Scrolling Marquee',
                'slug' => 'infinite-marquee-animation',
                'description' => 'A row of logos/text that scrolls infinitely and seamlessly to the left, a common \'trusted by\' band pattern.',
                'storage_path' => 'animations/infinite-marquee-animation',
                'customizable_vars' => [
                    '--text-color' => '#475569',
                ],
                'tags' => [
                    'marquee',
                    'infinite-scroll',
                    'logo-band',
                ],
            ],
            [
                'title' => 'Number Flip Counter',
                'slug' => 'number-flip-animation',
                'description' => 'A digit that flips like an old mechanical counter/odometer when its value changes, using CSS 3D rotation.',
                'storage_path' => 'animations/number-flip-animation',
                'customizable_vars' => [
                    '--digit-bg' => '#1e293b',
                ],
                'tags' => [
                    'number-flip',
                    'odometer',
                    'javascript',
                ],
            ],
            [
                'title' => 'Spinning Gradient Border',
                'slug' => 'gradient-border-spin-animation',
                'description' => 'A card whose border is a continuously rotating conic gradient ring, a popular \'premium card\' effect.',
                'storage_path' => 'animations/gradient-border-spin-animation',
                'customizable_vars' => [
                    '--g1' => '#f59e0b',
                    '--g2' => '#ef4444',
                ],
                'tags' => [
                    'gradient-border',
                    'spin',
                    'premium-card',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
