<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "buttons" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class ButtonsDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'buttons')->first();

        if (!$section) {
            $this->command?->warn("Section 'buttons' not found — skipping ButtonsDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Gradient Shift Button',
                'slug' => 'gradient-shift-button',
                'description' => 'A button with an animated gradient background that shifts on hover.',
                'storage_path' => 'buttons/gradient-shift-button',
                'customizable_vars' => [
                    '--btn-color-1' => '#6366f1',
                    '--btn-color-2' => '#ec4899',
                    '--btn-radius' => '12px',
                ],
                'tags' => [
                    'gradient',
                    'hover',
                    'animation',
                ],
            ],
            [
                'title' => '3D Press Button',
                'slug' => '3d-press-button',
                'description' => 'A chunky button with a 3D shadow that compresses when clicked.',
                'storage_path' => 'buttons/3d-press-button',
                'customizable_vars' => [
                    '--btn-bg' => '#22c55e',
                    '--btn-shadow' => '#15803d',
                ],
                'tags' => [
                    '3d',
                    'click',
                    'shadow',
                ],
            ],
            [
                'title' => 'Glassmorphic Button',
                'slug' => 'glass-button',
                'description' => 'A frosted-glass button using backdrop-filter blur.',
                'storage_path' => 'buttons/glass-button',
                'customizable_vars' => [
                    '--btn-text' => '#ffffff',
                    '--btn-radius' => '14px',
                ],
                'tags' => [
                    'glassmorphism',
                    'blur',
                ],
            ],
            [
                'title' => 'Neon Glow Button',
                'slug' => 'neon-glow-button',
                'description' => 'A dark-mode neon button with a pulsing glow effect.',
                'storage_path' => 'buttons/neon-glow-button',
                'customizable_vars' => [
                    '--neon-color' => '#22d3ee',
                ],
                'tags' => [
                    'neon',
                    'dark-mode',
                    'glow',
                ],
            ],
            [
                'title' => 'Ripple Click Button',
                'slug' => 'ripple-click-button',
                'description' => 'A material-style button that emits a ripple from the click point using JS.',
                'storage_path' => 'buttons/ripple-click-button',
                'customizable_vars' => [
                    '--btn-bg' => '#3b82f6',
                ],
                'tags' => [
                    'ripple',
                    'material',
                    'javascript',
                ],
            ],
            [
                'title' => 'Loading State Button',
                'slug' => 'loading-state-button',
                'description' => 'A button that switches to a spinner and \'Loading...\' text on click, using JS.',
                'storage_path' => 'buttons/loading-state-button',
                'customizable_vars' => [
                    '--btn-bg' => '#8b5cf6',
                ],
                'tags' => [
                    'loading',
                    'spinner',
                    'javascript',
                    'ux',
                ],
            ],
            [
                'title' => 'Outline Fill Button',
                'slug' => 'outline-fill-button',
                'description' => 'An outlined button where the fill slides in from the left on hover.',
                'storage_path' => 'buttons/outline-fill-button',
                'customizable_vars' => [
                    '--btn-color' => '#ef4444',
                ],
                'tags' => [
                    'outline',
                    'hover',
                    'transition',
                ],
            ],
            [
                'title' => 'Icon Slide Button',
                'slug' => 'icon-slide-button',
                'description' => 'A button whose arrow icon slides right on hover using a flex layout and transform.',
                'storage_path' => 'buttons/icon-slide-button',
                'customizable_vars' => [
                    '--btn-bg' => '#0f172a',
                ],
                'tags' => [
                    'icon',
                    'hover',
                    'flex',
                ],
            ],
            [
                'title' => 'Gooey Blob Button',
                'slug' => 'gooey-blob-button',
                'description' => 'An organic, irregular border-radius button that morphs shape on hover.',
                'storage_path' => 'buttons/gooey-blob-button',
                'customizable_vars' => [
                    '--btn-bg' => '#f59e0b',
                ],
                'tags' => [
                    'organic',
                    'border-radius',
                    'hover',
                ],
            ],
            [
                'title' => 'Underline Grow Button',
                'slug' => 'underline-grow-button',
                'description' => 'A minimal text-style button where an underline grows from center on hover.',
                'storage_path' => 'buttons/underline-grow-button',
                'customizable_vars' => [
                    '--text-color' => '#111827',
                ],
                'tags' => [
                    'minimal',
                    'underline',
                    'hover',
                ],
            ],
            [
                'title' => 'Split Color Button',
                'slug' => 'split-color-button',
                'description' => 'A two-tone button split diagonally using a clip-path on a pseudo-element.',
                'storage_path' => 'buttons/split-color-button',
                'customizable_vars' => [
                    '--color-a' => '#06b6d4',
                    '--color-b' => '#1e3a8a',
                ],
                'tags' => [
                    'clip-path',
                    'diagonal',
                    'two-tone',
                ],
            ],
            [
                'title' => 'Toggle Like Button',
                'slug' => 'toggle-like-button',
                'description' => 'A heart-shaped like button that fills and animates on click using JS state toggling.',
                'storage_path' => 'buttons/toggle-like-button',
                'customizable_vars' => [
                    '--like-color' => '#f43f5e',
                ],
                'tags' => [
                    'toggle',
                    'like',
                    'javascript',
                    'svg',
                ],
            ],
            [
                'title' => 'Border Beam Button',
                'slug' => 'border-beam-button',
                'description' => 'A button with an animated light beam that travels continuously around its border.',
                'storage_path' => 'buttons/border-beam-button',
                'customizable_vars' => [
                    '--beam-color' => '#a855f7',
                ],
                'tags' => [
                    'border-animation',
                    'beam',
                    'css-animation',
                ],
            ],
            [
                'title' => 'Stacked Shadow Button',
                'slug' => 'stacked-shadow-button',
                'description' => 'A retro button using multiple stacked box-shadows for a layered paper effect.',
                'storage_path' => 'buttons/stacked-shadow-button',
                'customizable_vars' => [
                    '--btn-bg' => '#fde047',
                ],
                'tags' => [
                    'retro',
                    'box-shadow',
                    'layered',
                ],
            ],
            [
                'title' => 'Magnetic Hover Button',
                'slug' => 'magnetic-hover-button',
                'description' => 'A button that subtly follows the cursor within its bounds using JS mousemove tracking.',
                'storage_path' => 'buttons/magnetic-hover-button',
                'customizable_vars' => [
                    '--btn-bg' => '#10b981',
                ],
                'tags' => [
                    'magnetic',
                    'mousemove',
                    'javascript',
                    'interactive',
                ],
            ],
            [
                'title' => 'Progress Fill Button',
                'slug' => 'progress-fill-button',
                'description' => 'A button that fills with a progress bar over time when held down, then completes.',
                'storage_path' => 'buttons/progress-fill-button',
                'customizable_vars' => [
                    '--fill-color' => '#3b82f6',
                ],
                'tags' => [
                    'progress',
                    'javascript',
                    'timer',
                ],
            ],
            [
                'title' => 'Skeuomorphic Button',
                'slug' => 'skeuomorphic-button',
                'description' => 'A realistic, glossy plastic-style button with inner highlights and depth.',
                'storage_path' => 'buttons/skeuomorphic-button',
                'customizable_vars' => [
                    '--btn-bg' => '#dc2626',
                ],
                'tags' => [
                    'skeuomorphic',
                    'realistic',
                    'gloss',
                ],
            ],
            [
                'title' => 'Dashed Border Button',
                'slug' => 'dashed-border-button',
                'description' => 'An \'add new\' style button with a dashed border, common in upload/create UIs.',
                'storage_path' => 'buttons/dashed-border-button',
                'customizable_vars' => [
                    '--border-color' => '#9ca3af',
                ],
                'tags' => [
                    'dashed',
                    'upload',
                    'secondary',
                ],
            ],
            [
                'title' => 'Long Shadow Button',
                'slug' => 'long-shadow-button',
                'description' => 'A flat-design button with a stylized long diagonal text-shadow trail.',
                'storage_path' => 'buttons/long-shadow-button',
                'customizable_vars' => [
                    '--btn-bg' => '#fb7185',
                ],
                'tags' => [
                    'flat-design',
                    'shadow',
                    'trendy',
                ],
            ],
            [
                'title' => 'Checkbox Confirm Button',
                'slug' => 'checkbox-confirm-button',
                'description' => 'A button that morphs into a checkmark confirmation state when clicked, then reverts.',
                'storage_path' => 'buttons/checkbox-confirm-button',
                'customizable_vars' => [
                    '--btn-bg' => '#16a34a',
                ],
                'tags' => [
                    'confirm',
                    'checkmark',
                    'javascript',
                    'feedback',
                ],
            ],
            [
                'title' => 'Double Border Button',
                'slug' => 'double-border-button',
                'description' => 'A button with an offset double-border effect using box-shadow as a fake second border.',
                'storage_path' => 'buttons/double-border-button',
                'customizable_vars' => [
                    '--btn-color' => '#1d4ed8',
                ],
                'tags' => [
                    'double-border',
                    'offset',
                    'creative',
                ],
            ],
            [
                'title' => 'Social Share Button Group',
                'slug' => 'social-share-button',
                'description' => 'A \'Share\' button that expands into a row of social icon buttons on click.',
                'storage_path' => 'buttons/social-share-button',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'social',
                    'expand',
                    'javascript',
                    'group',
                ],
            ],
            [
                'title' => 'Frosted Icon Button',
                'slug' => 'frosted-icon-button',
                'description' => 'A round icon-only button with a frosted background, ideal for toolbars.',
                'storage_path' => 'buttons/frosted-icon-button',
                'customizable_vars' => [
                    '--icon-color' => '#475569',
                ],
                'tags' => [
                    'icon-only',
                    'round',
                    'toolbar',
                ],
            ],
            [
                'title' => 'Text Reveal Button',
                'slug' => 'text-reveal-button',
                'description' => 'A button where hidden secondary text slides up to replace the label on hover.',
                'storage_path' => 'buttons/text-reveal-button',
                'customizable_vars' => [
                    '--btn-bg' => '#0ea5e9',
                ],
                'tags' => [
                    'text-reveal',
                    'hover',
                    'overflow',
                ],
            ],
            [
                'title' => 'Border Radius Morph Button',
                'slug' => 'border-radius-morph-button',
                'description' => 'A square button that smoothly morphs into a circle shape on hover.',
                'storage_path' => 'buttons/border-radius-morph-button',
                'customizable_vars' => [
                    '--btn-bg' => '#14b8a6',
                ],
                'tags' => [
                    'morph',
                    'border-radius',
                    'shape-change',
                ],
            ],
            [
                'title' => 'Countdown Disable Button',
                'slug' => 'countdown-disable-button',
                'description' => 'A \'resend code\' style button that disables itself and counts down before re-enabling.',
                'storage_path' => 'buttons/countdown-disable-button',
                'customizable_vars' => [
                    '--btn-bg' => '#6366f1',
                ],
                'tags' => [
                    'countdown',
                    'disabled',
                    'javascript',
                    'ux-pattern',
                ],
            ],
            [
                'title' => 'Elastic Scale Button',
                'slug' => 'elastic-scale-button',
                'description' => 'A button with a bouncy elastic scale animation on click using cubic-bezier easing.',
                'storage_path' => 'buttons/elastic-scale-button',
                'customizable_vars' => [
                    '--btn-bg' => '#db2777',
                ],
                'tags' => [
                    'elastic',
                    'bounce',
                    'easing',
                ],
            ],
            [
                'title' => 'Border Gradient Button',
                'slug' => 'border-gradient-button',
                'description' => 'A button with a solid background but a gradient border, achieved via the padding-box trick.',
                'storage_path' => 'buttons/border-gradient-button',
                'customizable_vars' => [
                    '--g1' => '#06b6d4',
                    '--g2' => '#8b5cf6',
                ],
                'tags' => [
                    'gradient-border',
                    'padding-box',
                    'modern',
                ],
            ],
            [
                'title' => 'Shake on Error Button',
                'slug' => 'shake-on-error-button',
                'description' => 'A submit button that shakes horizontally to signal an error, triggered by a JS class toggle.',
                'storage_path' => 'buttons/shake-on-error-button',
                'customizable_vars' => [
                    '--btn-bg' => '#dc2626',
                ],
                'tags' => [
                    'shake',
                    'error-feedback',
                    'javascript',
                    'form',
                ],
            ],
            [
                'title' => 'Neumorphic Soft UI Button',
                'slug' => 'neumorphic-button',
                'description' => 'A soft, embossed neumorphism-style button using dual light/dark box-shadows.',
                'storage_path' => 'buttons/neumorphic-button',
                'customizable_vars' => [
                    '--base-bg' => '#e0e5ec',
                ],
                'tags' => [
                    'neumorphism',
                    'soft-ui',
                    'embossed',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
