<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "calendar" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class CalendarDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'calendar')->first();

        if (!$section) {
            $this->command?->warn("Section 'calendar' not found — skipping CalendarDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Basic Month Grid Calendar',
                'slug' => 'basic-month-grid-calendar',
                'description' => 'A classic 7-column month-view calendar grid with day numbers and a highlighted today.',
                'storage_path' => 'calendar/basic-month-grid-calendar',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'month-grid',
                    'classic',
                ],
            ],
            [
                'title' => 'Calendar with Event Dots',
                'slug' => 'event-dots-calendar',
                'description' => 'A month calendar where days with events show a small colored dot beneath the number.',
                'storage_path' => 'calendar/event-dots-calendar',
                'customizable_vars' => [
                    '--dot-color' => '#ec4899',
                ],
                'tags' => [
                    'event-indicators',
                    'dots',
                ],
            ],
            [
                'title' => 'Date Range Selection Calendar',
                'slug' => 'date-range-select-calendar',
                'description' => 'A calendar where clicking two dates highlights the range between them, via JS.',
                'storage_path' => 'calendar/date-range-select-calendar',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'date-range',
                    'javascript',
                    'booking-style',
                ],
            ],
            [
                'title' => 'Mini Inline Calendar Widget',
                'slug' => 'mini-inline-calendar',
                'description' => 'A compact calendar widget designed to sit inline within a sidebar or dashboard panel.',
                'storage_path' => 'calendar/mini-inline-calendar',
                'customizable_vars' => [
                    '--accent' => '#0ea5e9',
                ],
                'tags' => [
                    'mini-widget',
                    'sidebar',
                    'compact',
                ],
            ],
            [
                'title' => 'Week View Schedule Calendar',
                'slug' => 'week-view-calendar',
                'description' => 'A horizontal week-view calendar with time slots, common in scheduling/booking apps.',
                'storage_path' => 'calendar/week-view-calendar',
                'customizable_vars' => [
                    '--event-color' => '#6366f1',
                ],
                'tags' => [
                    'week-view',
                    'scheduling',
                    'time-slots',
                ],
            ],
            [
                'title' => 'Dark Mode Calendar Widget',
                'slug' => 'dark-mode-calendar',
                'description' => 'A calendar styled for dark-themed dashboards, with subtle borders and accent highlights.',
                'storage_path' => 'calendar/dark-mode-calendar',
                'customizable_vars' => [
                    '--accent' => '#38bdf8',
                ],
                'tags' => [
                    'dark-mode',
                    'dashboard-widget',
                ],
            ],
            [
                'title' => 'Calendar with Event List Sidebar',
                'slug' => 'event-list-sidebar-calendar',
                'description' => 'A calendar paired with a side list of upcoming events for the selected day.',
                'storage_path' => 'calendar/event-list-sidebar-calendar',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'combo-layout',
                    'event-sidebar',
                ],
            ],
            [
                'title' => 'Availability Slot Picker',
                'slug' => 'availability-picker-calendar',
                'description' => 'A calendar where available days are highlighted green and unavailable ones are grayed out and unclickable.',
                'storage_path' => 'calendar/availability-picker-calendar',
                'customizable_vars' => [
                    '--avail-color' => '#16a34a',
                ],
                'tags' => [
                    'availability',
                    'booking',
                    'slot-picker',
                ],
            ],
            [
                'title' => 'Activity Heatmap Calendar',
                'slug' => 'monthly-heatmap-calendar',
                'description' => 'A calendar where each day\'s background color intensity reflects activity level, GitHub-contributions style.',
                'storage_path' => 'calendar/monthly-heatmap-calendar',
                'customizable_vars' => [
                    '--heat-color' => '#16a34a',
                ],
                'tags' => [
                    'heatmap',
                    'activity-tracker',
                    'github-style',
                ],
            ],
            [
                'title' => 'Calendar with Add Event Button',
                'slug' => 'calendar-with-add-event',
                'description' => 'A calendar that shows an inline \'add event\' form when a day is clicked, via JS.',
                'storage_path' => 'calendar/calendar-with-add-event',
                'customizable_vars' => [
                    '--accent' => '#4338ca',
                ],
                'tags' => [
                    'add-event',
                    'javascript',
                    'inline-form',
                ],
            ],
            [
                'title' => 'Year Overview Mini-Months',
                'slug' => 'year-overview-calendar',
                'description' => 'A compact yearly overview showing 12 tiny month grids at once, common in admin dashboards.',
                'storage_path' => 'calendar/year-overview-calendar',
                'customizable_vars' => [
                    '--accent' => '#0891b2',
                ],
                'tags' => [
                    'year-view',
                    'admin-dashboard',
                ],
            ],
            [
                'title' => 'Calendar + Time Slot Picker',
                'slug' => 'calendar-with-time-picker',
                'description' => 'A calendar paired with a list of selectable time slots below it for booking appointments.',
                'storage_path' => 'calendar/calendar-with-time-picker',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'time-slots',
                    'appointment-booking',
                ],
            ],
            [
                'title' => 'Multi-Select Days Calendar',
                'slug' => 'calendar-multi-select-days',
                'description' => 'A calendar allowing multiple non-contiguous days to be toggled selected/unselected, via JS.',
                'storage_path' => 'calendar/calendar-multi-select-days',
                'customizable_vars' => [
                    '--accent' => '#ea580c',
                ],
                'tags' => [
                    'multi-select',
                    'javascript',
                    'non-contiguous',
                ],
            ],
            [
                'title' => 'Calendar with Holiday Labels',
                'slug' => 'calendar-with-holiday-tags',
                'description' => 'A calendar where specific dates show a small text tag underneath identifying holidays.',
                'storage_path' => 'calendar/calendar-with-holiday-tags',
                'customizable_vars' => [
                    '--holiday-color' => '#dc2626',
                ],
                'tags' => [
                    'holiday-labels',
                    'annotations',
                ],
            ],
            [
                'title' => 'Calendar with Week Numbers',
                'slug' => 'calendar-with-week-numbers',
                'description' => 'A month calendar showing the ISO week number in a small column to the left of each row.',
                'storage_path' => 'calendar/calendar-with-week-numbers',
                'customizable_vars' => [
                    '--accent' => '#475569',
                ],
                'tags' => [
                    'week-numbers',
                    'iso-week',
                ],
            ],
            [
                'title' => 'Calendar with Recurring Event Icons',
                'slug' => 'calendar-recurring-event-icon',
                'description' => 'A calendar showing a small repeat icon on days with recurring events, distinct from one-time events.',
                'storage_path' => 'calendar/calendar-recurring-event-icon',
                'customizable_vars' => [
                    '--accent' => '#0d9488',
                ],
                'tags' => [
                    'recurring-events',
                    'icon-indicator',
                ],
            ],
            [
                'title' => 'Drag to Select Date Range',
                'slug' => 'calendar-drag-select-range',
                'description' => 'A calendar where dragging the mouse across days selects a continuous range, via JS mouse events.',
                'storage_path' => 'calendar/calendar-drag-select-range',
                'customizable_vars' => [
                    '--accent' => '#be185d',
                ],
                'tags' => [
                    'drag-select',
                    'javascript',
                    'range-selection',
                ],
            ],
            [
                'title' => 'Calendar with Month Navigation',
                'slug' => 'calendar-with-month-nav-arrows',
                'description' => 'A calendar with working Previous/Next month arrows that update the displayed month label via JS.',
                'storage_path' => 'calendar/calendar-with-month-nav-arrows',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'month-navigation',
                    'javascript',
                ],
            ],
            [
                'title' => 'Color-Coded Category Calendar',
                'slug' => 'calendar-color-coded-categories',
                'description' => 'A calendar showing events tagged with different colors per category (work, personal, etc).',
                'storage_path' => 'calendar/calendar-color-coded-categories',
                'customizable_vars' => [],
                'tags' => [
                    'color-coding',
                    'categories',
                    'legend',
                ],
            ],
            [
                'title' => 'Quarterly 3-Month Overview',
                'slug' => 'calendar-quarterly-overview',
                'description' => 'Three consecutive month-mini-grids displayed side by side, a common quarterly planning view.',
                'storage_path' => 'calendar/calendar-quarterly-overview',
                'customizable_vars' => [
                    '--accent' => '#f59e0b',
                ],
                'tags' => [
                    'quarterly-view',
                    'planning',
                ],
            ],
            [
                'title' => 'Calendar with Deadline Countdown',
                'slug' => 'calendar-with-deadline-countdown',
                'description' => 'A calendar that highlights an upcoming deadline date and shows a \'X days left\' counter beneath it.',
                'storage_path' => 'calendar/calendar-with-deadline-countdown',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'deadline',
                    'countdown-note',
                ],
            ],
            [
                'title' => 'Calendar with Sync Buttons',
                'slug' => 'calendar-import-export-buttons',
                'description' => 'A calendar widget with buttons to sync/export to Google or Apple Calendar, common in event/booking confirmations.',
                'storage_path' => 'calendar/calendar-import-export-buttons',
                'customizable_vars' => [
                    '--accent' => '#1d4ed8',
                ],
                'tags' => [
                    'calendar-sync',
                    'export',
                    'booking-confirmation',
                ],
            ],
            [
                'title' => 'Mood Tracker Calendar',
                'slug' => 'calendar-mood-tracker',
                'description' => 'A playful calendar where each day shows an emoji representing a logged mood for that day.',
                'storage_path' => 'calendar/calendar-mood-tracker',
                'customizable_vars' => [],
                'tags' => [
                    'mood-tracker',
                    'emoji',
                    'playful',
                ],
            ],
            [
                'title' => 'Calendar with Jump-to-Date Search',
                'slug' => 'calendar-with-search-jump',
                'description' => 'A calendar with a small input to type a date and jump directly to it, via JS.',
                'storage_path' => 'calendar/calendar-with-search-jump',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'jump-to-date',
                    'javascript',
                    'search',
                ],
            ],
            [
                'title' => 'Public Holidays Reference Calendar',
                'slug' => 'calendar-readonly-public-holidays',
                'description' => 'A read-only calendar styled purely as a reference list of public holidays for a month.',
                'storage_path' => 'calendar/calendar-readonly-public-holidays',
                'customizable_vars' => [
                    '--accent' => '#1e40af',
                ],
                'tags' => [
                    'holidays',
                    'reference-list',
                ],
            ],
            [
                'title' => 'Busy/Free Overlay Calendar',
                'slug' => 'calendar-with-busy-overlay',
                'description' => 'A calendar combining a grid view with an overlay legend showing busy vs free days, scheduling-tool style.',
                'storage_path' => 'calendar/calendar-with-busy-overlay',
                'customizable_vars' => [],
                'tags' => [
                    'busy-free',
                    'scheduling-tool',
                    'legend',
                ],
            ],
            [
                'title' => 'Fiscal Quarter Marker Calendar',
                'slug' => 'calendar-fiscal-quarter-marker',
                'description' => 'A calendar with a visual marker band indicating which fiscal quarter the visible month belongs to.',
                'storage_path' => 'calendar/calendar-fiscal-quarter-marker',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'fiscal-quarter',
                    'business',
                    'marker-band',
                ],
            ],
            [
                'title' => 'Calendar with Day Note Popover',
                'slug' => 'calendar-with-note-popover',
                'description' => 'Clicking a calendar day shows a small popover where the user can jot a quick note, via JS.',
                'storage_path' => 'calendar/calendar-with-note-popover',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'notes',
                    'popover',
                    'javascript',
                ],
            ],
            [
                'title' => 'RTL-Friendly Calendar Layout',
                'slug' => 'calendar-rtl-support',
                'description' => 'A calendar grid built to work correctly in right-to-left reading layouts, with reversed weekday order.',
                'storage_path' => 'calendar/calendar-rtl-support',
                'customizable_vars' => [
                    '--accent' => '#0284c7',
                ],
                'tags' => [
                    'rtl',
                    'internationalization',
                    'arabic',
                ],
            ],
            [
                'title' => 'Calendar with Weather Icons',
                'slug' => 'calendar-with-emoji-weather',
                'description' => 'A calendar overlaying small weather emoji icons on each day, useful for trip planning interfaces.',
                'storage_path' => 'calendar/calendar-with-emoji-weather',
                'customizable_vars' => [],
                'tags' => [
                    'weather-icons',
                    'trip-planning',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
