<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "cards" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class CardsDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'cards')->first();

        if (!$section) {
            $this->command?->warn("Section 'cards' not found — skipping CardsDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Basic Product Card',
                'slug' => 'product-card-basic',
                'description' => 'A classic e-commerce product card with image, title, price, and an add-to-cart button.',
                'storage_path' => 'cards/product-card-basic',
                'customizable_vars' => [
                    '--accent' => '#111827',
                    '--radius' => '14px',
                ],
                'tags' => [
                    'product',
                    'ecommerce',
                ],
            ],
            [
                'title' => 'Social Profile Card',
                'slug' => 'profile-card-social',
                'description' => 'A user profile card with avatar, name, bio, and follow stats — common in social platforms.',
                'storage_path' => 'cards/profile-card-social',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'profile',
                    'social',
                    'stats',
                ],
            ],
            [
                'title' => 'Highlighted Pricing Card',
                'slug' => 'pricing-card-highlight',
                'description' => 'A pricing tier card with a \'Most Popular\' ribbon and feature checklist.',
                'storage_path' => 'cards/pricing-card-highlight',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'pricing',
                    'ribbon',
                    'highlighted',
                ],
            ],
            [
                'title' => 'Blog Post Card',
                'slug' => 'blog-post-card',
                'description' => 'A blog/article preview card with a featured image area, category tag, title, and excerpt.',
                'storage_path' => 'cards/blog-post-card',
                'customizable_vars' => [
                    '--tag-color' => '#0ea5e9',
                ],
                'tags' => [
                    'blog',
                    'article',
                    'content',
                ],
            ],
            [
                'title' => 'Stat Dashboard Card',
                'slug' => 'stat-dashboard-card',
                'description' => 'A compact dashboard metric card showing a big number, label, and trend indicator.',
                'storage_path' => 'cards/stat-dashboard-card',
                'customizable_vars' => [
                    '--up-color' => '#16a34a',
                ],
                'tags' => [
                    'dashboard',
                    'stats',
                    'metric',
                ],
            ],
            [
                'title' => 'Testimonial Quote Card',
                'slug' => 'testimonial-quote-card',
                'description' => 'A customer testimonial card with a large quotation mark, quote text, and reviewer info.',
                'storage_path' => 'cards/testimonial-quote-card',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'testimonial',
                    'quote',
                    'review',
                ],
            ],
            [
                'title' => 'Event Card with Date Badge',
                'slug' => 'event-card-date',
                'description' => 'An event listing card with a calendar-style date badge in the corner.',
                'storage_path' => 'cards/event-card-date',
                'customizable_vars' => [
                    '--accent' => '#ea580c',
                ],
                'tags' => [
                    'event',
                    'date-badge',
                    'listing',
                ],
            ],
            [
                'title' => 'Flip-to-Reveal Info Card',
                'slug' => 'flip-reveal-card-info',
                'description' => 'A card that flips on click to reveal extended details on the back, via JS toggle of a CSS 3D transform.',
                'storage_path' => 'cards/flip-reveal-card-info',
                'customizable_vars' => [
                    '--front-bg' => '#1d4ed8',
                    '--back-bg' => '#1e3a8a',
                ],
                'tags' => [
                    'flip-card',
                    'javascript',
                    'team-card',
                ],
            ],
            [
                'title' => 'Glass Overlay Image Card',
                'slug' => 'glass-overlay-image-card',
                'description' => 'A card with a background image and a glassmorphic frosted text overlay at the bottom.',
                'storage_path' => 'cards/glass-overlay-image-card',
                'customizable_vars' => [
                    '--radius' => '16px',
                ],
                'tags' => [
                    'glassmorphism',
                    'image-overlay',
                    'travel',
                ],
            ],
            [
                'title' => 'Task Checklist Card',
                'slug' => 'checklist-task-card',
                'description' => 'A to-do style card with checkable items that strike through when completed, using JS.',
                'storage_path' => 'cards/checklist-task-card',
                'customizable_vars' => [
                    '--accent' => '#4f46e5',
                ],
                'tags' => [
                    'checklist',
                    'todo',
                    'interactive',
                ],
            ],
            [
                'title' => 'Sale Countdown Card',
                'slug' => 'countdown-sale-card',
                'description' => 'A promotional card with a live JS countdown timer ticking down to a sale deadline.',
                'storage_path' => 'cards/countdown-sale-card',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'countdown',
                    'sale',
                    'javascript',
                    'ecommerce',
                ],
            ],
            [
                'title' => 'Expandable Details Card',
                'slug' => 'expandable-details-card',
                'description' => 'A card that expands to show more content when clicked, with smooth height transition via JS.',
                'storage_path' => 'cards/expandable-details-card',
                'customizable_vars' => [
                    '--accent' => '#0891b2',
                ],
                'tags' => [
                    'expandable',
                    'javascript',
                    'order-summary',
                ],
            ],
            [
                'title' => 'Gradient Header Card',
                'slug' => 'gradient-header-card',
                'description' => 'A card with a vibrant gradient header band and white content area below.',
                'storage_path' => 'cards/gradient-header-card',
                'customizable_vars' => [
                    '--g1' => '#fb923c',
                    '--g2' => '#f43f5e',
                ],
                'tags' => [
                    'gradient-header',
                    'weather',
                    'simple',
                ],
            ],
            [
                'title' => 'Star Rating Review Card',
                'slug' => 'rating-review-card',
                'description' => 'A review card with clickable star rating input, tracking selected stars via JS.',
                'storage_path' => 'cards/rating-review-card',
                'customizable_vars' => [
                    '--star-color' => '#f59e0b',
                ],
                'tags' => [
                    'rating',
                    'stars',
                    'javascript',
                    'review-input',
                ],
            ],
            [
                'title' => 'Drag & Drop File Upload Card',
                'slug' => 'file-upload-card',
                'description' => 'A file-upload zone card that highlights when a file is dragged over it, using JS dragover events.',
                'storage_path' => 'cards/file-upload-card',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'file-upload',
                    'drag-drop',
                    'javascript',
                ],
            ],
            [
                'title' => 'Notification Feed Card',
                'slug' => 'notification-feed-card',
                'description' => 'A stacked card showing a small feed of recent notifications with icons and timestamps.',
                'storage_path' => 'cards/notification-feed-card',
                'customizable_vars' => [
                    '--accent' => '#ec4899',
                ],
                'tags' => [
                    'notifications',
                    'feed',
                    'list',
                ],
            ],
            [
                'title' => 'Plan Comparison Card',
                'slug' => 'comparison-table-card',
                'description' => 'A side-by-side mini comparison card highlighting two plans with checkmarks and crosses.',
                'storage_path' => 'cards/comparison-table-card',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'comparison',
                    'pricing',
                    'table-style',
                ],
            ],
            [
                'title' => 'Image Zoom on Hover Card',
                'slug' => 'image-zoom-hover-card',
                'description' => 'A card whose image subtly zooms in when hovered, a very common e-commerce/gallery effect.',
                'storage_path' => 'cards/image-zoom-hover-card',
                'customizable_vars' => [
                    '--g1' => '#fb923c',
                    '--g2' => '#7c2d12',
                ],
                'tags' => [
                    'image-zoom',
                    'hover',
                    'gallery',
                ],
            ],
            [
                'title' => 'Skill Progress Card',
                'slug' => 'progress-skill-card',
                'description' => 'A card showing several skill bars that animate to their target width on load.',
                'storage_path' => 'cards/progress-skill-card',
                'customizable_vars' => [
                    '--fill-color' => '#6366f1',
                ],
                'tags' => [
                    'progress-bar',
                    'skills',
                    'animated',
                ],
            ],
            [
                'title' => 'Weather Forecast Card',
                'slug' => 'weather-forecast-card',
                'description' => 'A small horizontal scroll of weather days, each with icon, day, and temperature.',
                'storage_path' => 'cards/weather-forecast-card',
                'customizable_vars' => [
                    '--accent' => '#0284c7',
                ],
                'tags' => [
                    'weather',
                    'forecast',
                    'icons',
                ],
            ],
            [
                'title' => 'Mini Podcast Player Card',
                'slug' => 'podcast-player-card',
                'description' => 'A compact audio player card with a play/pause toggle and a fake progress scrubber, controlled by JS.',
                'storage_path' => 'cards/podcast-player-card',
                'customizable_vars' => [
                    '--accent' => '#9333ea',
                ],
                'tags' => [
                    'podcast',
                    'audio-player',
                    'javascript',
                ],
            ],
            [
                'title' => 'Achievement Badges Card',
                'slug' => 'badge-collection-card',
                'description' => 'A profile achievements card showing a grid of earned/unearned circular badge icons.',
                'storage_path' => 'cards/badge-collection-card',
                'customizable_vars' => [
                    '--earned-bg' => '#fef3c7',
                ],
                'tags' => [
                    'badges',
                    'gamification',
                    'achievements',
                ],
            ],
            [
                'title' => 'Contact Info Card',
                'slug' => 'contact-info-card',
                'description' => 'A simple business-card style contact info layout with icons for phone, email, and location.',
                'storage_path' => 'cards/contact-info-card',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'contact',
                    'business-card',
                    'info',
                ],
            ],
            [
                'title' => 'Recipe Card',
                'slug' => 'recipe-card-simple',
                'description' => 'A food recipe card with prep time, difficulty tag, and ingredient count.',
                'storage_path' => 'cards/recipe-card-simple',
                'customizable_vars' => [
                    '--tag-color' => '#16a34a',
                ],
                'tags' => [
                    'recipe',
                    'food',
                    'meta-tags',
                ],
            ],
            [
                'title' => 'Vertical Timeline Card',
                'slug' => 'vertical-timeline-card',
                'description' => 'A card displaying a short vertical timeline of events with connecting line and dots.',
                'storage_path' => 'cards/vertical-timeline-card',
                'customizable_vars' => [
                    '--done-color' => '#16a34a',
                ],
                'tags' => [
                    'timeline',
                    'order-tracking',
                    'vertical',
                ],
            ],
            [
                'title' => 'Video Thumbnail Card',
                'slug' => 'video-thumbnail-card',
                'description' => 'A video preview card with a centered play button overlay and duration badge.',
                'storage_path' => 'cards/video-thumbnail-card',
                'customizable_vars' => [
                    '--play-color' => '#dc2626',
                ],
                'tags' => [
                    'video',
                    'thumbnail',
                    'play-button',
                ],
            ],
            [
                'title' => 'Color Palette Swatch Card',
                'slug' => 'color-swatch-card',
                'description' => 'A design-tool style card showing a row of clickable color swatches that copy their hex code on click.',
                'storage_path' => 'cards/color-swatch-card',
                'customizable_vars' => [],
                'tags' => [
                    'color-palette',
                    'design-tool',
                    'javascript',
                ],
            ],
            [
                'title' => 'Newsletter Signup Card',
                'slug' => 'subscription-newsletter-card',
                'description' => 'A compact newsletter signup card with an email input and inline confirmation message after submit.',
                'storage_path' => 'cards/subscription-newsletter-card',
                'customizable_vars' => [
                    '--accent' => '#4338ca',
                ],
                'tags' => [
                    'newsletter',
                    'javascript',
                    'form-success',
                ],
            ],
            [
                'title' => 'Team Member Grid Card',
                'slug' => 'team-grid-card',
                'description' => 'A card listing several small team avatars in a row, with a \'+N more\' overflow indicator.',
                'storage_path' => 'cards/team-grid-card',
                'customizable_vars' => [
                    '--accent' => '#be185d',
                ],
                'tags' => [
                    'team',
                    'avatar-stack',
                    'overflow-indicator',
                ],
            ],
            [
                'title' => 'Limited Stock Badge Card',
                'slug' => 'expiry-countdown-badge-card',
                'description' => 'A product card emphasizing scarcity with a \'Only 3 left\' badge and a subtly pulsing border.',
                'storage_path' => 'cards/expiry-countdown-badge-card',
                'customizable_vars' => [
                    '--urgent-color' => '#dc2626',
                ],
                'tags' => [
                    'scarcity',
                    'urgency',
                    'ecommerce',
                    'pulse',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
