<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "contact-form" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class ContactFormDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'contact-form')->first();

        if (!$section) {
            $this->command?->warn("Section 'contact-form' not found — skipping ContactFormDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Basic Contact Us Form',
                'slug' => 'basic-contact-form',
                'description' => 'A classic contact form with name, email, subject, and message fields.',
                'storage_path' => 'contact-form/basic-contact-form',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'basic',
                    'classic',
                ],
            ],
            [
                'title' => 'Split Layout with Contact Info',
                'slug' => 'split-contact-info-form',
                'description' => 'A contact page with company info on the left and the form on the right.',
                'storage_path' => 'contact-form/split-contact-info-form',
                'customizable_vars' => [
                    '--panel-bg' => '#4f46e5',
                ],
                'tags' => [
                    'split-layout',
                    'company-info',
                ],
            ],
            [
                'title' => 'Floating Label Contact Form',
                'slug' => 'floating-label-contact-form',
                'description' => 'A modern contact form using floating labels that animate above inputs on focus.',
                'storage_path' => 'contact-form/floating-label-contact-form',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'floating-label',
                    'modern',
                ],
            ],
            [
                'title' => 'Contact Form with Map Placeholder',
                'slug' => 'contact-form-with-map',
                'description' => 'A contact form paired with a map area below it showing the office location.',
                'storage_path' => 'contact-form/contact-form-with-map',
                'customizable_vars' => [
                    '--accent' => '#0891b2',
                ],
                'tags' => [
                    'map',
                    'location',
                ],
            ],
            [
                'title' => 'Contact Form with Department Selector',
                'slug' => 'contact-form-department-select',
                'description' => 'A support contact form with a dropdown to route the inquiry to the right department.',
                'storage_path' => 'contact-form/contact-form-department-select',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'department-select',
                    'support-ticket',
                ],
            ],
            [
                'title' => 'Contact Form with Success Message',
                'slug' => 'contact-form-with-success-state',
                'description' => 'A contact form that replaces itself with a thank-you confirmation after submission, via JS.',
                'storage_path' => 'contact-form/contact-form-with-success-state',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'success-state',
                    'javascript',
                    'confirmation',
                ],
            ],
            [
                'title' => 'Card-Style Contact Form',
                'slug' => 'contact-form-card-style',
                'description' => 'A bold card-style contact form with a colored header band and white content area.',
                'storage_path' => 'contact-form/contact-form-card-style',
                'customizable_vars' => [
                    '--g1' => '#ec4899',
                    '--g2' => '#8b5cf6',
                ],
                'tags' => [
                    'card-style',
                    'gradient-header',
                ],
            ],
            [
                'title' => 'Contact Form with Message Counter',
                'slug' => 'contact-form-character-counter',
                'description' => 'A contact form with a message textarea showing remaining character count, via JS.',
                'storage_path' => 'contact-form/contact-form-character-counter',
                'customizable_vars' => [
                    '--accent' => '#ea580c',
                ],
                'tags' => [
                    'character-counter',
                    'javascript',
                ],
            ],
            [
                'title' => 'Contact Form with File Attachment',
                'slug' => 'contact-form-with-file-attach',
                'description' => 'A support contact form including a file upload field for screenshots or documents.',
                'storage_path' => 'contact-form/contact-form-with-file-attach',
                'customizable_vars' => [
                    '--accent' => '#475569',
                ],
                'tags' => [
                    'file-attachment',
                    'bug-report',
                ],
            ],
            [
                'title' => 'Contact Form with Social Links Footer',
                'slug' => 'contact-form-social-links',
                'description' => 'A contact form with social media icon links displayed below the submit button.',
                'storage_path' => 'contact-form/contact-form-social-links',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'social-links',
                    'footer-links',
                ],
            ],
            [
                'title' => 'Dark Theme Contact Form',
                'slug' => 'contact-form-dark-theme',
                'description' => 'A contact form styled for dark-themed websites, with subtle borders instead of shadows.',
                'storage_path' => 'contact-form/contact-form-dark-theme',
                'customizable_vars' => [
                    '--accent' => '#38bdf8',
                ],
                'tags' => [
                    'dark-mode',
                ],
            ],
            [
                'title' => 'Contact Form with Live Validation',
                'slug' => 'contact-form-with-validation',
                'description' => 'A contact form with live JS validation showing red/green states as you type.',
                'storage_path' => 'contact-form/contact-form-with-validation',
                'customizable_vars' => [
                    '--accent' => '#be123c',
                ],
                'tags' => [
                    'validation',
                    'javascript',
                ],
            ],
            [
                'title' => 'Contact Form with Business Hours',
                'slug' => 'contact-form-business-hours',
                'description' => 'A contact form sidebar showing business hours alongside the message fields.',
                'storage_path' => 'contact-form/contact-form-business-hours',
                'customizable_vars' => [
                    '--accent' => '#4338ca',
                ],
                'tags' => [
                    'business-hours',
                    'sidebar-info',
                ],
            ],
            [
                'title' => 'Minimal Underline Contact Form',
                'slug' => 'contact-form-minimal-underline',
                'description' => 'A no-box contact form using only bottom-border underlines for fields, ultra minimal.',
                'storage_path' => 'contact-form/contact-form-minimal-underline',
                'customizable_vars' => [
                    '--accent' => '#000000',
                ],
                'tags' => [
                    'minimal',
                    'underline',
                    'typography',
                ],
            ],
            [
                'title' => 'Contact Form with FAQ Suggestion',
                'slug' => 'contact-form-with-faq-link',
                'description' => 'A support contact form that suggests checking the FAQ first, with a link, before submitting.',
                'storage_path' => 'contact-form/contact-form-with-faq-link',
                'customizable_vars' => [
                    '--accent' => '#0284c7',
                ],
                'tags' => [
                    'faq-link',
                    'deflection',
                ],
            ],
            [
                'title' => 'Multi-Step Contact Form',
                'slug' => 'contact-form-multi-step',
                'description' => 'A contact form split across two steps (info, then message) with progress dots, via JS.',
                'storage_path' => 'contact-form/contact-form-multi-step',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'multi-step',
                    'javascript',
                    'progress-dots',
                ],
            ],
            [
                'title' => 'Contact Form with Live Chat Alternative',
                'slug' => 'contact-form-with-live-chat-cta',
                'description' => 'A contact form offering a live chat button as a faster alternative to filling the form.',
                'storage_path' => 'contact-form/contact-form-with-live-chat-cta',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'live-chat',
                    'alternative-cta',
                ],
            ],
            [
                'title' => 'Contact Form with Newsletter Opt-in',
                'slug' => 'contact-form-newsletter-checkbox',
                'description' => 'A contact form including an optional checkbox to also subscribe to the newsletter.',
                'storage_path' => 'contact-form/contact-form-newsletter-checkbox',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'newsletter-optin',
                    'checkbox',
                ],
            ],
            [
                'title' => 'Contact Form with Icon Info Grid',
                'slug' => 'contact-form-icon-grid-info',
                'description' => 'A contact form preceded by a grid of icon+label contact methods (email, phone, chat) above the fields.',
                'storage_path' => 'contact-form/contact-form-icon-grid-info',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'icon-grid',
                    'contact-methods',
                ],
            ],
            [
                'title' => 'Contact Form with Priority Level',
                'slug' => 'contact-form-with-priority-select',
                'description' => 'A support form letting the user flag the urgency of their request via radio buttons.',
                'storage_path' => 'contact-form/contact-form-with-priority-select',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'priority-level',
                    'support-ticket',
                ],
            ],
            [
                'title' => 'Contact Form with Pill-Shaped Inputs',
                'slug' => 'contact-form-rounded-pill-inputs',
                'description' => 'A soft, friendly contact form using fully rounded pill input fields.',
                'storage_path' => 'contact-form/contact-form-rounded-pill-inputs',
                'customizable_vars' => [
                    '--accent' => '#0d9488',
                ],
                'tags' => [
                    'pill-shape',
                    'soft',
                ],
            ],
            [
                'title' => 'Contact Form with Response Time Note',
                'slug' => 'contact-form-with-response-time',
                'description' => 'A contact form that sets expectations with a small note about typical response time.',
                'storage_path' => 'contact-form/contact-form-with-response-time',
                'customizable_vars' => [
                    '--accent' => '#1e40af',
                ],
                'tags' => [
                    'response-time',
                    'sales-form',
                    'b2b',
                ],
            ],
            [
                'title' => 'Contact Form with Budget Range Slider',
                'slug' => 'contact-form-with-budget-range',
                'description' => 'A project inquiry contact form including a budget range slider, common in agency/freelance sites.',
                'storage_path' => 'contact-form/contact-form-with-budget-range',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'budget-slider',
                    'javascript',
                    'agency-form',
                ],
            ],
            [
                'title' => 'Glassmorphic Contact Form Overlay',
                'slug' => 'contact-form-glass-overlay',
                'description' => 'A frosted-glass contact form floating over a vibrant gradient background.',
                'storage_path' => 'contact-form/contact-form-glass-overlay',
                'customizable_vars' => [],
                'tags' => [
                    'glassmorphism',
                    'gradient-background',
                ],
            ],
            [
                'title' => 'Contact Form with Spam Protection Note',
                'slug' => 'contact-form-with-honeypot-note',
                'description' => 'A contact form displaying a small reassurance note about spam protection near the submit button.',
                'storage_path' => 'contact-form/contact-form-with-honeypot-note',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'spam-protection',
                    'trust-signal',
                ],
            ],
            [
                'title' => 'Event RSVP Style Contact Form',
                'slug' => 'contact-form-event-rsvp-style',
                'description' => 'A contact form styled for event RSVPs, including a \'will you attend\' choice alongside the message.',
                'storage_path' => 'contact-form/contact-form-event-rsvp-style',
                'customizable_vars' => [
                    '--accent' => '#ea580c',
                ],
                'tags' => [
                    'rsvp',
                    'event-form',
                ],
            ],
            [
                'title' => 'Contact Form with Satisfaction Context',
                'slug' => 'contact-form-with-rating-context',
                'description' => 'A support form that first asks for a quick satisfaction rating before the message field, giving context to the support team.',
                'storage_path' => 'contact-form/contact-form-with-rating-context',
                'customizable_vars' => [
                    '--star-color' => '#f59e0b',
                ],
                'tags' => [
                    'rating-context',
                    'feedback-form',
                ],
            ],
            [
                'title' => 'Combined Contact + Newsletter Form',
                'slug' => 'contact-form-newsletter-combo',
                'description' => 'A form offering two distinct purposes (general contact vs newsletter only) via tab switching, via JS.',
                'storage_path' => 'contact-form/contact-form-newsletter-combo',
                'customizable_vars' => [
                    '--accent' => '#4f46e5',
                ],
                'tags' => [
                    'tabbed-form',
                    'javascript',
                    'dual-purpose',
                ],
            ],
            [
                'title' => 'Contact Form with Mood Emoji Picker',
                'slug' => 'contact-form-with-emoji-mood',
                'description' => 'A friendly contact form starting with an emoji mood picker to set the tone of the message.',
                'storage_path' => 'contact-form/contact-form-with-emoji-mood',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'mood-picker',
                    'playful',
                    'emoji',
                ],
            ],
            [
                'title' => 'Contact Form as Sticky Footer Bar',
                'slug' => 'contact-form-sticky-footer-cta',
                'description' => 'A slim contact form embedded directly into a sticky page footer for always-visible reachability.',
                'storage_path' => 'contact-form/contact-form-sticky-footer-cta',
                'customizable_vars' => [
                    '--accent' => '#111827',
                ],
                'tags' => [
                    'sticky-footer',
                    'always-visible',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
