<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "dark-mode-toggle" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class DarkModeToggleDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'dark-mode-toggle')->first();

        if (!$section) {
            $this->command?->warn("Section 'dark-mode-toggle' not found — skipping DarkModeToggleDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'iOS-Style Dark Mode Switch',
                'slug' => 'ios-style-toggle',
                'description' => 'The classic rounded sliding switch used to toggle dark mode, with smooth knob animation.',
                'storage_path' => 'dark-mode-toggle/ios-style-toggle',
                'customizable_vars' => [
                    '--on-color' => '#16a34a',
                ],
                'tags' => [
                    'ios-style',
                    'javascript',
                    'classic',
                ],
            ],
            [
                'title' => 'Sun/Moon Icon Toggle',
                'slug' => 'sun-moon-icon-toggle',
                'description' => 'A toggle switch where the knob contains a sun or moon icon that swaps based on state.',
                'storage_path' => 'dark-mode-toggle/sun-moon-icon-toggle',
                'customizable_vars' => [
                    '--track-color' => '#fbbf24',
                ],
                'tags' => [
                    'icon-toggle',
                    'sun-moon',
                    'javascript',
                ],
            ],
            [
                'title' => 'Theme Card Selector Toggle',
                'slug' => 'checkbox-card-toggle',
                'description' => 'Two side-by-side theme preview cards (Light/Dark) the user clicks to select instead of a switch.',
                'storage_path' => 'dark-mode-toggle/checkbox-card-toggle',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'card-selector',
                    'javascript',
                    'preview-cards',
                ],
            ],
            [
                'title' => 'Animated Stars Background Toggle',
                'slug' => 'animated-stars-toggle',
                'description' => 'A toggle switch that reveals tiny twinkling stars in its track when dark mode is active.',
                'storage_path' => 'dark-mode-toggle/animated-stars-toggle',
                'customizable_vars' => [
                    '--night-color' => '#1e293b',
                ],
                'tags' => [
                    'stars',
                    'decorative',
                    'javascript',
                ],
            ],
            [
                'title' => 'Labeled Light/Dark Toggle',
                'slug' => 'text-label-toggle',
                'description' => 'A simple toggle with explicit \'Light\' and \'Dark\' text labels on either side of the switch.',
                'storage_path' => 'dark-mode-toggle/text-label-toggle',
                'customizable_vars' => [
                    '--accent' => '#111827',
                ],
                'tags' => [
                    'labeled',
                    'text-hints',
                    'javascript',
                ],
            ],
            [
                'title' => 'Three-Way Theme Toggle',
                'slug' => 'system-preference-toggle',
                'description' => 'A three-option segmented toggle for Light / Dark / System, common in modern app settings.',
                'storage_path' => 'dark-mode-toggle/system-preference-toggle',
                'customizable_vars' => [
                    '--accent' => '#4f46e5',
                ],
                'tags' => [
                    'three-way',
                    'system-preference',
                    'javascript',
                ],
            ],
            [
                'title' => 'Gradient Sky Toggle',
                'slug' => 'gradient-sky-toggle',
                'description' => 'A toggle track that transitions its background gradient from day-sky blue to night-sky purple.',
                'storage_path' => 'dark-mode-toggle/gradient-sky-toggle',
                'customizable_vars' => [
                    '--day-color' => '#60a5fa',
                    '--night-color' => '#312e81',
                ],
                'tags' => [
                    'gradient',
                    'sky-theme',
                    'javascript',
                ],
            ],
            [
                'title' => 'Ripple Fill Theme Toggle',
                'slug' => 'ripple-fill-toggle',
                'description' => 'Clicking the toggle triggers a circular ripple that expands across the whole page to reveal the new theme.',
                'storage_path' => 'dark-mode-toggle/ripple-fill-toggle',
                'customizable_vars' => [],
                'tags' => [
                    'ripple-transition',
                    'javascript',
                    'page-wide',
                ],
            ],
            [
                'title' => 'Brightness Slider Toggle',
                'slug' => 'toggle-with-percentage',
                'description' => 'A horizontal slider (rather than a binary switch) that adjusts a simulated brightness/theme darkness level.',
                'storage_path' => 'dark-mode-toggle/toggle-with-percentage',
                'customizable_vars' => [
                    '--accent' => '#f59e0b',
                ],
                'tags' => [
                    'slider',
                    'brightness',
                    'javascript',
                ],
            ],
            [
                'title' => 'Emoji Cycle Theme Toggle',
                'slug' => 'emoji-cycle-toggle',
                'description' => 'A single button that cycles through Light → Dark → System modes each time it\'s clicked, with emoji feedback.',
                'storage_path' => 'dark-mode-toggle/emoji-cycle-toggle',
                'customizable_vars' => [
                    '--accent' => '#1f2937',
                ],
                'tags' => [
                    'cycle-button',
                    'javascript',
                    'three-state',
                ],
            ],
            [
                'title' => 'Eclipse Style Toggle',
                'slug' => 'checkbox-eclipse-toggle',
                'description' => 'A circular toggle where a \'shadow\' slides over a sun shape to simulate an eclipse transitioning to night.',
                'storage_path' => 'dark-mode-toggle/checkbox-eclipse-toggle',
                'customizable_vars' => [
                    '--sun-color' => '#fbbf24',
                ],
                'tags' => [
                    'eclipse',
                    'circular',
                    'javascript',
                ],
            ],
            [
                'title' => 'Theme Change Confirmation Toast',
                'slug' => 'toggle-with-confirmation',
                'description' => 'Toggling dark mode shows a brief confirmation toast (\'Dark mode enabled\') alongside the switch.',
                'storage_path' => 'dark-mode-toggle/toggle-with-confirmation',
                'customizable_vars' => [
                    '--accent' => '#0891b2',
                ],
                'tags' => [
                    'confirmation-toast',
                    'javascript',
                    'feedback',
                ],
            ],
            [
                'title' => 'Sidebar-Style Theme Toggle Item',
                'slug' => 'sidebar-icon-toggle',
                'description' => 'A toggle styled to look exactly like a sidebar navigation item, with icon and label inline.',
                'storage_path' => 'dark-mode-toggle/sidebar-icon-toggle',
                'customizable_vars' => [
                    '--accent' => '#374151',
                ],
                'tags' => [
                    'sidebar-style',
                    'nav-item',
                    'javascript',
                ],
            ],
            [
                'title' => 'Glowing Edge Toggle',
                'slug' => 'glow-edge-toggle',
                'description' => 'A toggle switch whose knob has a soft glow that intensifies when dark mode is active.',
                'storage_path' => 'dark-mode-toggle/glow-edge-toggle',
                'customizable_vars' => [
                    '--glow-color' => '#818cf8',
                ],
                'tags' => [
                    'glow-effect',
                    'javascript',
                    'ambient',
                ],
            ],
            [
                'title' => 'Rotating Icon Theme Toggle',
                'slug' => 'rotate-icon-toggle',
                'description' => 'A single icon button that rotates 180 degrees and swaps between sun/moon when clicked.',
                'storage_path' => 'dark-mode-toggle/rotate-icon-toggle',
                'customizable_vars' => [],
                'tags' => [
                    'rotate-animation',
                    'icon-swap',
                    'javascript',
                ],
            ],
            [
                'title' => 'Toggle with Time-of-Day Label',
                'slug' => 'toggle-with-time-display',
                'description' => 'A theme toggle accompanied by a text label showing a simulated time matching the selected mode.',
                'storage_path' => 'dark-mode-toggle/toggle-with-time-display',
                'customizable_vars' => [
                    '--accent' => '#ea580c',
                ],
                'tags' => [
                    'time-display',
                    'contextual',
                    'javascript',
                ],
            ],
            [
                'title' => 'Gradient Knob Toggle',
                'slug' => 'colorful-gradient-knob-toggle',
                'description' => 'A toggle whose sliding knob itself has a gradient fill instead of plain white.',
                'storage_path' => 'dark-mode-toggle/colorful-gradient-knob-toggle',
                'customizable_vars' => [
                    '--g1' => '#f59e0b',
                    '--g2' => '#ef4444',
                ],
                'tags' => [
                    'gradient-knob',
                    'colorful',
                    'javascript',
                ],
            ],
            [
                'title' => 'Sleepy Eye Toggle',
                'slug' => 'checkbox-eye-toggle',
                'description' => 'A playful toggle shaped like an eye that closes (becomes a line) when dark mode is enabled.',
                'storage_path' => 'dark-mode-toggle/checkbox-eye-toggle',
                'customizable_vars' => [
                    '--accent' => '#0f172a',
                ],
                'tags' => [
                    'eye-shape',
                    'playful',
                    'javascript',
                ],
            ],
            [
                'title' => 'Shadow Shift Toggle Button',
                'slug' => 'toggle-button-shadow-shift',
                'description' => 'A button-style (not switch-style) toggle where the box-shadow direction flips to suggest light source change.',
                'storage_path' => 'dark-mode-toggle/toggle-button-shadow-shift',
                'customizable_vars' => [
                    '--accent' => '#fbbf24',
                ],
                'tags' => [
                    'shadow-direction',
                    'neumorphic-hint',
                    'javascript',
                ],
            ],
            [
                'title' => 'Cloud & Sun Scene Toggle',
                'slug' => 'animated-cloud-sun-toggle',
                'description' => 'A small animated scene toggle showing a sun behind clouds for light mode and stars for dark mode.',
                'storage_path' => 'dark-mode-toggle/animated-cloud-sun-toggle',
                'customizable_vars' => [
                    '--sky-color' => '#7dd3fc',
                    '--night-sky' => '#1e1b4b',
                ],
                'tags' => [
                    'scene-animation',
                    'decorative',
                    'javascript',
                ],
            ],
            [
                'title' => 'Theme Toggle with Shortcut Hint',
                'slug' => 'toggle-with-keyboard-shortcut',
                'description' => 'A theme toggle button that also responds to a keyboard shortcut (Ctrl+J), with the hint shown inline.',
                'storage_path' => 'dark-mode-toggle/toggle-with-keyboard-shortcut',
                'customizable_vars' => [
                    '--accent' => '#1f2937',
                ],
                'tags' => [
                    'keyboard-shortcut',
                    'javascript',
                    'power-user',
                ],
            ],
            [
                'title' => 'Toggle with Saved Preference Note',
                'slug' => 'toggle-with-persisted-state',
                'description' => 'A theme toggle that displays a small note confirming the preference will be remembered (simulated, no real storage).',
                'storage_path' => 'dark-mode-toggle/toggle-with-persisted-state',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'preference-note',
                    'javascript',
                    'ux-detail',
                ],
            ],
            [
                'title' => 'Particle Burst Theme Toggle',
                'slug' => 'toggle-with-particles',
                'description' => 'Clicking the toggle releases a small burst of star/sparkle particles, purely decorative feedback via JS.',
                'storage_path' => 'dark-mode-toggle/toggle-with-particles',
                'customizable_vars' => [],
                'tags' => [
                    'particle-effect',
                    'javascript',
                    'playful-feedback',
                ],
            ],
            [
                'title' => 'Flip Card Theme Toggle',
                'slug' => 'flip-card-theme-toggle',
                'description' => 'A small card that flips over to reveal the opposite theme icon, used as the toggle trigger itself.',
                'storage_path' => 'dark-mode-toggle/flip-card-theme-toggle',
                'customizable_vars' => [],
                'tags' => [
                    'flip-card',
                    '3d',
                    'javascript',
                ],
            ],
            [
                'title' => 'Toggle with Status Indicator Dot',
                'slug' => 'toggle-with-status-dot',
                'description' => 'A switch paired with a small colored status dot that changes from yellow to indigo based on the active theme.',
                'storage_path' => 'dark-mode-toggle/toggle-with-status-dot',
                'customizable_vars' => [
                    '--light-status' => '#fbbf24',
                    '--dark-status' => '#6366f1',
                ],
                'tags' => [
                    'status-dot',
                    'indicator',
                    'javascript',
                ],
            ],
            [
                'title' => 'Toggle with Live Preview Thumbnail',
                'slug' => 'toggle-with-preview-thumbnail',
                'description' => 'A toggle accompanied by a tiny preview swatch showing what the new theme will look like before switching.',
                'storage_path' => 'dark-mode-toggle/toggle-with-preview-thumbnail',
                'customizable_vars' => [
                    '--accent' => '#be185d',
                ],
                'tags' => [
                    'preview-swatch',
                    'javascript',
                    'visual-feedback',
                ],
            ],
            [
                'title' => 'Background Image Crossfade Toggle',
                'slug' => 'toggle-with-bg-image-shift',
                'description' => 'Toggling switches between two full background gradients with a smooth crossfade, simulating day/night scenery.',
                'storage_path' => 'dark-mode-toggle/toggle-with-bg-image-shift',
                'customizable_vars' => [],
                'tags' => [
                    'crossfade',
                    'scenery',
                    'javascript',
                ],
            ],
            [
                'title' => 'Toggle with Mute-Style Icon Pattern',
                'slug' => 'toggle-with-sound-icon-hint',
                'description' => 'A toggle reusing the familiar \'speaker on/off\' interaction pattern but applied to theme, with a slash icon for dark mode.',
                'storage_path' => 'dark-mode-toggle/toggle-with-sound-icon-hint',
                'customizable_vars' => [],
                'tags' => [
                    'icon-reuse',
                    'sun-icon',
                    'javascript',
                ],
            ],
            [
                'title' => 'Celebrate Light Mode Toggle',
                'slug' => 'toggle-with-confetti-light',
                'description' => 'A toggle that releases a small celebratory animation only when switching back to light mode, a fun easter-egg detail.',
                'storage_path' => 'dark-mode-toggle/toggle-with-confetti-light',
                'customizable_vars' => [],
                'tags' => [
                    'easter-egg',
                    'celebratory',
                    'javascript',
                ],
            ],
            [
                'title' => 'Contrast Preview Bar Toggle',
                'slug' => 'toggle-with-contrast-preview-bar',
                'description' => 'A toggle next to a small horizontal bar that visually shifts from light-to-dark gradient as a literal contrast preview.',
                'storage_path' => 'dark-mode-toggle/toggle-with-contrast-preview-bar',
                'customizable_vars' => [
                    '--accent' => '#475569',
                ],
                'tags' => [
                    'contrast-preview',
                    'javascript',
                    'visual-bar',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
