<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "dashboard-ui-components" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class DashboardUiComponentsDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'dashboard-ui-components')->first();

        if (!$section) {
            $this->command?->warn("Section 'dashboard-ui-components' not found — skipping DashboardUiComponentsDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Dashboard Stat Cards Row',
                'slug' => 'stat-cards-row',
                'description' => 'A row of four KPI summary cards showing key metrics with trend arrows, the classic dashboard top row.',
                'storage_path' => 'dashboard-ui-components/stat-cards-row',
                'customizable_vars' => [
                    '--up-color' => '#16a34a',
                    '--down-color' => '#dc2626',
                ],
                'tags' => [
                    'kpi-cards',
                    'stats-row',
                ],
            ],
            [
                'title' => 'Simple Bar Chart Widget',
                'slug' => 'bar-chart-widget',
                'description' => 'A dashboard widget displaying a basic CSS-only bar chart for monthly data comparison.',
                'storage_path' => 'dashboard-ui-components/bar-chart-widget',
                'customizable_vars' => [
                    '--bar-color' => '#6366f1',
                ],
                'tags' => [
                    'bar-chart',
                    'css-only',
                    'data-viz',
                ],
            ],
            [
                'title' => 'Donut Chart Widget',
                'slug' => 'donut-chart-widget',
                'description' => 'A dashboard widget showing a CSS conic-gradient donut chart with a center label.',
                'storage_path' => 'dashboard-ui-components/donut-chart-widget',
                'customizable_vars' => [
                    '--donut-color' => '#ec4899',
                ],
                'tags' => [
                    'donut-chart',
                    'conic-gradient',
                ],
            ],
            [
                'title' => 'Dashboard Sidebar Navigation',
                'slug' => 'sidebar-nav-dashboard',
                'description' => 'A vertical dashboard sidebar with sections, icons, and an active state indicator.',
                'storage_path' => 'dashboard-ui-components/sidebar-nav-dashboard',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'sidebar',
                    'navigation',
                    'dashboard-shell',
                ],
            ],
            [
                'title' => 'Recent Activity Feed Widget',
                'slug' => 'recent-activity-feed-widget',
                'description' => 'A dashboard widget listing recent user activity events with timestamps and icons.',
                'storage_path' => 'dashboard-ui-components/recent-activity-feed-widget',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'activity-feed',
                    'timeline',
                ],
            ],
            [
                'title' => 'Line Chart Trend Widget',
                'slug' => 'line-chart-widget',
                'description' => 'A dashboard widget using SVG to draw a simple line chart showing a trend over time.',
                'storage_path' => 'dashboard-ui-components/line-chart-widget',
                'customizable_vars' => [],
                'tags' => [
                    'line-chart',
                    'svg',
                    'trend',
                ],
            ],
            [
                'title' => 'Recent Orders Table Widget',
                'slug' => 'table-widget-recent-orders',
                'description' => 'A dashboard widget showing a compact table of recent orders with status badges.',
                'storage_path' => 'dashboard-ui-components/table-widget-recent-orders',
                'customizable_vars' => [],
                'tags' => [
                    'table-widget',
                    'orders',
                    'status-badge',
                ],
            ],
            [
                'title' => 'Goal Progress Widget',
                'slug' => 'goal-progress-widget',
                'description' => 'A dashboard widget showing progress toward a numeric goal with a circular progress ring.',
                'storage_path' => 'dashboard-ui-components/goal-progress-widget',
                'customizable_vars' => [],
                'tags' => [
                    'progress-ring',
                    'goal-tracker',
                ],
            ],
            [
                'title' => 'Top Products List Widget',
                'slug' => 'top-products-widget',
                'description' => 'A dashboard widget ranking top-performing items with a mini progress bar per row.',
                'storage_path' => 'dashboard-ui-components/top-products-widget',
                'customizable_vars' => [
                    '--accent' => '#f59e0b',
                ],
                'tags' => [
                    'ranked-list',
                    'leaderboard',
                ],
            ],
            [
                'title' => 'Notification Summary Widget',
                'slug' => 'notification-summary-widget',
                'description' => 'A small dashboard widget summarizing unread counts across categories like messages, alerts, tasks.',
                'storage_path' => 'dashboard-ui-components/notification-summary-widget',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'notification-summary',
                    'counts',
                ],
            ],
            [
                'title' => 'Dashboard Top Header Bar',
                'slug' => 'dashboard-header-search-bar',
                'description' => 'A complete dashboard top header with logo, search bar, and user avatar menu trigger.',
                'storage_path' => 'dashboard-ui-components/dashboard-header-search-bar',
                'customizable_vars' => [
                    '--accent' => '#4f46e5',
                ],
                'tags' => [
                    'header-bar',
                    'dashboard-shell',
                ],
            ],
            [
                'title' => 'Dashboard Date Range Filter Bar',
                'slug' => 'dashboard-date-range-filter',
                'description' => 'A filter bar at the top of a dashboard with a date-range selector and an export button.',
                'storage_path' => 'dashboard-ui-components/dashboard-date-range-filter',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'filter-bar',
                    'export',
                ],
            ],
            [
                'title' => 'Multi-Tab Dashboard Panel',
                'slug' => 'multi-tab-dashboard-panel',
                'description' => 'A dashboard panel with internal tabs (Overview, Analytics, Reports) switching content via JS.',
                'storage_path' => 'dashboard-ui-components/multi-tab-dashboard-panel',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'tabbed-panel',
                    'javascript',
                ],
            ],
            [
                'title' => 'Empty Chart Placeholder Widget',
                'slug' => 'dashboard-empty-chart-state',
                'description' => 'A dashboard widget shown when there\'s not yet enough data to chart, with a friendly message.',
                'storage_path' => 'dashboard-ui-components/dashboard-empty-chart-state',
                'customizable_vars' => [],
                'tags' => [
                    'empty-state',
                    'placeholder-chart',
                ],
            ],
            [
                'title' => 'Period Comparison Widget',
                'slug' => 'dashboard-comparison-widget',
                'description' => 'A widget comparing this period\'s metric against last period side-by-side with a delta indicator.',
                'storage_path' => 'dashboard-ui-components/dashboard-comparison-widget',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'comparison',
                    'period-over-period',
                ],
            ],
            [
                'title' => 'Team Members Widget',
                'slug' => 'dashboard-team-members-widget',
                'description' => 'A dashboard widget listing team members with avatars, roles, and online status.',
                'storage_path' => 'dashboard-ui-components/dashboard-team-members-widget',
                'customizable_vars' => [
                    '--online-color' => '#16a34a',
                ],
                'tags' => [
                    'team-list',
                    'status-indicator',
                ],
            ],
            [
                'title' => 'Quick Actions Grid Widget',
                'slug' => 'dashboard-quick-actions-widget',
                'description' => 'A dashboard widget showing a grid of quick action buttons for common tasks.',
                'storage_path' => 'dashboard-ui-components/dashboard-quick-actions-widget',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'quick-actions',
                    'shortcut-grid',
                ],
            ],
            [
                'title' => 'System Status Widget',
                'slug' => 'dashboard-server-status-widget',
                'description' => 'A widget showing live-style status indicators for system services (API, DB, CDN).',
                'storage_path' => 'dashboard-ui-components/dashboard-server-status-widget',
                'customizable_vars' => [
                    '--ok-color' => '#16a34a',
                    '--warn-color' => '#f59e0b',
                ],
                'tags' => [
                    'system-status',
                    'uptime',
                ],
            ],
            [
                'title' => 'Conversion Funnel Widget',
                'slug' => 'dashboard-funnel-widget',
                'description' => 'A dashboard widget visualizing a conversion funnel using progressively narrower bars.',
                'storage_path' => 'dashboard-ui-components/dashboard-funnel-widget',
                'customizable_vars' => [
                    '--accent' => '#0891b2',
                ],
                'tags' => [
                    'funnel-chart',
                    'conversion',
                ],
            ],
            [
                'title' => 'Geographic Distribution Widget',
                'slug' => 'dashboard-map-widget',
                'description' => 'A dashboard widget representing user distribution across regions using a simple bar-per-region layout.',
                'storage_path' => 'dashboard-ui-components/dashboard-map-widget',
                'customizable_vars' => [
                    '--accent' => '#4338ca',
                ],
                'tags' => [
                    'geographic',
                    'regional-stats',
                ],
            ],
            [
                'title' => 'Draggable Dashboard Widget Cards',
                'slug' => 'dashboard-card-drag-reorder',
                'description' => 'Dashboard summary cards that can be reordered via drag and drop, using native HTML5 drag events.',
                'storage_path' => 'dashboard-ui-components/dashboard-card-drag-reorder',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'drag-reorder',
                    'javascript',
                    'customizable-layout',
                ],
            ],
            [
                'title' => 'Mini Sparkline Trend Card',
                'slug' => 'dashboard-revenue-sparkline',
                'description' => 'A compact KPI card with a tiny inline SVG sparkline showing the trend shape without axes or labels.',
                'storage_path' => 'dashboard-ui-components/dashboard-revenue-sparkline',
                'customizable_vars' => [],
                'tags' => [
                    'sparkline',
                    'svg',
                    'compact-kpi',
                ],
            ],
            [
                'title' => 'CSAT Score Widget',
                'slug' => 'dashboard-customer-satisfaction-widget',
                'description' => 'A widget showing a customer satisfaction score with a smiley-based visual scale.',
                'storage_path' => 'dashboard-ui-components/dashboard-customer-satisfaction-widget',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'csat',
                    'satisfaction-score',
                ],
            ],
            [
                'title' => 'Recent Files Widget',
                'slug' => 'dashboard-recent-files-widget',
                'description' => 'A dashboard widget listing recently accessed files with type icons and modified time.',
                'storage_path' => 'dashboard-ui-components/dashboard-recent-files-widget',
                'customizable_vars' => [],
                'tags' => [
                    'file-list',
                    'recent-items',
                ],
            ],
            [
                'title' => 'Dashboard Alert Banner',
                'slug' => 'dashboard-alert-banner-widget',
                'description' => 'A full-width warning banner spanning the top of a dashboard, alerting about billing or system issues.',
                'storage_path' => 'dashboard-ui-components/dashboard-alert-banner-widget',
                'customizable_vars' => [
                    '--alert-bg' => '#fef3c7',
                    '--alert-text' => '#92400e',
                ],
                'tags' => [
                    'alert-banner',
                    'billing-warning',
                ],
            ],
            [
                'title' => 'Performance Gauge Widget',
                'slug' => 'dashboard-gauge-widget',
                'description' => 'A dashboard widget using a semi-circular gauge to show a performance score out of 100.',
                'storage_path' => 'dashboard-ui-components/dashboard-gauge-widget',
                'customizable_vars' => [],
                'tags' => [
                    'gauge-chart',
                    'performance-score',
                    'svg',
                ],
            ],
            [
                'title' => 'Onboarding Checklist Widget',
                'slug' => 'dashboard-onboarding-checklist',
                'description' => 'A dashboard widget guiding new users through setup steps with a progress percentage.',
                'storage_path' => 'dashboard-ui-components/dashboard-onboarding-checklist',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'onboarding-checklist',
                    'progress',
                ],
            ],
            [
                'title' => 'Billing Summary Widget',
                'slug' => 'dashboard-billing-summary-widget',
                'description' => 'A widget summarizing current plan, next billing date, and a manage-subscription button.',
                'storage_path' => 'dashboard-ui-components/dashboard-billing-summary-widget',
                'customizable_vars' => [
                    '--accent' => '#1e40af',
                ],
                'tags' => [
                    'billing-widget',
                    'subscription',
                ],
            ],
            [
                'title' => 'API Usage Limits Widget',
                'slug' => 'dashboard-api-usage-widget',
                'description' => 'A widget showing API call usage against a monthly quota with a warning state near the limit.',
                'storage_path' => 'dashboard-ui-components/dashboard-api-usage-widget',
                'customizable_vars' => [
                    '--warn-color' => '#f59e0b',
                ],
                'tags' => [
                    'api-usage',
                    'quota-limit',
                ],
            ],
            [
                'title' => 'Toggleable Widget Visibility Panel',
                'slug' => 'dashboard-widget-customizer-toggle',
                'description' => 'A settings panel letting users show/hide individual dashboard widgets via checkboxes, via JS.',
                'storage_path' => 'dashboard-ui-components/dashboard-widget-customizer-toggle',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'customization-panel',
                    'widget-visibility',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
