<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "date-picker" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class DatePickerDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'date-picker')->first();

        if (!$section) {
            $this->command?->warn("Section 'date-picker' not found — skipping DatePickerDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Native Styled Date Input',
                'slug' => 'native-date-input',
                'description' => 'A standard HTML date input with custom border and focus styling to match a design system.',
                'storage_path' => 'date-picker/native-date-input',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'native-input',
                    'simple',
                ],
            ],
            [
                'title' => 'Dropdown Calendar Date Picker',
                'slug' => 'dropdown-date-picker',
                'description' => 'A text input that reveals a calendar dropdown below it when clicked, via JS toggle.',
                'storage_path' => 'date-picker/dropdown-date-picker',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'dropdown',
                    'javascript',
                    'popup-calendar',
                ],
            ],
            [
                'title' => 'Inline Check-in/Check-out Picker',
                'slug' => 'range-date-picker-inline',
                'description' => 'Two side-by-side date fields styled as a single connected unit, common in hotel booking forms.',
                'storage_path' => 'date-picker/range-date-picker-inline',
                'customizable_vars' => [
                    '--accent' => '#0ea5e9',
                ],
                'tags' => [
                    'range-picker',
                    'booking',
                    'connected-fields',
                ],
            ],
            [
                'title' => 'iOS-Style Scroll Wheel Picker',
                'slug' => 'scroll-wheel-date-picker',
                'description' => 'A mobile-style date picker using three scrollable columns for month/day/year, mimicking native iOS wheels.',
                'storage_path' => 'date-picker/scroll-wheel-date-picker',
                'customizable_vars' => [
                    '--accent' => '#111827',
                ],
                'tags' => [
                    'scroll-wheel',
                    'ios-style',
                    'mobile',
                ],
            ],
            [
                'title' => 'Date Picker with Quick Presets',
                'slug' => 'date-picker-with-presets',
                'description' => 'A date input paired with preset shortcut buttons like \'Today\', \'Tomorrow\', \'Next Week\'.',
                'storage_path' => 'date-picker/date-picker-with-presets',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'presets',
                    'javascript',
                    'shortcuts',
                ],
            ],
            [
                'title' => 'Date Picker with Disabled Past Dates',
                'slug' => 'date-picker-disabled-past',
                'description' => 'A calendar date picker where all past dates are visually grayed out and unselectable.',
                'storage_path' => 'date-picker/date-picker-disabled-past',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'disabled-dates',
                    'validation',
                    'booking',
                ],
            ],
            [
                'title' => 'Birthday Picker with Age Display',
                'slug' => 'date-picker-with-age-validation',
                'description' => 'A date-of-birth picker that calculates and displays the resulting age live, via JS.',
                'storage_path' => 'date-picker/date-picker-with-age-validation',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'age-calculation',
                    'javascript',
                    'birthday',
                ],
            ],
            [
                'title' => 'Date and Time Combo Picker',
                'slug' => 'date-picker-with-time',
                'description' => 'A combined date and time selection input shown side by side as one logical unit.',
                'storage_path' => 'date-picker/date-picker-with-time',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'date-time',
                    'combo-input',
                ],
            ],
            [
                'title' => 'Card-Style Date Display Picker',
                'slug' => 'date-picker-card-style',
                'description' => 'A date picker where the selected date is shown as a large styled card (day, month, year stacked).',
                'storage_path' => 'date-picker/date-picker-card-style',
                'customizable_vars' => [
                    '--accent' => '#ea580c',
                ],
                'tags' => [
                    'card-display',
                    'stacked-date',
                ],
            ],
            [
                'title' => 'Week Selector Date Picker',
                'slug' => 'date-picker-fiscal-week',
                'description' => 'A date picker that highlights the entire week when any single day in it is hovered, via JS.',
                'storage_path' => 'date-picker/date-picker-fiscal-week',
                'customizable_vars' => [
                    '--accent' => '#0d9488',
                ],
                'tags' => [
                    'week-selector',
                    'javascript',
                    'hover-highlight',
                ],
            ],
            [
                'title' => 'Masked Date Input (DD/MM/YYYY)',
                'slug' => 'date-picker-input-mask',
                'description' => 'A text input that auto-formats as the user types digits into a DD/MM/YYYY pattern, via JS.',
                'storage_path' => 'date-picker/date-picker-input-mask',
                'customizable_vars' => [
                    '--accent' => '#475569',
                ],
                'tags' => [
                    'input-mask',
                    'javascript',
                    'auto-format',
                ],
            ],
            [
                'title' => 'Dark Mode Date Picker',
                'slug' => 'date-picker-dark-mode',
                'description' => 'A dropdown calendar date picker styled for dark-themed applications.',
                'storage_path' => 'date-picker/date-picker-dark-mode',
                'customizable_vars' => [
                    '--accent' => '#818cf8',
                ],
                'tags' => [
                    'dark-mode',
                    'javascript',
                    'dropdown',
                ],
            ],
            [
                'title' => 'Recurring Date Selector',
                'slug' => 'date-picker-recurring-options',
                'description' => 'A date picker accompanied by a dropdown for recurrence (Daily, Weekly, Monthly), common in calendar apps.',
                'storage_path' => 'date-picker/date-picker-recurring-options',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'recurring',
                    'select-combo',
                ],
            ],
            [
                'title' => 'Bounded Date Picker (Min/Max)',
                'slug' => 'date-picker-min-max-range',
                'description' => 'A calendar date picker where dates outside an allowed booking window are disabled and visually distinct.',
                'storage_path' => 'date-picker/date-picker-min-max-range',
                'customizable_vars' => [
                    '--accent' => '#1d4ed8',
                ],
                'tags' => [
                    'min-max-range',
                    'booking-window',
                ],
            ],
            [
                'title' => 'Icon-Triggered Date Picker',
                'slug' => 'date-picker-with-icon-trigger',
                'description' => 'A text input with a calendar icon button that opens the picker when clicked, rather than the input itself.',
                'storage_path' => 'date-picker/date-picker-with-icon-trigger',
                'customizable_vars' => [
                    '--accent' => '#0891b2',
                ],
                'tags' => [
                    'icon-trigger',
                    'calendar-button',
                ],
            ],
            [
                'title' => 'Side-by-Side Two Month Picker',
                'slug' => 'date-picker-multi-month-view',
                'description' => 'A date range picker showing two months side by side simultaneously, common in advanced booking tools.',
                'storage_path' => 'date-picker/date-picker-multi-month-view',
                'customizable_vars' => [
                    '--accent' => '#be185d',
                ],
                'tags' => [
                    'two-month-view',
                    'range-selection',
                    'advanced',
                ],
            ],
            [
                'title' => 'Relative Date Labels Picker',
                'slug' => 'date-picker-relative-labels',
                'description' => 'A date list using relative human labels (Today, Yesterday, This Week) instead of raw dates where possible.',
                'storage_path' => 'date-picker/date-picker-relative-labels',
                'customizable_vars' => [
                    '--accent' => '#4338ca',
                ],
                'tags' => [
                    'relative-labels',
                    'human-readable',
                ],
            ],
            [
                'title' => 'Date Picker with Validation Error',
                'slug' => 'date-picker-with-error-state',
                'description' => 'A date input showing a red error border and message when an invalid or required date is missing.',
                'storage_path' => 'date-picker/date-picker-with-error-state',
                'customizable_vars' => [
                    '--danger' => '#dc2626',
                ],
                'tags' => [
                    'validation-error',
                    'form-feedback',
                ],
            ],
            [
                'title' => 'Sliding Month Transition Picker',
                'slug' => 'date-picker-slide-month-transition',
                'description' => 'A calendar where navigating to next/prev month slides the grid horizontally, via JS+CSS transition.',
                'storage_path' => 'date-picker/date-picker-slide-month-transition',
                'customizable_vars' => [
                    '--accent' => '#0ea5e9',
                ],
                'tags' => [
                    'slide-transition',
                    'javascript',
                    'month-navigation',
                ],
            ],
            [
                'title' => 'Keyboard-Navigable Date Picker',
                'slug' => 'date-picker-with-keyboard-nav',
                'description' => 'A date grid where arrow keys move focus between days and Enter selects, for full keyboard accessibility.',
                'storage_path' => 'date-picker/date-picker-with-keyboard-nav',
                'customizable_vars' => [
                    '--accent' => '#334155',
                ],
                'tags' => [
                    'accessibility',
                    'keyboard-navigation',
                    'javascript',
                ],
            ],
            [
                'title' => 'Fade-In Calendar Popup',
                'slug' => 'date-picker-fade-transition-popup',
                'description' => 'A date input whose calendar dropdown fades and scales in smoothly rather than appearing instantly.',
                'storage_path' => 'date-picker/date-picker-fade-transition-popup',
                'customizable_vars' => [
                    '--accent' => '#f59e0b',
                ],
                'tags' => [
                    'fade-animation',
                    'javascript',
                    'popup',
                ],
            ],
            [
                'title' => 'Date Picker with Clear Button',
                'slug' => 'date-picker-with-clear-button',
                'description' => 'A date input with a small \'x\' button that resets the field, appearing only once a date is chosen.',
                'storage_path' => 'date-picker/date-picker-with-clear-button',
                'customizable_vars' => [
                    '--accent' => '#475569',
                ],
                'tags' => [
                    'clear-button',
                    'javascript',
                    'reset',
                ],
            ],
            [
                'title' => 'Business Days Only Picker',
                'slug' => 'date-picker-business-days-only',
                'description' => 'A calendar where weekends are visually disabled, only allowing weekday (business day) selection.',
                'storage_path' => 'date-picker/date-picker-business-days-only',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'business-days',
                    'weekday-only',
                    'scheduling',
                ],
            ],
            [
                'title' => 'Date Picker with Info Tooltip',
                'slug' => 'date-picker-with-tooltip-info',
                'description' => 'A date input with an info icon that reveals a tooltip explaining date format requirements.',
                'storage_path' => 'date-picker/date-picker-with-tooltip-info',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'tooltip',
                    'info-icon',
                    'card-expiry',
                ],
            ],
            [
                'title' => 'Year + Month Dropdown Picker',
                'slug' => 'date-picker-fiscal-year-select',
                'description' => 'A date picker using two plain select dropdowns (Month, Year) instead of a calendar grid, simplest possible pattern.',
                'storage_path' => 'date-picker/date-picker-fiscal-year-select',
                'customizable_vars' => [
                    '--accent' => '#be123c',
                ],
                'tags' => [
                    'dropdown-select',
                    'simple',
                    'no-calendar',
                ],
            ],
            [
                'title' => 'Date Picker with Jump-to-Today',
                'slug' => 'date-picker-with-today-button',
                'description' => 'A calendar with a persistent \'Today\' button that immediately scrolls/jumps the selection back to the current date.',
                'storage_path' => 'date-picker/date-picker-with-today-button',
                'customizable_vars' => [
                    '--accent' => '#4f46e5',
                ],
                'tags' => [
                    'today-button',
                    'javascript',
                    'quick-jump',
                ],
            ],
            [
                'title' => 'Glassmorphic Date Picker',
                'slug' => 'date-picker-glass-style',
                'description' => 'A frosted-glass styled dropdown calendar picker sitting over a colorful background.',
                'storage_path' => 'date-picker/date-picker-glass-style',
                'customizable_vars' => [],
                'tags' => [
                    'glassmorphism',
                    'colorful-background',
                ],
            ],
            [
                'title' => 'Date Picker with Sidebar Shortcuts',
                'slug' => 'date-picker-with-shortcuts-sidebar',
                'description' => 'A calendar paired with a vertical sidebar of common range shortcuts (Last 7 days, This Month, etc).',
                'storage_path' => 'date-picker/date-picker-with-shortcuts-sidebar',
                'customizable_vars' => [
                    '--accent' => '#0284c7',
                ],
                'tags' => [
                    'sidebar-shortcuts',
                    'range-presets',
                    'analytics-style',
                ],
            ],
            [
                'title' => 'Large Touch-Friendly Date Picker',
                'slug' => 'date-picker-touch-friendly',
                'description' => 'A date picker with oversized tap targets specifically designed for touchscreens, with generous spacing.',
                'storage_path' => 'date-picker/date-picker-touch-friendly',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'touch-friendly',
                    'large-targets',
                    'mobile',
                ],
            ],
            [
                'title' => 'Picker with Explicit Confirm/Cancel',
                'slug' => 'date-picker-with-confirm-cancel',
                'description' => 'A calendar dropdown requiring an explicit \'Apply\' click rather than auto-closing on date selection, common in analytics tools.',
                'storage_path' => 'date-picker/date-picker-with-confirm-cancel',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'confirm-apply',
                    'javascript',
                    'analytics-tool',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
