<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "footer" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class FooterDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'footer')->first();

        if (!$section) {
            $this->command?->warn("Section 'footer' not found — skipping FooterDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Basic Multi-Column Footer',
                'slug' => 'basic-multicolumn-footer',
                'description' => 'A classic 4-column footer with link groups and a copyright line at the bottom.',
                'storage_path' => 'footer/basic-multicolumn-footer',
                'customizable_vars' => [
                    '--bg-color' => '#111827',
                    '--text-color' => '#9ca3af',
                ],
                'tags' => [
                    'multi-column',
                    'classic',
                ],
            ],
            [
                'title' => 'Footer with Newsletter Signup',
                'slug' => 'footer-with-newsletter-signup',
                'description' => 'A footer including an embedded email signup form alongside the standard link columns.',
                'storage_path' => 'footer/footer-with-newsletter-signup',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                    '--bg-color' => '#0f172a',
                ],
                'tags' => [
                    'newsletter',
                    'lead-capture',
                ],
            ],
            [
                'title' => 'Minimal Centered Footer',
                'slug' => 'minimal-centered-footer',
                'description' => 'A super simple footer with centered logo, a few links, and copyright — no columns at all.',
                'storage_path' => 'footer/minimal-centered-footer',
                'customizable_vars' => [],
                'tags' => [
                    'minimal',
                    'centered',
                ],
            ],
            [
                'title' => 'Footer with Social Media Icons',
                'slug' => 'footer-with-social-icons',
                'description' => 'A footer with a prominent row of circular social media icon links above the copyright line.',
                'storage_path' => 'footer/footer-with-social-icons',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'social-icons',
                    'centered',
                ],
            ],
            [
                'title' => 'Dark Footer with App Store Badges',
                'slug' => 'footer-dark-with-app-badges',
                'description' => 'A dark footer featuring app store download badge placeholders alongside link columns.',
                'storage_path' => 'footer/footer-dark-with-app-badges',
                'customizable_vars' => [
                    '--bg-color' => '#1e1b4b',
                ],
                'tags' => [
                    'app-badges',
                    'dark-mode',
                ],
            ],
            [
                'title' => 'Footer with Back-to-Top Button',
                'slug' => 'footer-with-back-to-top',
                'description' => 'A footer including a circular back-to-top button that smoothly scrolls the page up, via JS.',
                'storage_path' => 'footer/footer-with-back-to-top',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'back-to-top',
                    'javascript',
                ],
            ],
            [
                'title' => 'Footer with Security Trust Badges',
                'slug' => 'footer-with-trust-badges-row',
                'description' => 'A footer with a row of trust/security badges (SSL, payment methods) above the link columns.',
                'storage_path' => 'footer/footer-with-trust-badges-row',
                'customizable_vars' => [],
                'tags' => [
                    'trust-badges',
                    'ecommerce-footer',
                ],
            ],
            [
                'title' => 'Footer with Language/Currency Selector',
                'slug' => 'footer-with-language-currency',
                'description' => 'A footer including dropdown selectors for language and currency, common on international e-commerce sites.',
                'storage_path' => 'footer/footer-with-language-currency',
                'customizable_vars' => [],
                'tags' => [
                    'language-currency',
                    'i18n',
                ],
            ],
            [
                'title' => 'Glassmorphic Footer',
                'slug' => 'footer-glassmorphic',
                'description' => 'A footer with a frosted-glass effect over a colorful gradient background.',
                'storage_path' => 'footer/footer-glassmorphic',
                'customizable_vars' => [],
                'tags' => [
                    'glassmorphism',
                    'gradient-background',
                ],
            ],
            [
                'title' => 'Footer with Full Sitemap Links',
                'slug' => 'footer-with-sitemap-links',
                'description' => 'A dense footer with 5 columns of links, mimicking a complete sitemap, common on large content sites.',
                'storage_path' => 'footer/footer-with-sitemap-links',
                'customizable_vars' => [],
                'tags' => [
                    'sitemap',
                    'dense-links',
                ],
            ],
            [
                'title' => 'Footer with Contact Info Block',
                'slug' => 'footer-with-contact-info-block',
                'description' => 'A footer dedicating one column entirely to contact details (address, phone, email).',
                'storage_path' => 'footer/footer-with-contact-info-block',
                'customizable_vars' => [],
                'tags' => [
                    'contact-info',
                    'address-block',
                ],
            ],
            [
                'title' => 'Mobile Accordion Footer Links',
                'slug' => 'footer-with-accordion-mobile',
                'description' => 'A footer where each link group collapses into an accordion on smaller screens, expandable via JS.',
                'storage_path' => 'footer/footer-with-accordion-mobile',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'accordion',
                    'mobile-pattern',
                    'javascript',
                ],
            ],
            [
                'title' => 'Footer with System Status Link',
                'slug' => 'footer-with-status-page-link',
                'description' => 'A footer including a live-style status indicator link to a system status page.',
                'storage_path' => 'footer/footer-with-status-page-link',
                'customizable_vars' => [
                    '--ok-color' => '#16a34a',
                ],
                'tags' => [
                    'status-link',
                    'saas-footer',
                ],
            ],
            [
                'title' => 'Footer with Logo and Tagline',
                'slug' => 'footer-with-logo-tagline',
                'description' => 'A simple footer featuring a larger brand logo and tagline, with links arranged underneath.',
                'storage_path' => 'footer/footer-with-logo-tagline',
                'customizable_vars' => [
                    '--accent' => '#4338ca',
                ],
                'tags' => [
                    'logo-tagline',
                    'branding',
                ],
            ],
            [
                'title' => 'Footer with Cookie Preferences Link',
                'slug' => 'footer-with-cookie-settings-link',
                'description' => 'A footer including a \'Cookie Settings\' link, distinct from the privacy policy, for GDPR-compliant sites.',
                'storage_path' => 'footer/footer-with-cookie-settings-link',
                'customizable_vars' => [
                    '--accent' => '#0891b2',
                ],
                'tags' => [
                    'cookie-settings',
                    'gdpr',
                ],
            ],
            [
                'title' => 'Footer with Mini Search Bar',
                'slug' => 'footer-with-quick-search',
                'description' => 'A footer including a small search input to find content, common on documentation sites.',
                'storage_path' => 'footer/footer-with-quick-search',
                'customizable_vars' => [
                    '--accent' => '#1e40af',
                ],
                'tags' => [
                    'search-bar',
                    'docs-footer',
                ],
            ],
            [
                'title' => 'Dark Single-Line Footer',
                'slug' => 'footer-dark-minimal-line',
                'description' => 'An extremely compact single-line dark footer, just copyright and two links, nothing else.',
                'storage_path' => 'footer/footer-dark-minimal-line',
                'customizable_vars' => [],
                'tags' => [
                    'minimal',
                    'single-line',
                    'dark-mode',
                ],
            ],
            [
                'title' => 'Footer with Review Rating Badge',
                'slug' => 'footer-with-rating-badge',
                'description' => 'A footer displaying an aggregate review score badge (like Trustpilot) alongside copyright.',
                'storage_path' => 'footer/footer-with-rating-badge',
                'customizable_vars' => [
                    '--accent' => '#f59e0b',
                ],
                'tags' => [
                    'rating-badge',
                    'social-proof',
                ],
            ],
            [
                'title' => 'Footer with Side-by-Side Newsletter Panel',
                'slug' => 'footer-with-newsletter-side-by-side',
                'description' => 'A footer split into two panels: link columns on the left, a colored newsletter signup panel on the right.',
                'storage_path' => 'footer/footer-with-newsletter-side-by-side',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'split-panel',
                    'newsletter',
                ],
            ],
            [
                'title' => 'Footer with App Version Number',
                'slug' => 'footer-with-version-number',
                'description' => 'A footer showing the current app/build version number, common in SaaS dashboard footers.',
                'storage_path' => 'footer/footer-with-version-number',
                'customizable_vars' => [
                    '--accent' => '#475569',
                ],
                'tags' => [
                    'version-number',
                    'dashboard-footer',
                ],
            ],
            [
                'title' => 'Footer Newsletter with Success State',
                'slug' => 'footer-with-newsletter-success-state',
                'description' => 'A footer signup form that swaps to a thank-you message after submission, via JS.',
                'storage_path' => 'footer/footer-with-newsletter-success-state',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'newsletter',
                    'success-state',
                    'javascript',
                ],
            ],
            [
                'title' => 'Footer with Payment Method Icons',
                'slug' => 'footer-with-payment-icons-row',
                'description' => 'An e-commerce footer with a row of accepted payment method badges.',
                'storage_path' => 'footer/footer-with-payment-icons-row',
                'customizable_vars' => [],
                'tags' => [
                    'payment-icons',
                    'ecommerce',
                ],
            ],
            [
                'title' => 'Footer with Gradient CTA Band',
                'slug' => 'footer-gradient-cta-band',
                'description' => 'A footer led by a bold gradient call-to-action band before the standard link columns.',
                'storage_path' => 'footer/footer-gradient-cta-band',
                'customizable_vars' => [
                    '--g1' => '#6366f1',
                    '--g2' => '#ec4899',
                ],
                'tags' => [
                    'cta-band',
                    'gradient',
                ],
            ],
            [
                'title' => 'Footer with Team Photo Strip',
                'slug' => 'footer-with-team-photos-strip',
                'description' => 'A footer including a small row of circular team member avatars, personalizing the brand.',
                'storage_path' => 'footer/footer-with-team-photos-strip',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'team-photos',
                    'personal-touch',
                ],
            ],
            [
                'title' => 'Footer with FAQ Quick Links',
                'slug' => 'footer-with-faq-quick-links',
                'description' => 'A footer featuring direct links to the most commonly asked questions, reducing support load.',
                'storage_path' => 'footer/footer-with-faq-quick-links',
                'customizable_vars' => [
                    '--accent' => '#0284c7',
                ],
                'tags' => [
                    'faq-links',
                    'support-deflection',
                ],
            ],
            [
                'title' => 'Footer with Expand All Links Toggle',
                'slug' => 'footer-with-mini-sitemap-toggle',
                'description' => 'A footer with a \'Show all links\' toggle that expands additional sitemap sections, via JS.',
                'storage_path' => 'footer/footer-with-mini-sitemap-toggle',
                'customizable_vars' => [
                    '--accent' => '#4338ca',
                ],
                'tags' => [
                    'expandable-links',
                    'javascript',
                ],
            ],
            [
                'title' => 'Footer with Dark Mode Toggle',
                'slug' => 'footer-with-theme-toggle',
                'description' => 'A footer that includes its own dark mode toggle switch, separate from any header control.',
                'storage_path' => 'footer/footer-with-theme-toggle',
                'customizable_vars' => [
                    '--accent' => '#1f2937',
                ],
                'tags' => [
                    'dark-mode-toggle',
                    'javascript',
                ],
            ],
            [
                'title' => 'Footer with Platform Stats',
                'slug' => 'footer-with-mini-stats',
                'description' => 'A footer showing small platform stats (total designs, users) for social proof, before the link columns.',
                'storage_path' => 'footer/footer-with-mini-stats',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'platform-stats',
                    'social-proof',
                ],
            ],
            [
                'title' => 'Footer with Support Hotline Banner',
                'slug' => 'footer-with-emergency-contact',
                'description' => 'A footer prominently displaying a support phone number for urgent contact, common in service businesses.',
                'storage_path' => 'footer/footer-with-emergency-contact',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'support-hotline',
                    'service-business',
                ],
            ],
            [
                'title' => 'Three-Tier Comprehensive Footer',
                'slug' => 'footer-three-tier-layout',
                'description' => 'A comprehensive footer with three distinct tiers: CTA band, link columns, and a bottom legal bar.',
                'storage_path' => 'footer/footer-three-tier-layout',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'three-tier',
                    'comprehensive',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
