<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "forms" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class FormsDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'forms')->first();

        if (!$section) {
            $this->command?->warn("Section 'forms' not found — skipping FormsDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Contact Inquiry Form',
                'slug' => 'contact-inquiry-form',
                'description' => 'A standard multi-field contact form with name, email, subject, and message.',
                'storage_path' => 'forms/contact-inquiry-form',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'contact',
                    'multi-field',
                ],
            ],
            [
                'title' => 'Inline Newsletter Form',
                'slug' => 'newsletter-inline-form',
                'description' => 'A horizontal single-row email capture form, ideal for footers or banners.',
                'storage_path' => 'forms/newsletter-inline-form',
                'customizable_vars' => [
                    '--accent' => '#111827',
                ],
                'tags' => [
                    'newsletter',
                    'inline',
                    'compact',
                ],
            ],
            [
                'title' => 'Multi-Step Survey Form',
                'slug' => 'multi-step-survey-form',
                'description' => 'A form split into multiple steps with a progress indicator, navigated via JS Next/Back.',
                'storage_path' => 'forms/multi-step-survey-form',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'multi-step',
                    'survey',
                    'javascript',
                    'progress',
                ],
            ],
            [
                'title' => 'Range Slider Input Form',
                'slug' => 'range-slider-form',
                'description' => 'A form using a styled range slider input with a live value display, updated via JS.',
                'storage_path' => 'forms/range-slider-form',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'range-slider',
                    'javascript',
                    'filter',
                ],
            ],
            [
                'title' => 'Radio Card Selector Form',
                'slug' => 'radio-card-select-form',
                'description' => 'A form where radio options are styled as selectable cards instead of plain dots, common in plan-pickers.',
                'storage_path' => 'forms/radio-card-select-form',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'radio-card',
                    'plan-selector',
                    'css-has',
                ],
            ],
            [
                'title' => 'File Upload with Preview Form',
                'slug' => 'file-drop-with-preview-form',
                'description' => 'A form with a file input that shows the selected filename and a remove option, via JS.',
                'storage_path' => 'forms/file-drop-with-preview-form',
                'customizable_vars' => [
                    '--accent' => '#ea580c',
                ],
                'tags' => [
                    'file-upload',
                    'javascript',
                    'preview',
                ],
            ],
            [
                'title' => 'Shipping Address Form',
                'slug' => 'address-autocomplete-form',
                'description' => 'A structured shipping/billing address form with grouped name, address, and city/zip rows.',
                'storage_path' => 'forms/address-autocomplete-form',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'address',
                    'shipping',
                    'grouped-fields',
                ],
            ],
            [
                'title' => 'Textarea with Character Counter',
                'slug' => 'character-counter-form',
                'description' => 'A message textarea showing a live remaining-character counter that turns red near the limit, via JS.',
                'storage_path' => 'forms/character-counter-form',
                'customizable_vars' => [
                    '--accent' => '#0ea5e9',
                ],
                'tags' => [
                    'character-counter',
                    'javascript',
                    'textarea',
                ],
            ],
            [
                'title' => 'Conditional Fields Form',
                'slug' => 'toggle-fields-form',
                'description' => 'A form where checking a box reveals an additional input field below it, via JS show/hide.',
                'storage_path' => 'forms/toggle-fields-form',
                'customizable_vars' => [
                    '--accent' => '#4f46e5',
                ],
                'tags' => [
                    'conditional-fields',
                    'javascript',
                    'dynamic-form',
                ],
            ],
            [
                'title' => 'Dual List Transfer Form',
                'slug' => 'dual-list-transfer-form',
                'description' => 'A form with two list boxes where clicking an item moves it from \'available\' to \'selected\', via JS.',
                'storage_path' => 'forms/dual-list-transfer-form',
                'customizable_vars' => [
                    '--accent' => '#be185d',
                ],
                'tags' => [
                    'dual-list',
                    'javascript',
                    'transfer-list',
                ],
            ],
            [
                'title' => 'Password Strength Meter Form',
                'slug' => 'password-strength-form',
                'description' => 'A signup password field with a live strength bar that updates color/width via JS as the user types.',
                'storage_path' => 'forms/password-strength-form',
                'customizable_vars' => [
                    '--weak' => '#dc2626',
                    '--medium' => '#f59e0b',
                    '--strong' => '#16a34a',
                ],
                'tags' => [
                    'password-strength',
                    'javascript',
                    'signup',
                ],
            ],
            [
                'title' => 'Tag Input Field Form',
                'slug' => 'tag-input-form',
                'description' => 'A form field where pressing Enter turns typed text into removable pill tags, via JS.',
                'storage_path' => 'forms/tag-input-form',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'tag-input',
                    'javascript',
                    'pills',
                ],
            ],
            [
                'title' => 'Rating Difficulty Form',
                'slug' => 'star-difficulty-form',
                'description' => 'A feedback form where the user selects a difficulty level using clickable emoji-style buttons.',
                'storage_path' => 'forms/star-difficulty-form',
                'customizable_vars' => [
                    '--accent' => '#f59e0b',
                ],
                'tags' => [
                    'feedback',
                    'javascript',
                    'selectable-buttons',
                ],
            ],
            [
                'title' => 'Click-to-Edit Inline Form',
                'slug' => 'inline-edit-form',
                'description' => 'Text that looks static but becomes an editable input field when clicked, saving on blur via JS.',
                'storage_path' => 'forms/inline-edit-form',
                'customizable_vars' => [
                    '--accent' => '#0891b2',
                ],
                'tags' => [
                    'inline-edit',
                    'javascript',
                    'content-editable',
                ],
            ],
            [
                'title' => 'NPS Score Survey Form',
                'slug' => 'survey-nps-form',
                'description' => 'A Net Promoter Score style form: pick a number 0-10, with color feedback on selection.',
                'storage_path' => 'forms/survey-nps-form',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'nps',
                    'survey',
                    'javascript',
                    'score-selector',
                ],
            ],
            [
                'title' => 'Autosave Status Form',
                'slug' => 'autosave-indicator-form',
                'description' => 'A form that shows a \'Saving... / Saved\' status indicator automatically as the user types, via JS debounce.',
                'storage_path' => 'forms/autosave-indicator-form',
                'customizable_vars' => [
                    '--saved-color' => '#16a34a',
                ],
                'tags' => [
                    'autosave',
                    'javascript',
                    'status-indicator',
                ],
            ],
            [
                'title' => 'Quantity Stepper Form',
                'slug' => 'quantity-stepper-form',
                'description' => 'A product quantity field with +/- buttons instead of raw number typing, controlled via JS.',
                'storage_path' => 'forms/quantity-stepper-form',
                'customizable_vars' => [
                    '--accent' => '#ea580c',
                ],
                'tags' => [
                    'quantity-stepper',
                    'javascript',
                    'ecommerce',
                ],
            ],
            [
                'title' => 'Simple Signature Pad Form',
                'slug' => 'signature-pad-form',
                'description' => 'A form including a canvas the user can draw a signature on with their mouse, using JS canvas drawing.',
                'storage_path' => 'forms/signature-pad-form',
                'customizable_vars' => [
                    '--accent' => '#1e293b',
                ],
                'tags' => [
                    'signature',
                    'canvas',
                    'javascript',
                ],
            ],
            [
                'title' => 'Settings Toggle List Form',
                'slug' => 'toggle-switch-settings-form',
                'description' => 'A settings panel with several labeled toggle switches stacked vertically, a very common preferences UI.',
                'storage_path' => 'forms/toggle-switch-settings-form',
                'customizable_vars' => [
                    '--accent' => '#4f46e5',
                ],
                'tags' => [
                    'settings',
                    'toggle-list',
                    'preferences',
                ],
            ],
            [
                'title' => 'Date Range Picker Form',
                'slug' => 'date-range-picker-form',
                'description' => 'A booking-style form with separate check-in/check-out date inputs side by side.',
                'storage_path' => 'forms/date-range-picker-form',
                'customizable_vars' => [
                    '--accent' => '#0284c7',
                ],
                'tags' => [
                    'date-range',
                    'booking',
                    'two-fields',
                ],
            ],
            [
                'title' => 'Mini Currency Converter Form',
                'slug' => 'currency-converter-form',
                'description' => 'A small form that converts an entered amount between two currencies live via JS calculation.',
                'storage_path' => 'forms/currency-converter-form',
                'customizable_vars' => [
                    '--accent' => '#15803d',
                ],
                'tags' => [
                    'currency-converter',
                    'javascript',
                    'calculation',
                ],
            ],
            [
                'title' => 'BMI Calculator Form',
                'slug' => 'bmi-calculator-form',
                'description' => 'A small health calculator form computing BMI live from height/weight inputs via JS.',
                'storage_path' => 'forms/bmi-calculator-form',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'calculator',
                    'javascript',
                    'health',
                ],
            ],
            [
                'title' => 'Thumbs Up/Down Feedback Form',
                'slug' => 'feedback-thumbs-form',
                'description' => 'A minimal feedback widget with thumbs up/down buttons that lock in the choice via JS.',
                'storage_path' => 'forms/feedback-thumbs-form',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'feedback',
                    'thumbs',
                    'javascript',
                ],
            ],
            [
                'title' => 'Autocomplete Suggestions Form',
                'slug' => 'autocomplete-search-form',
                'description' => 'A search input that shows a filtered list of matching suggestions below it as you type, via JS.',
                'storage_path' => 'forms/autocomplete-search-form',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'autocomplete',
                    'javascript',
                    'search-suggestions',
                ],
            ],
            [
                'title' => 'Emoji Mood Slider Form',
                'slug' => 'rating-emoji-slider-form',
                'description' => 'A slider input where the displayed emoji changes based on the slider\'s current position, via JS.',
                'storage_path' => 'forms/rating-emoji-slider-form',
                'customizable_vars' => [
                    '--accent' => '#f59e0b',
                ],
                'tags' => [
                    'mood-slider',
                    'javascript',
                    'emoji',
                ],
            ],
            [
                'title' => 'Two-Column Signup Form',
                'slug' => 'two-column-signup-form',
                'description' => 'A signup form arranging first/last name side by side for a more compact, professional feel.',
                'storage_path' => 'forms/two-column-signup-form',
                'customizable_vars' => [
                    '--accent' => '#1e40af',
                ],
                'tags' => [
                    'signup',
                    'two-column',
                    'compact',
                ],
            ],
            [
                'title' => 'Password Match Validator Form',
                'slug' => 'toggle-password-match-form',
                'description' => 'A signup form that live-checks if \'confirm password\' matches \'password\', showing a green check or red X via JS.',
                'storage_path' => 'forms/toggle-password-match-form',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'password-match',
                    'javascript',
                    'validation',
                ],
            ],
            [
                'title' => 'Budget Allocation Sliders Form',
                'slug' => 'budget-allocation-form',
                'description' => 'Multiple linked range sliders that together must total 100%, common in budget/allocation UIs.',
                'storage_path' => 'forms/budget-allocation-form',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'sliders',
                    'javascript',
                    'budget-allocation',
                ],
            ],
            [
                'title' => 'Apply Coupon Code Form',
                'slug' => 'coupon-code-form',
                'description' => 'A checkout-style coupon input that shows a success message and strikes through the old price when applied via JS.',
                'storage_path' => 'forms/coupon-code-form',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'coupon',
                    'javascript',
                    'checkout',
                ],
            ],
            [
                'title' => 'Location Permission Request Card',
                'slug' => 'location-permission-form',
                'description' => 'A form-adjacent card asking the user to share their location, with allow/deny actions and a JS-simulated response.',
                'storage_path' => 'forms/location-permission-form',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'permission-request',
                    'javascript',
                    'location',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
