<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "header" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class HeaderDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'header')->first();

        if (!$section) {
            $this->command?->warn("Section 'header' not found — skipping HeaderDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Basic Navbar Header',
                'slug' => 'basic-navbar-header',
                'description' => 'A standard horizontal navbar with logo on the left and nav links on the right.',
                'storage_path' => 'header/basic-navbar-header',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'navbar',
                    'basic',
                ],
            ],
            [
                'title' => 'Transparent Overlay Header',
                'slug' => 'transparent-hero-header',
                'description' => 'A header that sits transparent over a hero image, becoming opaque on scroll, via JS.',
                'storage_path' => 'header/transparent-hero-header',
                'customizable_vars' => [],
                'tags' => [
                    'transparent',
                    'scroll-effect',
                    'javascript',
                ],
            ],
            [
                'title' => 'Centered Logo Header',
                'slug' => 'centered-logo-header',
                'description' => 'A header with the logo perfectly centered and nav links split evenly on either side.',
                'storage_path' => 'header/centered-logo-header',
                'customizable_vars' => [
                    '--accent' => '#111827',
                ],
                'tags' => [
                    'centered-logo',
                    'split-nav',
                ],
            ],
            [
                'title' => 'Header with Dropdown Submenu',
                'slug' => 'header-with-dropdown-menu',
                'description' => 'A navbar where one nav item reveals a dropdown submenu on hover/click, via JS.',
                'storage_path' => 'header/header-with-dropdown-menu',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'dropdown-menu',
                    'javascript',
                ],
            ],
            [
                'title' => 'Header with Integrated Search',
                'slug' => 'header-with-search-bar',
                'description' => 'A navbar with a search input built directly into the header bar.',
                'storage_path' => 'header/header-with-search-bar',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'search-integrated',
                    'navbar',
                ],
            ],
            [
                'title' => 'Sticky Shrinking Header on Scroll',
                'slug' => 'sticky-shrink-header',
                'description' => 'A header that reduces its padding/height as the user scrolls down, via JS.',
                'storage_path' => 'header/sticky-shrink-header',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'sticky',
                    'shrink-on-scroll',
                    'javascript',
                ],
            ],
            [
                'title' => 'Header with Promo Banner Top Strip',
                'slug' => 'header-with-cta-banner',
                'description' => 'A two-layer header: a thin promotional banner above the main navbar.',
                'storage_path' => 'header/header-with-cta-banner',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'promo-banner',
                    'two-layer',
                ],
            ],
            [
                'title' => 'Header with Mega Menu',
                'slug' => 'header-with-mega-menu',
                'description' => 'A navbar item that opens a wide multi-column mega menu showing categorized links, via JS.',
                'storage_path' => 'header/header-with-mega-menu',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'mega-menu',
                    'javascript',
                ],
            ],
            [
                'title' => 'Header with Mobile Hamburger Menu',
                'slug' => 'header-mobile-hamburger',
                'description' => 'A header that collapses nav links into a hamburger icon, revealing a dropdown menu when clicked, via JS.',
                'storage_path' => 'header/header-mobile-hamburger',
                'customizable_vars' => [
                    '--accent' => '#1e40af',
                ],
                'tags' => [
                    'mobile-hamburger',
                    'javascript',
                ],
            ],
            [
                'title' => 'Header with Dark Mode Switch',
                'slug' => 'header-dark-mode-toggle',
                'description' => 'A navbar that includes a built-in dark/light mode toggle switch on the right side.',
                'storage_path' => 'header/header-dark-mode-toggle',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'dark-mode-toggle',
                    'javascript',
                ],
            ],
            [
                'title' => 'Header with User Avatar Dropdown',
                'slug' => 'header-with-user-avatar-menu',
                'description' => 'A logged-in style header where the right side shows a user avatar opening a profile dropdown, via JS.',
                'storage_path' => 'header/header-with-user-avatar-menu',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'avatar-dropdown',
                    'javascript',
                    'logged-in-state',
                ],
            ],
            [
                'title' => 'Glassmorphic Frosted Header',
                'slug' => 'header-glassmorphic',
                'description' => 'A header with a frosted-glass blur effect, designed to sit over colorful page backgrounds.',
                'storage_path' => 'header/header-glassmorphic',
                'customizable_vars' => [],
                'tags' => [
                    'glassmorphism',
                    'frosted',
                ],
            ],
            [
                'title' => 'Header with Notification Bell',
                'slug' => 'header-with-notification-bell',
                'description' => 'A navbar including a bell icon with an unread-count badge, opening a dropdown of recent alerts via JS.',
                'storage_path' => 'header/header-with-notification-bell',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'notification-bell',
                    'javascript',
                ],
            ],
            [
                'title' => 'Bold Split-Color Header',
                'slug' => 'header-bold-split-color',
                'description' => 'A navbar split into two colored halves diagonally, a bold distinctive branding choice.',
                'storage_path' => 'header/header-bold-split-color',
                'customizable_vars' => [
                    '--left-color' => '#111827',
                    '--right-color' => '#6366f1',
                ],
                'tags' => [
                    'split-color',
                    'bold-branding',
                ],
            ],
            [
                'title' => 'Header with Language Selector',
                'slug' => 'header-with-language-selector',
                'description' => 'A navbar including a language/region dropdown selector, common on international sites.',
                'storage_path' => 'header/header-with-language-selector',
                'customizable_vars' => [
                    '--accent' => '#0891b2',
                ],
                'tags' => [
                    'language-selector',
                    'i18n',
                ],
            ],
            [
                'title' => 'Header with Dual CTA Buttons',
                'slug' => 'header-with-cta-buttons-pair',
                'description' => 'A navbar with two distinct call-to-action buttons (Login + Sign Up) styled differently for hierarchy.',
                'storage_path' => 'header/header-with-cta-buttons-pair',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'dual-cta',
                    'hierarchy',
                ],
            ],
            [
                'title' => 'Vertical Sidebar-Style Header',
                'slug' => 'header-vertical-sidebar-style',
                'description' => 'A header that runs vertically along the left edge instead of horizontally across the top.',
                'storage_path' => 'header/header-vertical-sidebar-style',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'vertical-header',
                    'side-nav',
                ],
            ],
            [
                'title' => 'Header with Page Scroll Progress Bar',
                'slug' => 'header-with-progress-indicator',
                'description' => 'A header with a thin progress bar at its very bottom edge showing scroll progress through the page, via JS.',
                'storage_path' => 'header/header-with-progress-indicator',
                'customizable_vars' => [
                    '--accent' => '#ea580c',
                ],
                'tags' => [
                    'scroll-progress',
                    'javascript',
                    'blog-style',
                ],
            ],
            [
                'title' => 'Header with Breadcrumb Sub-row',
                'slug' => 'header-with-breadcrumb-row',
                'description' => 'A two-tier header: main nav on top, a breadcrumb trail row directly beneath it.',
                'storage_path' => 'header/header-with-breadcrumb-row',
                'customizable_vars' => [
                    '--accent' => '#475569',
                ],
                'tags' => [
                    'breadcrumb-row',
                    'two-tier',
                ],
            ],
            [
                'title' => 'Icon-Only Minimal Header',
                'slug' => 'header-icon-only-nav',
                'description' => 'A super minimal header with just icon buttons, no text labels at all, for a sleek compact look.',
                'storage_path' => 'header/header-icon-only-nav',
                'customizable_vars' => [
                    '--accent' => '#111827',
                ],
                'tags' => [
                    'icon-only',
                    'minimal',
                ],
            ],
            [
                'title' => 'Header with Trust Badge Row',
                'slug' => 'header-with-trust-badges',
                'description' => 'A navbar with a secondary row of small trust badges (security, ratings) beneath the main nav.',
                'storage_path' => 'header/header-with-trust-badges',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'trust-badges',
                    'social-proof',
                ],
            ],
            [
                'title' => 'Header with Shopping Cart Badge',
                'slug' => 'header-with-cart-icon-badge',
                'description' => 'A navbar with a cart icon showing an item-count badge, the standard e-commerce header pattern.',
                'storage_path' => 'header/header-with-cart-icon-badge',
                'customizable_vars' => [
                    '--accent' => '#ea580c',
                ],
                'tags' => [
                    'shopping-cart',
                    'ecommerce-header',
                ],
            ],
            [
                'title' => 'Header with Scrolling Announcement',
                'slug' => 'header-with-marquee-announcement',
                'description' => 'A header with a continuously scrolling marquee-style announcement bar above the navbar.',
                'storage_path' => 'header/header-with-marquee-announcement',
                'customizable_vars' => [
                    '--accent' => '#4338ca',
                ],
                'tags' => [
                    'marquee',
                    'announcement',
                    'scrolling-text',
                ],
            ],
            [
                'title' => 'Header with Animated Active Underline',
                'slug' => 'header-underline-active-nav',
                'description' => 'A navbar where the active link has an underline that slides smoothly when switching, via JS.',
                'storage_path' => 'header/header-underline-active-nav',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'active-underline',
                    'javascript',
                ],
            ],
            [
                'title' => 'Header with System Status Dot',
                'slug' => 'header-with-status-indicator',
                'description' => 'A navbar including a small green \'all systems operational\' status indicator, common in SaaS dashboards.',
                'storage_path' => 'header/header-with-status-indicator',
                'customizable_vars' => [
                    '--ok-color' => '#16a34a',
                ],
                'tags' => [
                    'status-indicator',
                    'saas-style',
                ],
            ],
            [
                'title' => 'Header with Search Shortcut Hint',
                'slug' => 'header-with-keyboard-shortcut-hint',
                'description' => 'A navbar search bar showing a Cmd+K hint badge inside it for power users.',
                'storage_path' => 'header/header-with-keyboard-shortcut-hint',
                'customizable_vars' => [
                    '--accent' => '#1f2937',
                ],
                'tags' => [
                    'keyboard-hint',
                    'search-shortcut',
                    'docs-style',
                ],
            ],
            [
                'title' => 'Header with Gradient Background',
                'slug' => 'header-gradient-background',
                'description' => 'A navbar with a vibrant gradient fill instead of a flat color, for bold landing pages.',
                'storage_path' => 'header/header-gradient-background',
                'customizable_vars' => [
                    '--g1' => '#6366f1',
                    '--g2' => '#ec4899',
                ],
                'tags' => [
                    'gradient-background',
                    'bold',
                ],
            ],
            [
                'title' => 'Header with Back Navigation Button',
                'slug' => 'header-with-back-button',
                'description' => 'A simplified header showing only a back arrow and page title, common on detail/sub-pages.',
                'storage_path' => 'header/header-with-back-button',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'back-button',
                    'detail-page',
                ],
            ],
            [
                'title' => 'Header Using Tabs as Primary Nav',
                'slug' => 'header-with-tabs-navigation',
                'description' => 'A header where the main navigation is styled as a tab strip rather than plain links, with an active tab highlight.',
                'storage_path' => 'header/header-with-tabs-navigation',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'tab-navigation',
                    'app-style',
                ],
            ],
            [
                'title' => 'Header with Feedback Button',
                'slug' => 'header-with-feedback-button',
                'description' => 'A navbar including a persistent \'Give Feedback\' button, common in beta/early-access products.',
                'storage_path' => 'header/header-with-feedback-button',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'feedback-button',
                    'beta-product',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
