<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "loaders" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class LoadersDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'loaders')->first();

        if (!$section) {
            $this->command?->warn("Section 'loaders' not found — skipping LoadersDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Spinning Ring Loader',
                'slug' => 'spinning-ring-loader',
                'description' => 'The classic single-ring spinner using a border trick.',
                'storage_path' => 'loaders/spinning-ring-loader',
                'customizable_vars' => [
                    '--ring-color' => '#6366f1',
                ],
                'tags' => [
                    'spinner',
                    'ring',
                    'css-only',
                ],
            ],
            [
                'title' => 'Dual Color Ring Loader',
                'slug' => 'dual-ring-loader',
                'description' => 'Two rings rotating in opposite directions at different speeds for a layered effect.',
                'storage_path' => 'loaders/dual-ring-loader',
                'customizable_vars' => [
                    '--c1' => '#ec4899',
                    '--c2' => '#6366f1',
                ],
                'tags' => [
                    'dual-ring',
                    'layered',
                    'css-only',
                ],
            ],
            [
                'title' => 'Three Bouncing Dots',
                'slug' => 'bouncing-dots-loader',
                'description' => 'Three dots bouncing in sequence, the classic \'typing\' indicator.',
                'storage_path' => 'loaders/bouncing-dots-loader',
                'customizable_vars' => [
                    '--dot-color' => '#16a34a',
                ],
                'tags' => [
                    'dots',
                    'bounce',
                    'typing-indicator',
                ],
            ],
            [
                'title' => 'Pulsing Square Loader',
                'slug' => 'pulsing-square-loader',
                'description' => 'A square that scales and fades in a continuous pulse loop.',
                'storage_path' => 'loaders/pulsing-square-loader',
                'customizable_vars' => [
                    '--sq-color' => '#f59e0b',
                ],
                'tags' => [
                    'pulse',
                    'square',
                    'minimal',
                ],
            ],
            [
                'title' => 'Audio Equalizer Bars Loader',
                'slug' => 'bars-equalizer-loader',
                'description' => 'Vertical bars animating up and down like an audio equalizer/visualizer.',
                'storage_path' => 'loaders/bars-equalizer-loader',
                'customizable_vars' => [
                    '--bar-color' => '#8b5cf6',
                ],
                'tags' => [
                    'equalizer',
                    'bars',
                    'audio-style',
                ],
            ],
            [
                'title' => 'Percentage Counter Loader',
                'slug' => 'progress-percentage-loader',
                'description' => 'A loader that displays an actual incrementing percentage number via JS, common for file uploads.',
                'storage_path' => 'loaders/progress-percentage-loader',
                'customizable_vars' => [
                    '--ring-color' => '#0ea5e9',
                ],
                'tags' => [
                    'percentage',
                    'svg',
                    'javascript',
                    'upload-progress',
                ],
            ],
            [
                'title' => 'Skeleton Card Loader',
                'slug' => 'skeleton-card-loader',
                'description' => 'A full card-shaped skeleton placeholder with shimmering gray blocks, simulating a loading content card.',
                'storage_path' => 'loaders/skeleton-card-loader',
                'customizable_vars' => [],
                'tags' => [
                    'skeleton',
                    'card-placeholder',
                    'shimmer',
                ],
            ],
            [
                'title' => 'DNA Helix Loader',
                'slug' => 'dna-helix-loader',
                'description' => 'Dots arranged in a rotating double-helix-like wave pattern using staggered animation delays.',
                'storage_path' => 'loaders/dna-helix-loader',
                'customizable_vars' => [
                    '--dot-color' => '#06b6d4',
                ],
                'tags' => [
                    'dna-wave',
                    'javascript',
                    'dots-pattern',
                ],
            ],
            [
                'title' => 'Rotating Squares Loader',
                'slug' => 'rotating-squares-loader',
                'description' => 'Four small squares rotating together around a center point like a pinwheel.',
                'storage_path' => 'loaders/rotating-squares-loader',
                'customizable_vars' => [
                    '--sq-color' => '#ef4444',
                ],
                'tags' => [
                    'pinwheel',
                    'squares',
                    'css-only',
                ],
            ],
            [
                'title' => 'Loading Text with Animated Dots',
                'slug' => 'text-loading-dots-loader',
                'description' => 'The word \'Loading\' followed by dots that animate in sequence via JS, common in app splash screens.',
                'storage_path' => 'loaders/text-loading-dots-loader',
                'customizable_vars' => [
                    '--text-color' => '#374151',
                ],
                'tags' => [
                    'text-loader',
                    'javascript',
                    'splash-screen',
                ],
            ],
            [
                'title' => 'Indeterminate Stripe Bar Loader',
                'slug' => 'progress-stripe-loader',
                'description' => 'A horizontal progress bar with a sliding indeterminate stripe, common for top-of-page loading bars.',
                'storage_path' => 'loaders/progress-stripe-loader',
                'customizable_vars' => [
                    '--stripe-color' => '#2563eb',
                ],
                'tags' => [
                    'indeterminate',
                    'top-bar',
                    'progress',
                ],
            ],
            [
                'title' => 'Orbiting Dot Loader',
                'slug' => 'orbiting-dot-loader',
                'description' => 'A small dot orbiting around a static center dot, simulating an orbital motion path.',
                'storage_path' => 'loaders/orbiting-dot-loader',
                'customizable_vars' => [
                    '--moon-color' => '#f43f5e',
                    '--center-color' => '#1f2937',
                ],
                'tags' => [
                    'orbit',
                    'css-only',
                    'motion-path',
                ],
            ],
            [
                'title' => 'Gradient Conic Spinner',
                'slug' => 'gradient-spinner-loader',
                'description' => 'A spinner using a conic-gradient mask for a smooth fading-tail rotation effect.',
                'storage_path' => 'loaders/gradient-spinner-loader',
                'customizable_vars' => [
                    '--spin-color' => '#a855f7',
                ],
                'tags' => [
                    'conic-gradient',
                    'smooth',
                    'modern',
                ],
            ],
            [
                'title' => 'Skeleton Grid Loader',
                'slug' => 'card-grid-skeleton-loader',
                'description' => 'A grid of multiple skeleton placeholder cards loading simultaneously, simulating a content grid loading state.',
                'storage_path' => 'loaders/card-grid-skeleton-loader',
                'customizable_vars' => [],
                'tags' => [
                    'skeleton',
                    'grid',
                    'multiple-items',
                ],
            ],
            [
                'title' => 'Liquid Fill Loader',
                'slug' => 'liquid-fill-loader',
                'description' => 'A circular container that fills up with a wavy \'liquid\' level using an animated radial mask.',
                'storage_path' => 'loaders/liquid-fill-loader',
                'customizable_vars' => [
                    '--liquid-color' => '#0ea5e9',
                ],
                'tags' => [
                    'liquid',
                    'fill-animation',
                    'circular',
                ],
            ],
            [
                'title' => 'Heartbeat Pulse Loader',
                'slug' => 'heartbeat-pulse-loader',
                'description' => 'A heart-shaped icon that pulses like a heartbeat rhythm, double-beat pattern.',
                'storage_path' => 'loaders/heartbeat-pulse-loader',
                'customizable_vars' => [],
                'tags' => [
                    'heartbeat',
                    'icon-based',
                    'playful',
                ],
            ],
            [
                'title' => 'Hourglass Flip Loader',
                'slug' => 'hourglass-flip-loader',
                'description' => 'An hourglass emoji that flips 180 degrees repeatedly, simulating time passing.',
                'storage_path' => 'loaders/hourglass-flip-loader',
                'customizable_vars' => [],
                'tags' => [
                    'hourglass',
                    'icon-based',
                    'time',
                ],
            ],
            [
                'title' => 'Multi-Color Sequential Dots',
                'slug' => 'multi-color-dots-loader',
                'description' => 'Five dots each a different color, lighting up one after another in sequence.',
                'storage_path' => 'loaders/multi-color-dots-loader',
                'customizable_vars' => [],
                'tags' => [
                    'multi-color',
                    'sequential',
                    'dots',
                ],
            ],
            [
                'title' => 'Loading Bar with Inline Percent',
                'slug' => 'loading-bar-percentage-text-loader',
                'description' => 'A loading bar with the percentage number displayed directly inside the filled portion of the bar.',
                'storage_path' => 'loaders/loading-bar-percentage-text-loader',
                'customizable_vars' => [
                    '--fill-color' => '#16a34a',
                ],
                'tags' => [
                    'progress-bar',
                    'javascript',
                    'inline-text',
                ],
            ],
            [
                'title' => 'Book Page Flip Loader',
                'slug' => 'book-page-flip-loader',
                'description' => 'Two small rectangles flipping like book pages turning, using staggered 3D rotation.',
                'storage_path' => 'loaders/book-page-flip-loader',
                'customizable_vars' => [
                    '--page-color' => '#d97706',
                ],
                'tags' => [
                    'book-flip',
                    '3d',
                    'playful',
                ],
            ],
            [
                'title' => 'Dotted Circle Spinner',
                'slug' => 'dotted-circle-loader',
                'description' => 'Dots arranged in a circle, each fading in and out in sequence to create a spinning illusion.',
                'storage_path' => 'loaders/dotted-circle-loader',
                'customizable_vars' => [
                    '--dot-color' => '#db2777',
                ],
                'tags' => [
                    'circular-dots',
                    'javascript',
                    'fade',
                ],
            ],
            [
                'title' => 'Growing Bars Loader',
                'slug' => 'growing-bar-loader',
                'description' => 'Five vertical bars that grow tall then shrink in a smooth wave, like an audio spectrum.',
                'storage_path' => 'loaders/growing-bar-loader',
                'customizable_vars' => [
                    '--bar-color' => '#0d9488',
                ],
                'tags' => [
                    'growing-bars',
                    'wave',
                    'spectrum',
                ],
            ],
            [
                'title' => 'Rotating Text Ring Loader',
                'slug' => 'circular-text-loader',
                'description' => 'The word \'LOADING\' arranged in a circle that continuously rotates, using letter-spacing and transform.',
                'storage_path' => 'loaders/circular-text-loader',
                'customizable_vars' => [
                    '--text-color' => '#4f46e5',
                ],
                'tags' => [
                    'circular-text',
                    'javascript',
                    'rotating',
                ],
            ],
            [
                'title' => 'Split Flap Counter Loader',
                'slug' => 'split-flap-loader',
                'description' => 'A number that flips like an airport split-flap display, cycling 0-9 repeatedly via JS.',
                'storage_path' => 'loaders/split-flap-loader',
                'customizable_vars' => [
                    '--flap-bg' => '#1f2937',
                ],
                'tags' => [
                    'split-flap',
                    'javascript',
                    'counter',
                ],
            ],
            [
                'title' => 'Dashed Circle Spinner',
                'slug' => 'dashed-circle-spinner-loader',
                'description' => 'A spinner made from a dashed circle border that rotates continuously, giving a \'ticking clock\' feel.',
                'storage_path' => 'loaders/dashed-circle-spinner-loader',
                'customizable_vars' => [
                    '--dash-color' => '#475569',
                ],
                'tags' => [
                    'dashed-border',
                    'clock-style',
                    'css-only',
                ],
            ],
            [
                'title' => 'Full-Page Loading Overlay',
                'slug' => 'loading-overlay-fullpage-loader',
                'description' => 'A full-screen semi-transparent overlay with a centered spinner and message, the typical \'app is loading\' pattern.',
                'storage_path' => 'loaders/loading-overlay-fullpage-loader',
                'customizable_vars' => [
                    '--spinner-color' => '#2563eb',
                ],
                'tags' => [
                    'full-page',
                    'overlay',
                    'app-loading',
                ],
            ],
            [
                'title' => 'Morphing Shape Loader',
                'slug' => 'morphing-shape-loader',
                'description' => 'A shape that continuously morphs between circle and square while rotating, combining two transform techniques.',
                'storage_path' => 'loaders/morphing-shape-loader',
                'customizable_vars' => [
                    '--shape-color' => '#ec4899',
                ],
                'tags' => [
                    'morph',
                    'shape-shift',
                    'rotate',
                ],
            ],
            [
                'title' => 'Blinking Cursor Loader',
                'slug' => 'typing-cursor-loader',
                'description' => 'A simple blinking text cursor bar, useful as a minimal \'waiting for input/response\' indicator.',
                'storage_path' => 'loaders/typing-cursor-loader',
                'customizable_vars' => [
                    '--cursor-color' => '#16a34a',
                ],
                'tags' => [
                    'cursor-blink',
                    'ai-style',
                    'minimal',
                ],
            ],
            [
                'title' => 'Rainbow Gradient Spinner',
                'slug' => 'rainbow-spinner-loader',
                'description' => 'A spinner with a full rainbow conic gradient continuously rotating, vibrant and colorful.',
                'storage_path' => 'loaders/rainbow-spinner-loader',
                'customizable_vars' => [],
                'tags' => [
                    'rainbow',
                    'conic-gradient',
                    'colorful',
                ],
            ],
            [
                'title' => 'Flower Petal Spinner',
                'slug' => 'flower-petal-loader',
                'description' => 'Six small petal-shaped ovals arranged radially and rotating together, fading per petal for a blooming effect.',
                'storage_path' => 'loaders/flower-petal-loader',
                'customizable_vars' => [
                    '--petal-color' => '#f472b6',
                ],
                'tags' => [
                    'flower',
                    'petals',
                    'javascript',
                    'radial',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
