<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "login" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class LoginDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'login')->first();

        if (!$section) {
            $this->command?->warn("Section 'login' not found — skipping LoginDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Glassmorphic Login',
                'slug' => 'glassmorphic-login',
                'description' => 'A frosted-glass login card over a purple gradient backdrop.',
                'storage_path' => 'login/glassmorphic-login',
                'customizable_vars' => [
                    '--primary-color' => '#6366f1',
                    '--bg-start' => '#667eea',
                    '--bg-end' => '#764ba2',
                    '--radius' => '20px',
                ],
                'tags' => [
                    'glassmorphism',
                    'gradient',
                    'modern',
                ],
            ],
            [
                'title' => 'Split Screen Login',
                'slug' => 'split-screen-login',
                'description' => 'Two-panel login layout with a branded message on the left and the form on the right.',
                'storage_path' => 'login/split-screen-login',
                'customizable_vars' => [
                    '--panel-bg' => '#4f46e5',
                    '--radius' => '12px',
                ],
                'tags' => [
                    'split-screen',
                    'business',
                    'responsive',
                ],
            ],
            [
                'title' => 'Minimal Card Login',
                'slug' => 'minimal-card-login',
                'description' => 'A clean, no-frills login card for projects that want simplicity above all.',
                'storage_path' => 'login/minimal-card-login',
                'customizable_vars' => [
                    '--primary-color' => '#111827',
                    '--bg-color' => '#f3f4f6',
                    '--radius' => '8px',
                ],
                'tags' => [
                    'minimal',
                    'clean',
                ],
            ],
            [
                'title' => 'Dark Neon Login',
                'slug' => 'dark-neon-login',
                'description' => 'A dark-themed login form with neon cyan accents and glowing focus states.',
                'storage_path' => 'login/dark-neon-login',
                'customizable_vars' => [
                    '--neon' => '#22d3ee',
                ],
                'tags' => [
                    'dark-mode',
                    'neon',
                    'terminal',
                ],
            ],
            [
                'title' => 'Floating Label Login',
                'slug' => 'floating-label-login',
                'description' => 'Inputs with labels that float up above the field when focused or filled, using :placeholder-shown.',
                'storage_path' => 'login/floating-label-login',
                'customizable_vars' => [
                    '--primary-color' => '#2563eb',
                ],
                'tags' => [
                    'floating-label',
                    'css-only',
                    'form-ux',
                ],
            ],
            [
                'title' => 'Card Flip Login/Signup',
                'slug' => 'card-flip-login',
                'description' => 'A card that flips in 3D between Login and Sign Up forms using a JS toggle and CSS transforms.',
                'storage_path' => 'login/card-flip-login',
                'customizable_vars' => [
                    '--primary-color' => '#ec4899',
                ],
                'tags' => [
                    '3d-flip',
                    'javascript',
                    'signup-toggle',
                ],
            ],
            [
                'title' => 'Gradient Border Login',
                'slug' => 'gradient-border-login',
                'description' => 'A login card with an animated rotating gradient border ring.',
                'storage_path' => 'login/gradient-border-login',
                'customizable_vars' => [
                    '--g1' => '#06b6d4',
                    '--g2' => '#8b5cf6',
                ],
                'tags' => [
                    'gradient-border',
                    'animated',
                    'dark-mode',
                ],
            ],
            [
                'title' => 'Social Icons Login',
                'slug' => 'social-icons-login',
                'description' => 'A login form with prominent social-login buttons above a divider and the email form.',
                'storage_path' => 'login/social-icons-login',
                'customizable_vars' => [
                    '--primary-color' => '#4338ca',
                ],
                'tags' => [
                    'social-login',
                    'oauth-style',
                    'divider',
                ],
            ],
            [
                'title' => 'Full Image Background Login',
                'slug' => 'image-bg-login',
                'description' => 'A login form centered over a full-bleed background image with a dark overlay.',
                'storage_path' => 'login/image-bg-login',
                'customizable_vars' => [
                    '--primary-color' => '#f59e0b',
                ],
                'tags' => [
                    'background-image',
                    'overlay',
                    'travel',
                ],
            ],
            [
                'title' => 'Show/Hide Password Login',
                'slug' => 'show-password-login',
                'description' => 'A login form with an eye-icon toggle to reveal the password text, implemented in JS.',
                'storage_path' => 'login/show-password-login',
                'customizable_vars' => [
                    '--primary-color' => '#059669',
                ],
                'tags' => [
                    'show-password',
                    'javascript',
                    'ux',
                ],
            ],
            [
                'title' => 'Two-Step Login',
                'slug' => 'stepper-login',
                'description' => 'A login flow that asks for email first, then reveals the password field in a second step via JS.',
                'storage_path' => 'login/stepper-login',
                'customizable_vars' => [
                    '--primary-color' => '#1e40af',
                ],
                'tags' => [
                    'multi-step',
                    'javascript',
                    'progressive',
                ],
            ],
            [
                'title' => 'Centered Logo Login',
                'slug' => 'centered-logo-login',
                'description' => 'A login form with a prominent circular logo placeholder centered above the fields.',
                'storage_path' => 'login/centered-logo-login',
                'customizable_vars' => [
                    '--primary-color' => '#7c3aed',
                ],
                'tags' => [
                    'branding',
                    'centered',
                    'logo',
                ],
            ],
            [
                'title' => 'Login with Remember Me',
                'slug' => 'remember-me-login',
                'description' => 'A standard login form featuring a styled custom checkbox for \'Remember Me\' and a forgot-password link.',
                'storage_path' => 'login/remember-me-login',
                'customizable_vars' => [
                    '--primary-color' => '#0284c7',
                ],
                'tags' => [
                    'remember-me',
                    'forgot-password',
                    'standard',
                ],
            ],
            [
                'title' => 'Animated Background Blobs Login',
                'slug' => 'animated-bg-blobs-login',
                'description' => 'A login card floating over slowly drifting, blurred gradient blob shapes in the background.',
                'storage_path' => 'login/animated-bg-blobs-login',
                'customizable_vars' => [
                    '--blob-1' => '#818cf8',
                    '--blob-2' => '#f472b6',
                ],
                'tags' => [
                    'animated-background',
                    'blobs',
                    'decorative',
                ],
            ],
            [
                'title' => 'Inline Validation Login',
                'slug' => 'form-validation-login',
                'description' => 'A login form with live JS validation that marks fields red/green and shows error text.',
                'storage_path' => 'login/form-validation-login',
                'customizable_vars' => [
                    '--primary-color' => '#be123c',
                ],
                'tags' => [
                    'validation',
                    'javascript',
                    'form-feedback',
                ],
            ],
            [
                'title' => 'Sidebar Illustration Login',
                'slug' => 'sidebar-illustration-login',
                'description' => 'A login form with a narrow decorative gradient sidebar featuring an icon, rather than a full panel.',
                'storage_path' => 'login/sidebar-illustration-login',
                'customizable_vars' => [
                    '--g1' => '#f97316',
                    '--g2' => '#db2777',
                ],
                'tags' => [
                    'sidebar-accent',
                    'decorative',
                    'two-tone',
                ],
            ],
            [
                'title' => 'Pill Shaped Inputs Login',
                'slug' => 'pill-shaped-login',
                'description' => 'A login form using fully rounded pill-shaped input fields and button for a soft, modern look.',
                'storage_path' => 'login/pill-shaped-login',
                'customizable_vars' => [
                    '--primary-color' => '#0d9488',
                ],
                'tags' => [
                    'pill-shape',
                    'soft',
                    'rounded',
                ],
            ],
            [
                'title' => 'Left Illustration Login',
                'slug' => 'left-illustration-login',
                'description' => 'Login form paired with a large decorative SVG illustration panel on the left side.',
                'storage_path' => 'login/left-illustration-login',
                'customizable_vars' => [
                    '--panel-bg' => '#1d4ed8',
                ],
                'tags' => [
                    'illustration',
                    'svg',
                    'split-layout',
                ],
            ],
            [
                'title' => 'Login with Toast Feedback',
                'slug' => 'toast-feedback-login',
                'description' => 'A login form that shows a sliding toast notification on submit, simulating success feedback via JS.',
                'storage_path' => 'login/toast-feedback-login',
                'customizable_vars' => [
                    '--primary-color' => '#4d7c0f',
                ],
                'tags' => [
                    'toast',
                    'feedback',
                    'javascript',
                ],
            ],
            [
                'title' => 'Dotted Pattern Background Login',
                'slug' => 'dotted-pattern-login',
                'description' => 'A login card over a subtle repeating dot-grid background pattern made with CSS radial-gradient.',
                'storage_path' => 'login/dotted-pattern-login',
                'customizable_vars' => [
                    '--primary-color' => '#334155',
                ],
                'tags' => [
                    'pattern-background',
                    'dot-grid',
                    'subtle',
                ],
            ],
            [
                'title' => 'Compact Inline Login',
                'slug' => 'compact-inline-login',
                'description' => 'A horizontal, single-row login bar suited for a top navbar dropdown rather than a full page.',
                'storage_path' => 'login/compact-inline-login',
                'customizable_vars' => [
                    '--primary-color' => '#18181b',
                ],
                'tags' => [
                    'compact',
                    'inline',
                    'navbar-style',
                ],
            ],
            [
                'title' => 'Tabbed Login/Signup',
                'slug' => 'tabbed-login-signup',
                'description' => 'A card with two clickable tabs (Login / Sign Up) that swap the visible form via JS, with a sliding underline.',
                'storage_path' => 'login/tabbed-login-signup',
                'customizable_vars' => [
                    '--primary-color' => '#9333ea',
                ],
                'tags' => [
                    'tabs',
                    'javascript',
                    'signup-toggle',
                ],
            ],
            [
                'title' => 'Borderless Underline Login',
                'slug' => 'border-only-login',
                'description' => 'A minimalist login using only bottom-border underlines for inputs, no boxes at all.',
                'storage_path' => 'login/border-only-login',
                'customizable_vars' => [
                    '--primary-color' => '#000000',
                ],
                'tags' => [
                    'minimal',
                    'borderless',
                    'typography',
                ],
            ],
            [
                'title' => 'Login with Bot Check',
                'slug' => 'captcha-style-login',
                'description' => 'A login form including a \'I am not a robot\' style checkbox confirmation, mimicking CAPTCHA UX patterns.',
                'storage_path' => 'login/captcha-style-login',
                'customizable_vars' => [
                    '--primary-color' => '#2563eb',
                ],
                'tags' => [
                    'captcha-style',
                    'security-ux',
                    'checkbox',
                ],
            ],
            [
                'title' => 'Hover-Lift Login Card',
                'slug' => 'card-shadow-hover-login',
                'description' => 'A login card that lifts and deepens its shadow when the mouse hovers anywhere over it.',
                'storage_path' => 'login/card-shadow-hover-login',
                'customizable_vars' => [
                    '--primary-color' => '#ea580c',
                ],
                'tags' => [
                    'hover-effect',
                    'shadow',
                    'subtle',
                ],
            ],
            [
                'title' => 'Phone OTP Login',
                'slug' => 'phone-otp-login',
                'description' => 'A login flow using a phone number plus a 6-box OTP code input, with JS auto-advance between boxes.',
                'storage_path' => 'login/phone-otp-login',
                'customizable_vars' => [
                    '--primary-color' => '#15803d',
                ],
                'tags' => [
                    'otp',
                    'phone-auth',
                    'javascript',
                ],
            ],
            [
                'title' => 'Magazine Style Login',
                'slug' => 'magazine-style-login',
                'description' => 'An editorial, magazine-inspired login layout with bold oversized typography and asymmetric spacing.',
                'storage_path' => 'login/magazine-style-login',
                'customizable_vars' => [
                    '--primary-color' => '#000000',
                ],
                'tags' => [
                    'editorial',
                    'typography',
                    'bold',
                ],
            ],
            [
                'title' => 'Rounded Avatar Login',
                'slug' => 'rounded-avatar-login',
                'description' => 'A login card showing a circular user avatar placeholder above a greeting and the password field only (returning user pattern).',
                'storage_path' => 'login/rounded-avatar-login',
                'customizable_vars' => [
                    '--primary-color' => '#4f46e5',
                ],
                'tags' => [
                    'returning-user',
                    'avatar',
                    'personalized',
                ],
            ],
            [
                'title' => 'Testimonial Side Login',
                'slug' => 'side-quote-login',
                'description' => 'A split login where the side panel shows a rotating customer quote instead of pure branding.',
                'storage_path' => 'login/side-quote-login',
                'customizable_vars' => [
                    '--panel-bg' => '#065f46',
                ],
                'tags' => [
                    'testimonial',
                    'split-layout',
                    'social-proof',
                ],
            ],
            [
                'title' => 'Login with Theme Toggle',
                'slug' => 'dark-mode-toggle-login',
                'description' => 'A login card with its own self-contained light/dark mode switch in the corner, powered by JS class toggling.',
                'storage_path' => 'login/dark-mode-toggle-login',
                'customizable_vars' => [
                    '--primary-color' => '#6366f1',
                ],
                'tags' => [
                    'dark-mode',
                    'javascript',
                    'self-contained-toggle',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
