<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "logout" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class LogoutDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'logout')->first();

        if (!$section) {
            $this->command?->warn("Section 'logout' not found — skipping LogoutDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Simple Confirm Logout',
                'slug' => 'simple-confirm-logout',
                'description' => 'A centered card asking the user to confirm before logging out.',
                'storage_path' => 'logout/simple-confirm-logout',
                'customizable_vars' => [
                    '--danger' => '#dc2626',
                ],
                'tags' => [
                    'confirmation',
                    'modal-style',
                ],
            ],
            [
                'title' => 'Modal Overlay Logout',
                'slug' => 'modal-overlay-logout',
                'description' => 'A logout confirmation that appears as a dark-overlay modal over the page content.',
                'storage_path' => 'logout/modal-overlay-logout',
                'customizable_vars' => [
                    '--danger' => '#b91c1c',
                ],
                'tags' => [
                    'overlay',
                    'modal',
                    'backdrop',
                ],
            ],
            [
                'title' => 'Auto-Logout Countdown',
                'slug' => 'countdown-auto-logout',
                'description' => 'Warns the user of an inactivity timeout with a live JS countdown before forced logout.',
                'storage_path' => 'logout/countdown-auto-logout',
                'customizable_vars' => [
                    '--warn' => '#d97706',
                ],
                'tags' => [
                    'countdown',
                    'auto-logout',
                    'javascript',
                    'session-timeout',
                ],
            ],
            [
                'title' => 'Slide-Down Logout Bar',
                'slug' => 'slide-down-logout-bar',
                'description' => 'A thin notification bar that slides down from the top of the screen asking to confirm logout.',
                'storage_path' => 'logout/slide-down-logout-bar',
                'customizable_vars' => [
                    '--bar-bg' => '#1f2937',
                ],
                'tags' => [
                    'slide-down',
                    'notification-bar',
                    'javascript',
                ],
            ],
            [
                'title' => 'Icon-Only Logout Button',
                'slug' => 'icon-only-logout-button',
                'description' => 'A minimal circular icon button (common in navbars) that shows a tooltip and triggers logout directly.',
                'storage_path' => 'logout/icon-only-logout-button',
                'customizable_vars' => [
                    '--icon-color' => '#ef4444',
                ],
                'tags' => [
                    'icon-only',
                    'tooltip',
                    'navbar',
                ],
            ],
            [
                'title' => 'Dropdown Menu Logout',
                'slug' => 'dropdown-menu-logout',
                'description' => 'A user avatar dropdown menu where \'Log Out\' is the last item, toggled via JS.',
                'storage_path' => 'logout/dropdown-menu-logout',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'dropdown',
                    'avatar-menu',
                    'javascript',
                ],
            ],
            [
                'title' => 'Split Confirm/Cancel Card',
                'slug' => 'split-action-logout',
                'description' => 'A wide horizontally-split card: left side explains, right side has stacked action buttons.',
                'storage_path' => 'logout/split-action-logout',
                'customizable_vars' => [
                    '--danger' => '#dc2626',
                ],
                'tags' => [
                    'split-layout',
                    'wide-card',
                ],
            ],
            [
                'title' => 'Goodbye Message Screen',
                'slug' => 'goodbye-message-logout',
                'description' => 'A full-screen friendly goodbye message shown for a moment right after logging out, before redirect.',
                'storage_path' => 'logout/goodbye-message-logout',
                'customizable_vars' => [
                    '--accent' => '#4f46e5',
                ],
                'tags' => [
                    'goodbye-screen',
                    'redirect-style',
                    'full-page',
                ],
            ],
            [
                'title' => 'Swipe to Confirm Logout',
                'slug' => 'swipe-to-logout',
                'description' => 'A mobile-style \'swipe to confirm\' slider that triggers logout once dragged to the end, using JS drag tracking.',
                'storage_path' => 'logout/swipe-to-logout',
                'customizable_vars' => [
                    '--track-color' => '#fee2e2',
                    '--thumb-color' => '#dc2626',
                ],
                'tags' => [
                    'swipe',
                    'drag',
                    'javascript',
                    'mobile-pattern',
                ],
            ],
            [
                'title' => 'Warning Icon Logout',
                'slug' => 'centered-icon-warning-logout',
                'description' => 'A logout confirmation centered around a large triangular warning icon for emphasis.',
                'storage_path' => 'logout/centered-icon-warning-logout',
                'customizable_vars' => [
                    '--warn' => '#f59e0b',
                ],
                'tags' => [
                    'warning-icon',
                    'emphasis',
                ],
            ],
            [
                'title' => 'Sidebar Bottom Logout Link',
                'slug' => 'sidebar-logout-link',
                'description' => 'A logout link styled as it would appear pinned to the bottom of an app sidebar, with hover feedback.',
                'storage_path' => 'logout/sidebar-logout-link',
                'customizable_vars' => [
                    '--accent' => '#111827',
                ],
                'tags' => [
                    'sidebar',
                    'app-navigation',
                    'pinned-bottom',
                ],
            ],
            [
                'title' => 'Animated Door Close Logout',
                'slug' => 'animated-door-logout',
                'description' => 'A playful logout button where two panels slide shut like a door when clicked, via JS+CSS transition.',
                'storage_path' => 'logout/animated-door-logout',
                'customizable_vars' => [
                    '--door-color' => '#1e293b',
                ],
                'tags' => [
                    'animated',
                    'playful',
                    'javascript',
                    'transition',
                ],
            ],
            [
                'title' => 'Logout from All Devices',
                'slug' => 'two-factor-logout-all',
                'description' => 'A security-focused logout screen listing active sessions, with a \'log out everywhere\' action.',
                'storage_path' => 'logout/two-factor-logout-all',
                'customizable_vars' => [
                    '--danger' => '#dc2626',
                ],
                'tags' => [
                    'security',
                    'session-management',
                    'multi-device',
                ],
            ],
            [
                'title' => 'One-Click Quick Logout',
                'slug' => 'single-button-quick-logout',
                'description' => 'The simplest possible pattern: a single full-width red button with no confirmation step at all.',
                'storage_path' => 'logout/single-button-quick-logout',
                'customizable_vars' => [
                    '--danger' => '#ef4444',
                ],
                'tags' => [
                    'simple',
                    'single-action',
                    'no-confirmation',
                ],
            ],
            [
                'title' => 'Fade-Out Page Logout',
                'slug' => 'fade-out-logout-transition',
                'description' => 'Simulates the entire page fading to black on logout click, a common SPA transition pattern.',
                'storage_path' => 'logout/fade-out-logout-transition',
                'customizable_vars' => [
                    '--fade-color' => '#000000',
                ],
                'tags' => [
                    'fade-transition',
                    'javascript',
                    'spa-pattern',
                ],
            ],
            [
                'title' => 'Emoji Reaction Logout',
                'slug' => 'emoji-reaction-logout',
                'description' => 'A friendly logout confirmation asking the user to pick how their session went, before logging out.',
                'storage_path' => 'logout/emoji-reaction-logout',
                'customizable_vars' => [
                    '--accent' => '#f59e0b',
                ],
                'tags' => [
                    'feedback',
                    'playful',
                    'emoji',
                ],
            ],
            [
                'title' => 'Logging Out Progress Bar',
                'slug' => 'progress-bar-logout',
                'description' => 'Shows an animated progress bar filling up while \'logging out\' is simulated, then completes.',
                'storage_path' => 'logout/progress-bar-logout',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'progress-bar',
                    'javascript',
                    'loading-state',
                ],
            ],
            [
                'title' => 'Stacked Card Peek Logout',
                'slug' => 'card-stack-logout',
                'description' => 'A logout card with a subtle stacked-card illusion behind it using two offset pseudo-card layers.',
                'storage_path' => 'logout/card-stack-logout',
                'customizable_vars' => [
                    '--accent' => '#be185d',
                ],
                'tags' => [
                    'stacked-cards',
                    'playful',
                    'depth',
                ],
            ],
            [
                'title' => 'Stay Signed Out Option',
                'slug' => 'checkbox-stay-signed-out',
                'description' => 'A logout screen with a checkbox to also clear saved login info, common in shared-device contexts.',
                'storage_path' => 'logout/checkbox-stay-signed-out',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'shared-device',
                    'checkbox-option',
                    'privacy',
                ],
            ],
            [
                'title' => 'Illustration Logout Screen',
                'slug' => 'illustration-empty-logout',
                'description' => 'A logout confirmation with a large simple SVG illustration to soften the action visually.',
                'storage_path' => 'logout/illustration-empty-logout',
                'customizable_vars' => [
                    '--accent' => '#4338ca',
                ],
                'tags' => [
                    'illustration',
                    'svg',
                    'friendly',
                ],
            ],
            [
                'title' => 'Keyboard Shortcut Logout Hint',
                'slug' => 'keyboard-shortcut-logout',
                'description' => 'A logout button that also displays and listens for a keyboard shortcut (Ctrl+Shift+Q) via JS.',
                'storage_path' => 'logout/keyboard-shortcut-logout',
                'customizable_vars' => [
                    '--accent' => '#374151',
                ],
                'tags' => [
                    'keyboard-shortcut',
                    'javascript',
                    'power-user',
                ],
            ],
            [
                'title' => 'Gradient Fullscreen Logout',
                'slug' => 'gradient-fullscreen-logout',
                'description' => 'A bold full-screen gradient background with centered minimal logout confirmation text and buttons.',
                'storage_path' => 'logout/gradient-fullscreen-logout',
                'customizable_vars' => [
                    '--g1' => '#7c3aed',
                    '--g2' => '#db2777',
                ],
                'tags' => [
                    'fullscreen',
                    'gradient',
                    'bold',
                ],
            ],
            [
                'title' => 'Inline Text Confirm Logout',
                'slug' => 'inline-confirm-text-logout',
                'description' => 'An ultra-minimal pattern: clicking \'Log Out\' replaces it inline with \'Are you sure? Yes / No\' without any modal.',
                'storage_path' => 'logout/inline-confirm-text-logout',
                'customizable_vars' => [
                    '--accent' => '#1d4ed8',
                ],
                'tags' => [
                    'inline',
                    'minimal',
                    'no-modal',
                    'javascript',
                ],
            ],
            [
                'title' => 'Session Stats Logout Card',
                'slug' => 'card-with-stats-logout',
                'description' => 'A logout card that shows a quick summary of the session (time spent, designs viewed) before confirming.',
                'storage_path' => 'logout/card-with-stats-logout',
                'customizable_vars' => [
                    '--accent' => '#0891b2',
                ],
                'tags' => [
                    'stats-summary',
                    'engagement',
                    'card',
                ],
            ],
            [
                'title' => 'Toggle Switch Logout',
                'slug' => 'toggle-switch-logout',
                'description' => 'A logout pattern using an iOS-style toggle switch that must be slid to confirm, via JS.',
                'storage_path' => 'logout/toggle-switch-logout',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'toggle-switch',
                    'ios-style',
                    'javascript',
                ],
            ],
            [
                'title' => 'Hover-Reveal Logout Card',
                'slug' => 'hover-reveal-logout',
                'description' => 'A profile card where the logout button is hidden by default and slides into view only on hover.',
                'storage_path' => 'logout/hover-reveal-logout',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'hover-reveal',
                    'profile-card',
                    'hidden-action',
                ],
            ],
            [
                'title' => 'Type to Confirm Logout',
                'slug' => 'two-step-verify-logout',
                'description' => 'A higher-friction logout requiring the user to type LOGOUT to enable the confirm button, via JS input matching.',
                'storage_path' => 'logout/two-step-verify-logout',
                'customizable_vars' => [
                    '--accent' => '#b91c1c',
                ],
                'tags' => [
                    'type-to-confirm',
                    'high-friction',
                    'javascript',
                    'security',
                ],
            ],
            [
                'title' => 'Circular Countdown Logout',
                'slug' => 'circular-progress-logout',
                'description' => 'An SVG circular progress ring that depletes as a countdown to automatic logout runs, via JS stroke-dashoffset animation.',
                'storage_path' => 'logout/circular-progress-logout',
                'customizable_vars' => [
                    '--ring-color' => '#dc2626',
                ],
                'tags' => [
                    'svg',
                    'circular-progress',
                    'javascript',
                    'countdown',
                ],
            ],
            [
                'title' => 'Mobile Bottom Sheet Logout',
                'slug' => 'bottom-sheet-logout',
                'description' => 'A mobile-style bottom sheet that slides up from the bottom of the screen with logout actions.',
                'storage_path' => 'logout/bottom-sheet-logout',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'bottom-sheet',
                    'mobile-pattern',
                    'javascript',
                ],
            ],
            [
                'title' => 'Icon + Text Split Logout',
                'slug' => 'split-icon-text-logout',
                'description' => 'A clean two-column logout dialog: icon on the left, message and actions stacked on the right.',
                'storage_path' => 'logout/split-icon-text-logout',
                'customizable_vars' => [
                    '--accent' => '#334155',
                ],
                'tags' => [
                    'two-column',
                    'icon-text',
                    'lock-metaphor',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
