<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "mobile-ui-components" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class MobileUiComponentsDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'mobile-ui-components')->first();

        if (!$section) {
            $this->command?->warn("Section 'mobile-ui-components' not found — skipping MobileUiComponentsDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Mobile Bottom Tab Bar',
                'slug' => 'bottom-tab-bar',
                'description' => 'A fixed bottom navigation bar with icon+label tabs, the standard mobile app navigation pattern.',
                'storage_path' => 'mobile-ui-components/bottom-tab-bar',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'bottom-nav',
                    'tab-bar',
                    'mobile-app',
                ],
            ],
            [
                'title' => 'Pull to Refresh Indicator',
                'slug' => 'pull-to-refresh',
                'description' => 'A mobile screen with a pull-to-refresh spinner that appears at the top, simulated via JS button.',
                'storage_path' => 'mobile-ui-components/pull-to-refresh',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'pull-to-refresh',
                    'javascript',
                    'feed',
                ],
            ],
            [
                'title' => 'Mobile Action Sheet',
                'slug' => 'mobile-action-sheet',
                'description' => 'A bottom action sheet with multiple option buttons and a cancel action, the native iOS/Android pattern.',
                'storage_path' => 'mobile-ui-components/mobile-action-sheet',
                'customizable_vars' => [
                    '--danger' => '#dc2626',
                ],
                'tags' => [
                    'action-sheet',
                    'native-pattern',
                ],
            ],
            [
                'title' => 'Swipeable Card Stack',
                'slug' => 'swipeable-card-stack',
                'description' => 'A Tinder-style stack of cards that can be swiped away via JS drag tracking, revealing the next card.',
                'storage_path' => 'mobile-ui-components/swipeable-card-stack',
                'customizable_vars' => [
                    '--accent' => '#ec4899',
                ],
                'tags' => [
                    'swipe-cards',
                    'javascript',
                    'drag',
                ],
            ],
            [
                'title' => 'Mobile Segmented Control',
                'slug' => 'mobile-segmented-control',
                'description' => 'An iOS-style segmented control toggle used to switch between two views, with a sliding active indicator.',
                'storage_path' => 'mobile-ui-components/mobile-segmented-control',
                'customizable_vars' => [
                    '--accent' => '#111827',
                ],
                'tags' => [
                    'segmented-control',
                    'ios-style',
                    'javascript',
                ],
            ],
            [
                'title' => 'Mobile Floating Action Button',
                'slug' => 'mobile-fab-button',
                'description' => 'A circular floating action button fixed in the bottom-right of a mobile screen mockup.',
                'storage_path' => 'mobile-ui-components/mobile-fab-button',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'fab',
                    'floating-action',
                    'mobile',
                ],
            ],
            [
                'title' => 'Horizontal Card Carousel',
                'slug' => 'mobile-card-carousel',
                'description' => 'A horizontally scrollable card carousel, common for mobile \'featured items\' rows.',
                'storage_path' => 'mobile-ui-components/mobile-card-carousel',
                'customizable_vars' => [],
                'tags' => [
                    'carousel',
                    'horizontal-scroll',
                    'featured-items',
                ],
            ],
            [
                'title' => 'Mobile Status Bar Mockup',
                'slug' => 'mobile-status-bar-mock',
                'description' => 'A static mockup of a phone\'s top status bar (time, signal, battery) for realistic mobile mockups.',
                'storage_path' => 'mobile-ui-components/mobile-status-bar-mock',
                'customizable_vars' => [],
                'tags' => [
                    'status-bar',
                    'mockup',
                    'realistic',
                ],
            ],
            [
                'title' => 'Onboarding Slide Dots',
                'slug' => 'mobile-onboarding-dots',
                'description' => 'A mobile onboarding screen with paginated dot indicators showing which slide is active.',
                'storage_path' => 'mobile-ui-components/mobile-onboarding-dots',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'onboarding',
                    'pagination-dots',
                ],
            ],
            [
                'title' => 'Mobile Full-Screen Search Overlay',
                'slug' => 'mobile-search-overlay',
                'description' => 'Tapping a search icon opens a full-screen search overlay with a back arrow, common on mobile apps.',
                'storage_path' => 'mobile-ui-components/mobile-search-overlay',
                'customizable_vars' => [],
                'tags' => [
                    'search-overlay',
                    'full-screen',
                    'javascript',
                ],
            ],
            [
                'title' => 'Mobile Settings Toggle Rows',
                'slug' => 'mobile-toggle-row-list',
                'description' => 'A mobile-styled list of settings rows each with a label and a right-aligned toggle switch.',
                'storage_path' => 'mobile-ui-components/mobile-toggle-row-list',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'settings-rows',
                    'toggle-list',
                    'mobile',
                ],
            ],
            [
                'title' => 'Numeric PIN Keypad',
                'slug' => 'mobile-otp-keypad',
                'description' => 'A custom on-screen numeric keypad for entering a PIN code, common in banking apps.',
                'storage_path' => 'mobile-ui-components/mobile-otp-keypad',
                'customizable_vars' => [
                    '--accent' => '#111827',
                ],
                'tags' => [
                    'pin-keypad',
                    'numeric',
                    'banking-app',
                ],
            ],
            [
                'title' => 'Swipe-to-Delete List Item',
                'slug' => 'mobile-card-swipe-actions',
                'description' => 'A list item that reveals a delete button when swiped left, simulated via JS click toggle.',
                'storage_path' => 'mobile-ui-components/mobile-card-swipe-actions',
                'customizable_vars' => [
                    '--danger' => '#dc2626',
                ],
                'tags' => [
                    'swipe-to-delete',
                    'javascript',
                    'list-item',
                ],
            ],
            [
                'title' => 'Mobile App Header Bar',
                'slug' => 'mobile-app-header',
                'description' => 'A standard mobile screen header with back arrow, centered title, and a right-side action icon.',
                'storage_path' => 'mobile-ui-components/mobile-app-header',
                'customizable_vars' => [],
                'tags' => [
                    'app-header',
                    'navigation',
                    'mobile-screen',
                ],
            ],
            [
                'title' => 'Mobile Bottom Toast',
                'slug' => 'mobile-toast-bottom',
                'description' => 'A small toast that appears just above the bottom edge of a mobile screen, auto-dismissing after a delay.',
                'storage_path' => 'mobile-ui-components/mobile-toast-bottom',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'toast',
                    'bottom-aligned',
                    'javascript',
                ],
            ],
            [
                'title' => 'Mobile Horizontal Filter Chips',
                'slug' => 'mobile-chip-filter-row',
                'description' => 'A horizontally scrollable row of filter chip buttons at the top of a mobile list screen.',
                'storage_path' => 'mobile-ui-components/mobile-chip-filter-row',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'chip-filter',
                    'horizontal-scroll',
                    'mobile',
                ],
            ],
            [
                'title' => 'Mobile App Store Rating Prompt',
                'slug' => 'mobile-rating-bottom-sheet',
                'description' => 'A bottom-sheet style rating prompt mimicking app-store review requests, with star selection.',
                'storage_path' => 'mobile-ui-components/mobile-rating-bottom-sheet',
                'customizable_vars' => [
                    '--star-color' => '#f59e0b',
                ],
                'tags' => [
                    'rating-prompt',
                    'bottom-sheet',
                    'app-store-style',
                ],
            ],
            [
                'title' => 'Infinite Scroll Loading Footer',
                'slug' => 'mobile-load-more-spinner',
                'description' => 'A list footer showing a small loading spinner that simulates loading more items as you scroll.',
                'storage_path' => 'mobile-ui-components/mobile-load-more-spinner',
                'customizable_vars' => [
                    '--accent' => '#0ea5e9',
                ],
                'tags' => [
                    'infinite-scroll',
                    'loading-footer',
                ],
            ],
            [
                'title' => 'Expandable Mobile Card',
                'slug' => 'mobile-toggle-card-expand',
                'description' => 'A mobile list card that expands inline to reveal more details when tapped, via JS height toggle.',
                'storage_path' => 'mobile-ui-components/mobile-toggle-card-expand',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'expandable-card',
                    'javascript',
                    'order-details',
                ],
            ],
            [
                'title' => 'Mobile Onboarding Progress Bar',
                'slug' => 'mobile-progress-onboard-bar',
                'description' => 'A thin progress bar at the top of an onboarding flow showing how many steps remain.',
                'storage_path' => 'mobile-ui-components/mobile-progress-onboard-bar',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'onboarding-progress',
                    'top-bar',
                ],
            ],
            [
                'title' => 'Chat Quick Reply Chips',
                'slug' => 'mobile-quick-reply-chips',
                'description' => 'A messaging app pattern showing tappable quick-reply suggestion chips above the keyboard area.',
                'storage_path' => 'mobile-ui-components/mobile-quick-reply-chips',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'quick-reply',
                    'chat-app',
                    'chips',
                ],
            ],
            [
                'title' => 'Mobile Empty Cart State',
                'slug' => 'mobile-empty-cart-state',
                'description' => 'A friendly empty-state screen for an empty shopping cart, with icon and CTA button.',
                'storage_path' => 'mobile-ui-components/mobile-empty-cart-state',
                'customizable_vars' => [
                    '--accent' => '#ea580c',
                ],
                'tags' => [
                    'empty-state',
                    'ecommerce',
                    'mobile',
                ],
            ],
            [
                'title' => 'Mobile Permission Request Screen',
                'slug' => 'mobile-permission-prompt',
                'description' => 'A full mobile screen asking for camera/photo permission, with icon and allow/deny buttons.',
                'storage_path' => 'mobile-ui-components/mobile-permission-prompt',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'permission-prompt',
                    'camera-access',
                ],
            ],
            [
                'title' => 'Mobile Header with Search Bar',
                'slug' => 'mobile-rounded-search-header',
                'description' => 'A mobile screen header that contains an embedded search bar directly inside it.',
                'storage_path' => 'mobile-ui-components/mobile-rounded-search-header',
                'customizable_vars' => [
                    '--accent' => '#4f46e5',
                ],
                'tags' => [
                    'search-header',
                    'embedded-search',
                ],
            ],
            [
                'title' => 'Mobile Card with Heart Toggle',
                'slug' => 'mobile-toggle-favorite-heart',
                'description' => 'A product card mockup with a heart icon in the corner that fills in when tapped, via JS.',
                'storage_path' => 'mobile-ui-components/mobile-toggle-favorite-heart',
                'customizable_vars' => [
                    '--heart-color' => '#f43f5e',
                ],
                'tags' => [
                    'heart-toggle',
                    'javascript',
                    'product-card',
                ],
            ],
            [
                'title' => 'Mobile Hamburger Drawer Menu',
                'slug' => 'mobile-drawer-menu',
                'description' => 'A hamburger icon that opens a slide-in side drawer menu over the mobile screen, via JS.',
                'storage_path' => 'mobile-ui-components/mobile-drawer-menu',
                'customizable_vars' => [
                    '--accent' => '#111827',
                ],
                'tags' => [
                    'hamburger-menu',
                    'drawer',
                    'javascript',
                ],
            ],
            [
                'title' => 'Mobile Image Tap-to-Zoom',
                'slug' => 'mobile-image-zoom-pinch',
                'description' => 'An image that scales up on tap, simulating a zoom interaction common on mobile galleries, via JS toggle.',
                'storage_path' => 'mobile-ui-components/mobile-image-zoom-pinch',
                'customizable_vars' => [],
                'tags' => [
                    'tap-to-zoom',
                    'javascript',
                    'gallery',
                ],
            ],
            [
                'title' => 'Mobile Sticky Add-to-Cart Bar',
                'slug' => 'mobile-bottom-cart-bar',
                'description' => 'A bar fixed at the bottom of a product screen showing price and an always-visible add-to-cart button.',
                'storage_path' => 'mobile-ui-components/mobile-bottom-cart-bar',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'sticky-bar',
                    'ecommerce',
                    'bottom-fixed',
                ],
            ],
            [
                'title' => 'Mobile Tab Swipe Progress Dots',
                'slug' => 'mobile-tab-swipe-indicator',
                'description' => 'Small progress dots beneath swipeable tab content indicating which page is currently visible.',
                'storage_path' => 'mobile-ui-components/mobile-tab-swipe-indicator',
                'customizable_vars' => [
                    '--accent' => '#0891b2',
                ],
                'tags' => [
                    'swipe-indicator',
                    'pagination-dots',
                    'tabs',
                ],
            ],
            [
                'title' => 'Mobile Voice Search FAB',
                'slug' => 'mobile-voice-search-button',
                'description' => 'A floating circular voice-search button that pulses while \'listening\', simulated via JS toggle.',
                'storage_path' => 'mobile-ui-components/mobile-voice-search-button',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'voice-search',
                    'fab',
                    'javascript',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
