<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "modals" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class ModalsDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'modals')->first();

        if (!$section) {
            $this->command?->warn("Section 'modals' not found — skipping ModalsDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Basic Confirm Modal',
                'slug' => 'basic-confirm-modal',
                'description' => 'A standard modal dialog with a title, message, and two action buttons over a dark backdrop.',
                'storage_path' => 'modals/basic-confirm-modal',
                'customizable_vars' => [
                    '--danger' => '#dc2626',
                ],
                'tags' => [
                    'confirm',
                    'basic',
                    'javascript',
                ],
            ],
            [
                'title' => 'Image Lightbox Modal',
                'slug' => 'centered-image-modal',
                'description' => 'A clickable thumbnail that opens a centered full-size image modal with a close button.',
                'storage_path' => 'modals/centered-image-modal',
                'customizable_vars' => [],
                'tags' => [
                    'lightbox',
                    'image-modal',
                    'javascript',
                ],
            ],
            [
                'title' => 'Slide-Up Mobile Modal',
                'slug' => 'slide-up-mobile-modal',
                'description' => 'A modal that slides up from the bottom of the screen, common in mobile-first interfaces.',
                'storage_path' => 'modals/slide-up-mobile-modal',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'mobile',
                    'slide-up',
                    'bottom-sheet',
                ],
            ],
            [
                'title' => 'Video Embed Modal',
                'slug' => 'video-embed-modal',
                'description' => 'A modal that opens to show a centered video player placeholder, common for \'watch demo\' buttons.',
                'storage_path' => 'modals/video-embed-modal',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'video',
                    'demo',
                    'javascript',
                ],
            ],
            [
                'title' => 'Newsletter Signup Modal',
                'slug' => 'form-modal-newsletter',
                'description' => 'A modal containing a small signup form, the classic \'subscribe\' popup pattern.',
                'storage_path' => 'modals/form-modal-newsletter',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'newsletter',
                    'form-modal',
                    'javascript',
                ],
            ],
            [
                'title' => 'Scale-In Animated Modal',
                'slug' => 'scale-in-modal',
                'description' => 'A modal that animates in with a scale + fade effect rather than appearing instantly.',
                'storage_path' => 'modals/scale-in-modal',
                'customizable_vars' => [
                    '--accent' => '#0ea5e9',
                ],
                'tags' => [
                    'scale-animation',
                    'entrance',
                    'javascript',
                ],
            ],
            [
                'title' => 'Full-Screen Takeover Modal',
                'slug' => 'full-screen-takeover-modal',
                'description' => 'A modal that covers the entire viewport rather than floating as a small box, used for major actions.',
                'storage_path' => 'modals/full-screen-takeover-modal',
                'customizable_vars' => [
                    '--bg-color' => '#4f46e5',
                ],
                'tags' => [
                    'fullscreen',
                    'onboarding',
                    'takeover',
                ],
            ],
            [
                'title' => 'Image Gallery Modal with Navigation',
                'slug' => 'multi-image-gallery-modal',
                'description' => 'A modal showing one image at a time with Previous/Next buttons to browse a small gallery, via JS index tracking.',
                'storage_path' => 'modals/multi-image-gallery-modal',
                'customizable_vars' => [
                    '--accent' => '#f59e0b',
                ],
                'tags' => [
                    'gallery',
                    'navigation',
                    'javascript',
                ],
            ],
            [
                'title' => 'Warning Icon Modal',
                'slug' => 'warning-icon-modal',
                'description' => 'A modal centered around a large warning icon for high-stakes confirmations like account deletion.',
                'storage_path' => 'modals/warning-icon-modal',
                'customizable_vars' => [
                    '--danger' => '#dc2626',
                ],
                'tags' => [
                    'warning',
                    'high-stakes',
                    'javascript',
                ],
            ],
            [
                'title' => 'Tabbed Content Modal',
                'slug' => 'modal-with-tabs',
                'description' => 'A modal containing internal tabs to switch between different content panes, via JS tab switching.',
                'storage_path' => 'modals/modal-with-tabs',
                'customizable_vars' => [
                    '--accent' => '#0891b2',
                ],
                'tags' => [
                    'tabs',
                    'settings',
                    'javascript',
                ],
            ],
            [
                'title' => 'Drag Down to Close Modal',
                'slug' => 'drag-to-close-modal',
                'description' => 'A mobile-style modal that can be dragged downward to dismiss, tracking touch/mouse movement via JS.',
                'storage_path' => 'modals/drag-to-close-modal',
                'customizable_vars' => [
                    '--accent' => '#334155',
                ],
                'tags' => [
                    'drag-to-dismiss',
                    'javascript',
                    'mobile-pattern',
                ],
            ],
            [
                'title' => 'Success Confirmation Modal',
                'slug' => 'success-checkmark-modal',
                'description' => 'A modal showing an animated checkmark to confirm a successful action, like a completed purchase.',
                'storage_path' => 'modals/success-checkmark-modal',
                'customizable_vars' => [],
                'tags' => [
                    'success',
                    'checkmark',
                    'confirmation',
                ],
            ],
            [
                'title' => 'Cookie Consent Modal',
                'slug' => 'cookie-consent-modal',
                'description' => 'A bottom-fixed banner-style modal requesting cookie consent, with accept/customize options.',
                'storage_path' => 'modals/cookie-consent-modal',
                'customizable_vars' => [
                    '--accent' => '#111827',
                ],
                'tags' => [
                    'cookie-consent',
                    'banner',
                    'gdpr-style',
                ],
            ],
            [
                'title' => 'Keyboard Shortcuts Help Modal',
                'slug' => 'keyboard-shortcuts-modal',
                'description' => 'A modal listing keyboard shortcuts in a clean two-column key/description layout.',
                'storage_path' => 'modals/keyboard-shortcuts-modal',
                'customizable_vars' => [
                    '--accent' => '#1e293b',
                ],
                'tags' => [
                    'keyboard-shortcuts',
                    'help',
                    'reference',
                ],
            ],
            [
                'title' => 'Upgrade Plan Promo Modal',
                'slug' => 'upgrade-plan-modal',
                'description' => 'A promotional modal nudging the user toward a paid plan, with a feature list and gradient CTA button.',
                'storage_path' => 'modals/upgrade-plan-modal',
                'customizable_vars' => [
                    '--g1' => '#6366f1',
                    '--g2' => '#ec4899',
                ],
                'tags' => [
                    'upsell',
                    'promo',
                    'gradient-cta',
                ],
            ],
            [
                'title' => 'Share Link Modal',
                'slug' => 'share-link-modal',
                'description' => 'A modal with a copyable link field and social share icons, common for sharing content.',
                'storage_path' => 'modals/share-link-modal',
                'customizable_vars' => [
                    '--accent' => '#0ea5e9',
                ],
                'tags' => [
                    'share',
                    'copy-link',
                    'javascript',
                ],
            ],
            [
                'title' => 'Step Progress Modal',
                'slug' => 'step-progress-modal',
                'description' => 'A modal with a numbered step progress tracker at the top, useful for setup wizards.',
                'storage_path' => 'modals/step-progress-modal',
                'customizable_vars' => [
                    '--accent' => '#4338ca',
                ],
                'tags' => [
                    'wizard',
                    'step-progress',
                    'setup',
                ],
            ],
            [
                'title' => 'Blurred Background Modal',
                'slug' => 'blurred-bg-modal',
                'description' => 'A modal where the page content behind it gets a CSS blur filter applied, drawing strong focus to the modal.',
                'storage_path' => 'modals/blurred-bg-modal',
                'customizable_vars' => [
                    '--accent' => '#be123c',
                ],
                'tags' => [
                    'blur-backdrop',
                    'focus',
                    'javascript',
                ],
            ],
            [
                'title' => 'Side Drawer Modal',
                'slug' => 'side-panel-drawer-modal',
                'description' => 'A modal that slides in from the right edge like a drawer, rather than appearing centered.',
                'storage_path' => 'modals/side-panel-drawer-modal',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'drawer',
                    'side-panel',
                    'cart',
                ],
            ],
            [
                'title' => 'Post-Action Rating Modal',
                'slug' => 'rating-feedback-modal',
                'description' => 'A modal asking the user to rate their experience right after completing an action, with star input.',
                'storage_path' => 'modals/rating-feedback-modal',
                'customizable_vars' => [
                    '--star-color' => '#f59e0b',
                ],
                'tags' => [
                    'rating',
                    'post-action',
                    'javascript',
                ],
            ],
            [
                'title' => 'Two-Choice Decision Modal',
                'slug' => 'two-choice-decision-modal',
                'description' => 'A modal presenting two large, equally weighted choice cards rather than text buttons.',
                'storage_path' => 'modals/two-choice-decision-modal',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'decision',
                    'choice-cards',
                    'onboarding',
                ],
            ],
            [
                'title' => 'Loading State Modal',
                'slug' => 'loading-state-modal',
                'description' => 'A modal that first shows a spinner while \'processing\', then automatically swaps to a result message via JS timeout.',
                'storage_path' => 'modals/loading-state-modal',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'loading-state',
                    'javascript',
                    'payment',
                ],
            ],
            [
                'title' => 'Nested Confirmation Modal',
                'slug' => 'nested-confirm-modal',
                'description' => 'Clicking an action inside one modal opens a second confirmation modal on top of it, via JS stacking.',
                'storage_path' => 'modals/nested-confirm-modal',
                'customizable_vars' => [
                    '--danger' => '#dc2626',
                ],
                'tags' => [
                    'nested-modal',
                    'stacked',
                    'javascript',
                ],
            ],
            [
                'title' => 'Limited Time Offer Modal',
                'slug' => 'countdown-promo-modal',
                'description' => 'A promotional modal with a live countdown timer to create urgency, common in marketing popups.',
                'storage_path' => 'modals/countdown-promo-modal',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'countdown',
                    'promo',
                    'urgency',
                ],
            ],
            [
                'title' => 'Avatar Picker Modal',
                'slug' => 'avatar-picker-modal',
                'description' => 'A modal showing a grid of selectable avatar emoji options, highlighting the chosen one via JS.',
                'storage_path' => 'modals/avatar-picker-modal',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'avatar-picker',
                    'grid-select',
                    'javascript',
                ],
            ],
            [
                'title' => 'Scroll-to-Accept Terms Modal',
                'slug' => 'terms-scroll-confirm-modal',
                'description' => 'A terms-of-service modal where the Accept button only enables after the user scrolls to the bottom, via JS scroll detection.',
                'storage_path' => 'modals/terms-scroll-confirm-modal',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'terms-of-service',
                    'scroll-detection',
                    'javascript',
                ],
            ],
            [
                'title' => 'Emoji Reaction Picker Modal',
                'slug' => 'emoji-reaction-picker-modal',
                'description' => 'A small popover-style modal letting the user pick a quick emoji reaction, closing automatically on selection.',
                'storage_path' => 'modals/emoji-reaction-picker-modal',
                'customizable_vars' => [],
                'tags' => [
                    'emoji-picker',
                    'popover',
                    'reactions',
                ],
            ],
            [
                'title' => 'Quick Survey Prompt Modal',
                'slug' => 'survey-prompt-modal',
                'description' => 'A small modal that interrupts gently to ask a single survey question, with skip and answer options.',
                'storage_path' => 'modals/survey-prompt-modal',
                'customizable_vars' => [
                    '--accent' => '#0284c7',
                ],
                'tags' => [
                    'survey',
                    'micro-feedback',
                    'javascript',
                ],
            ],
            [
                'title' => 'Zoom-In Product Quick View Modal',
                'slug' => 'zoom-in-product-modal',
                'description' => 'A modal that pops up with a zoom-in animation showing product quick-view details, common in e-commerce.',
                'storage_path' => 'modals/zoom-in-product-modal',
                'customizable_vars' => [
                    '--accent' => '#92400e',
                ],
                'tags' => [
                    'quick-view',
                    'ecommerce',
                    'zoom-animation',
                ],
            ],
            [
                'title' => 'Voice Message Modal',
                'slug' => 'audio-message-modal',
                'description' => 'A modal that simulates recording a voice message with a pulsing mic icon and timer, via JS.',
                'storage_path' => 'modals/audio-message-modal',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'voice-recording',
                    'javascript',
                    'chat-feature',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
