<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "notifications-toasts" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class NotificationsToastsDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'notifications-toasts')->first();

        if (!$section) {
            $this->command?->warn("Section 'notifications-toasts' not found — skipping NotificationsToastsDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Basic Success Toast',
                'slug' => 'success-toast-basic',
                'description' => 'A simple green success toast notification with a checkmark icon, triggered by a button.',
                'storage_path' => 'notifications-toasts/success-toast-basic',
                'customizable_vars' => [
                    '--success-color' => '#16a34a',
                ],
                'tags' => [
                    'success',
                    'basic',
                    'javascript',
                ],
            ],
            [
                'title' => 'Error Toast with Icon',
                'slug' => 'error-toast-with-icon',
                'description' => 'A red error toast with a warning icon and dismiss button.',
                'storage_path' => 'notifications-toasts/error-toast-with-icon',
                'customizable_vars' => [
                    '--error-color' => '#dc2626',
                ],
                'tags' => [
                    'error',
                    'dismissible',
                    'javascript',
                ],
            ],
            [
                'title' => 'Top Slide-Down Notification',
                'slug' => 'top-slide-notification',
                'description' => 'A notification bar that slides down from the very top of the viewport.',
                'storage_path' => 'notifications-toasts/top-slide-notification',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'top-bar',
                    'slide-down',
                    'javascript',
                ],
            ],
            [
                'title' => 'Stacked Multiple Toasts',
                'slug' => 'stacked-multi-toast',
                'description' => 'Clicking multiple times stacks several toasts vertically, each auto-dismissing independently.',
                'storage_path' => 'notifications-toasts/stacked-multi-toast',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'stacked',
                    'multiple',
                    'javascript',
                ],
            ],
            [
                'title' => 'Toast with Auto-Dismiss Progress Bar',
                'slug' => 'progress-bar-toast',
                'description' => 'A toast notification with a thin progress bar at the bottom showing time remaining before auto-dismiss.',
                'storage_path' => 'notifications-toasts/progress-bar-toast',
                'customizable_vars' => [
                    '--accent' => '#0ea5e9',
                ],
                'tags' => [
                    'progress-bar',
                    'auto-dismiss',
                    'javascript',
                ],
            ],
            [
                'title' => 'Toast with Undo Action',
                'slug' => 'action-button-toast',
                'description' => 'A toast that includes an inline action button (Undo), the classic \'item deleted\' pattern.',
                'storage_path' => 'notifications-toasts/action-button-toast',
                'customizable_vars' => [
                    '--accent' => '#1f2937',
                ],
                'tags' => [
                    'undo-action',
                    'javascript',
                    'delete-pattern',
                ],
            ],
            [
                'title' => 'Notification Bell with Dropdown List',
                'slug' => 'notification-bell-dropdown',
                'description' => 'A bell icon that opens a dropdown list of recent notifications when clicked, via JS.',
                'storage_path' => 'notifications-toasts/notification-bell-dropdown',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'dropdown',
                    'bell-icon',
                    'javascript',
                ],
            ],
            [
                'title' => 'Pulsing Warning Toast',
                'slug' => 'warning-toast-pulse',
                'description' => 'A warning toast that pulses gently to draw attention without being too aggressive.',
                'storage_path' => 'notifications-toasts/warning-toast-pulse',
                'customizable_vars' => [
                    '--warn-color' => '#f59e0b',
                ],
                'tags' => [
                    'warning',
                    'pulse-animation',
                    'javascript',
                ],
            ],
            [
                'title' => 'Info Toast with Action Link',
                'slug' => 'info-toast-with-link',
                'description' => 'An informational toast containing an inline \'Learn more\' link alongside the message.',
                'storage_path' => 'notifications-toasts/info-toast-with-link',
                'customizable_vars' => [
                    '--info-color' => '#0891b2',
                ],
                'tags' => [
                    'info',
                    'action-link',
                    'javascript',
                ],
            ],
            [
                'title' => 'Centered Modal-Style Notice',
                'slug' => 'centered-modal-style-notification',
                'description' => 'A notification that appears centered on screen like a small modal, rather than in a corner.',
                'storage_path' => 'notifications-toasts/centered-modal-style-notification',
                'customizable_vars' => [
                    '--accent' => '#ec4899',
                ],
                'tags' => [
                    'centered',
                    'celebratory',
                    'javascript',
                ],
            ],
            [
                'title' => 'Toast with User Avatar',
                'slug' => 'toast-with-avatar',
                'description' => 'A notification toast showing a small avatar alongside the message, useful for social/mention alerts.',
                'storage_path' => 'notifications-toasts/toast-with-avatar',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'avatar',
                    'social',
                    'mention',
                ],
            ],
            [
                'title' => 'Glassmorphic Frosted Toast',
                'slug' => 'glassmorphic-toast',
                'description' => 'A toast notification with a frosted-glass blur effect over a colorful background.',
                'storage_path' => 'notifications-toasts/glassmorphic-toast',
                'customizable_vars' => [],
                'tags' => [
                    'glassmorphism',
                    'frosted',
                    'javascript',
                ],
            ],
            [
                'title' => 'Loading Then Success Toast',
                'slug' => 'loading-to-success-toast',
                'description' => 'A toast that first shows a spinner with \'Saving...\' then morphs into a success checkmark message.',
                'storage_path' => 'notifications-toasts/loading-to-success-toast',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'loading-state',
                    'morph',
                    'javascript',
                ],
            ],
            [
                'title' => 'Toast with Position Selector Demo',
                'slug' => 'toast-position-selector',
                'description' => 'A demo where buttons let you trigger toasts in different screen corners, via JS positioning.',
                'storage_path' => 'notifications-toasts/toast-position-selector',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'position-demo',
                    'javascript',
                    'configurable',
                ],
            ],
            [
                'title' => 'Toast with Rotating Icon Entry',
                'slug' => 'toast-with-icon-rotation',
                'description' => 'A toast whose icon spins into place on entry before settling, a playful entrance detail.',
                'storage_path' => 'notifications-toasts/toast-with-icon-rotation',
                'customizable_vars' => [
                    '--accent' => '#d97706',
                ],
                'tags' => [
                    'icon-rotation',
                    'playful',
                    'javascript',
                ],
            ],
            [
                'title' => 'Toast with Countdown to Auto-Action',
                'slug' => 'toast-with-countdown-action',
                'description' => 'A toast showing a live countdown before an action automatically proceeds, with a cancel option.',
                'storage_path' => 'notifications-toasts/toast-with-countdown-action',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'countdown',
                    'cancel-action',
                    'javascript',
                ],
            ],
            [
                'title' => 'Toast Grouped Summary',
                'slug' => 'toast-grouped-by-type',
                'description' => 'Multiple rapid toasts collapse into a single summary toast like \'3 new notifications\', via JS counting.',
                'storage_path' => 'notifications-toasts/toast-grouped-by-type',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'grouped',
                    'summary',
                    'javascript',
                ],
            ],
            [
                'title' => 'Toast with Thumbnail Preview',
                'slug' => 'toast-with-image-preview',
                'description' => 'A toast showing a small image thumbnail next to its message, useful for upload confirmations.',
                'storage_path' => 'notifications-toasts/toast-with-image-preview',
                'customizable_vars' => [
                    '--accent' => '#475569',
                ],
                'tags' => [
                    'thumbnail',
                    'upload-confirmation',
                    'javascript',
                ],
            ],
            [
                'title' => 'Offline/Network Status Toast',
                'slug' => 'offline-network-toast',
                'description' => 'A persistent toast that appears when network connectivity is lost, simulated via a toggle button.',
                'storage_path' => 'notifications-toasts/offline-network-toast',
                'customizable_vars' => [
                    '--accent' => '#92400e',
                ],
                'tags' => [
                    'offline-status',
                    'persistent',
                    'javascript',
                ],
            ],
            [
                'title' => 'Dark Mode Toast Notification',
                'slug' => 'toast-dark-mode-style',
                'description' => 'A toast styled for dark-themed applications with a subtle border instead of high-contrast color.',
                'storage_path' => 'notifications-toasts/toast-dark-mode-style',
                'customizable_vars' => [
                    '--accent' => '#38bdf8',
                ],
                'tags' => [
                    'dark-mode',
                    'javascript',
                ],
            ],
            [
                'title' => 'Swipe to Dismiss Toast',
                'slug' => 'toast-swipe-to-dismiss',
                'description' => 'A toast that can be dragged horizontally to dismiss, simulating mobile swipe-away gestures via JS.',
                'storage_path' => 'notifications-toasts/toast-swipe-to-dismiss',
                'customizable_vars' => [
                    '--accent' => '#0d9488',
                ],
                'tags' => [
                    'swipe-dismiss',
                    'javascript',
                    'drag',
                ],
            ],
            [
                'title' => 'Toast Asking for Quick Rating',
                'slug' => 'toast-with-rating-prompt',
                'description' => 'A toast notification that asks the user to rate a just-completed action with a 1-5 star inline picker.',
                'storage_path' => 'notifications-toasts/toast-with-rating-prompt',
                'customizable_vars' => [
                    '--accent' => '#f59e0b',
                ],
                'tags' => [
                    'rating-prompt',
                    'inline-feedback',
                    'javascript',
                ],
            ],
            [
                'title' => 'Toast with Mute Option',
                'slug' => 'toast-with-sound-toggle',
                'description' => 'A notification toast that includes a small speaker icon toggle to mute future sound alerts, via JS.',
                'storage_path' => 'notifications-toasts/toast-with-sound-toggle',
                'customizable_vars' => [
                    '--accent' => '#4338ca',
                ],
                'tags' => [
                    'mute-toggle',
                    'sound',
                    'javascript',
                ],
            ],
            [
                'title' => 'Achievement Unlocked Toast',
                'slug' => 'achievement-unlock-toast',
                'description' => 'A celebratory gold-themed toast with a trophy icon for gamified achievement unlocks.',
                'storage_path' => 'notifications-toasts/achievement-unlock-toast',
                'customizable_vars' => [
                    '--gold' => '#d97706',
                ],
                'tags' => [
                    'achievement',
                    'gamification',
                    'javascript',
                ],
            ],
            [
                'title' => 'Permission Request Toast',
                'slug' => 'toast-permission-request',
                'description' => 'A toast asking permission for a browser feature (notifications) with Allow/Block buttons.',
                'storage_path' => 'notifications-toasts/toast-permission-request',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'permission-request',
                    'javascript',
                    'browser-style',
                ],
            ],
            [
                'title' => 'Expandable Detail Toast',
                'slug' => 'toast-with-expand-details',
                'description' => 'A toast that can be clicked to expand and reveal additional details, via JS height toggle.',
                'storage_path' => 'notifications-toasts/toast-with-expand-details',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'expandable',
                    'build-status',
                    'javascript',
                ],
            ],
            [
                'title' => 'Quick Emoji Reaction Toast',
                'slug' => 'toast-with-emoji-reaction',
                'description' => 'A lightweight toast where the user can tap an emoji to react, replacing the toast text on selection.',
                'storage_path' => 'notifications-toasts/toast-with-emoji-reaction',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'emoji-reaction',
                    'javascript',
                    'interactive',
                ],
            ],
            [
                'title' => 'Error Toast with Retry Button',
                'slug' => 'toast-error-with-retry',
                'description' => 'An error toast that includes a \'Retry\' button to re-attempt a failed action, via JS.',
                'storage_path' => 'notifications-toasts/toast-error-with-retry',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'retry-action',
                    'error-recovery',
                    'javascript',
                ],
            ],
            [
                'title' => 'Toast with Two Action Buttons',
                'slug' => 'toast-with-multiple-actions',
                'description' => 'A toast offering two distinct choices (Accept/Decline) rather than a single dismiss, for invite-style notifications.',
                'storage_path' => 'notifications-toasts/toast-with-multiple-actions',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'two-actions',
                    'invite',
                    'javascript',
                ],
            ],
            [
                'title' => 'Minimal Text-Only Toast',
                'slug' => 'toast-minimal-text-only',
                'description' => 'The simplest possible toast: plain text on a subtle background, no icon, no border, barely-there design.',
                'storage_path' => 'notifications-toasts/toast-minimal-text-only',
                'customizable_vars' => [],
                'tags' => [
                    'minimal',
                    'text-only',
                    'javascript',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
