<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "popups" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class PopupsDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'popups')->first();

        if (!$section) {
            $this->command?->warn("Section 'popups' not found — skipping PopupsDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Basic Newsletter Signup Popup',
                'slug' => 'newsletter-popup-basic',
                'description' => 'A classic centered popup asking for email signup, with a close button.',
                'storage_path' => 'popups/newsletter-popup-basic',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'newsletter',
                    'basic',
                    'javascript',
                ],
            ],
            [
                'title' => 'Exit Intent Discount Popup',
                'slug' => 'exit-intent-popup',
                'description' => 'A popup that simulates triggering when the user is about to leave, offering a last-chance discount.',
                'storage_path' => 'popups/exit-intent-popup',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'exit-intent',
                    'discount',
                    'javascript',
                ],
            ],
            [
                'title' => 'First Visit Welcome Popup',
                'slug' => 'welcome-popup-firstvisit',
                'description' => 'A friendly welcome popup that would normally trigger only on a user\'s first visit.',
                'storage_path' => 'popups/welcome-popup-firstvisit',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'welcome',
                    'first-visit',
                    'javascript',
                ],
            ],
            [
                'title' => 'Cookie Consent Bottom Popup',
                'slug' => 'cookie-consent-popup',
                'description' => 'A bottom-fixed popup requesting cookie consent with accept/decline/customize options.',
                'storage_path' => 'popups/cookie-consent-popup',
                'customizable_vars' => [
                    '--accent' => '#111827',
                ],
                'tags' => [
                    'cookie-consent',
                    'gdpr',
                    'javascript',
                ],
            ],
            [
                'title' => 'Video Lightbox Popup',
                'slug' => 'video-popup-lightbox',
                'description' => 'Clicking a play button opens a centered popup with a video player area and close button.',
                'storage_path' => 'popups/video-popup-lightbox',
                'customizable_vars' => [
                    '--accent' => '#ef4444',
                ],
                'tags' => [
                    'video-lightbox',
                    'javascript',
                ],
            ],
            [
                'title' => 'Spin-to-Win Discount Wheel Popup',
                'slug' => 'spin-to-win-popup',
                'description' => 'A playful gamified popup with a spinning wheel graphic enticing the user to engage for a discount.',
                'storage_path' => 'popups/spin-to-win-popup',
                'customizable_vars' => [
                    '--accent' => '#f59e0b',
                ],
                'tags' => [
                    'gamified',
                    'spin-wheel',
                    'javascript',
                ],
            ],
            [
                'title' => 'Quick Survey Feedback Popup',
                'slug' => 'survey-feedback-popup',
                'description' => 'A popup asking a single survey question with rating options, common for site-wide feedback collection.',
                'storage_path' => 'popups/survey-feedback-popup',
                'customizable_vars' => [
                    '--accent' => '#0891b2',
                ],
                'tags' => [
                    'survey',
                    'feedback',
                    'javascript',
                ],
            ],
            [
                'title' => 'Age Verification Gate Popup',
                'slug' => 'age-verification-popup',
                'description' => 'A popup requiring the user to confirm they meet an age requirement before entering the site.',
                'storage_path' => 'popups/age-verification-popup',
                'customizable_vars' => [
                    '--accent' => '#1f2937',
                ],
                'tags' => [
                    'age-verification',
                    'gate',
                    'javascript',
                ],
            ],
            [
                'title' => 'Mobile App Download Banner Popup',
                'slug' => 'app-download-popup',
                'description' => 'A popup prompting mobile visitors to download the native app instead of using the website.',
                'storage_path' => 'popups/app-download-popup',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'app-download',
                    'smart-banner',
                    'javascript',
                ],
            ],
            [
                'title' => 'Flash Sale Countdown Popup',
                'slug' => 'countdown-sale-popup',
                'description' => 'A popup with a live countdown timer to a sale\'s end, building urgency for the offer.',
                'storage_path' => 'popups/countdown-sale-popup',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'countdown',
                    'flash-sale',
                    'javascript',
                ],
            ],
            [
                'title' => 'Image Gallery Lightbox Popup',
                'slug' => 'image-gallery-lightbox-popup',
                'description' => 'Clicking a thumbnail opens a full-size image popup with prev/next navigation arrows.',
                'storage_path' => 'popups/image-gallery-lightbox-popup',
                'customizable_vars' => [
                    '--accent' => '#f59e0b',
                ],
                'tags' => [
                    'gallery-lightbox',
                    'navigation',
                    'javascript',
                ],
            ],
            [
                'title' => 'Referral Program Share Popup',
                'slug' => 'referral-share-popup',
                'description' => 'A popup encouraging users to share a referral link for a reward, with social share buttons.',
                'storage_path' => 'popups/referral-share-popup',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'referral',
                    'share',
                    'javascript',
                ],
            ],
            [
                'title' => 'Session Timeout Warning Popup',
                'slug' => 'session-timeout-popup',
                'description' => 'A popup that warns the user their session is about to expire, with options to continue or log out.',
                'storage_path' => 'popups/session-timeout-popup',
                'customizable_vars' => [
                    '--accent' => '#d97706',
                ],
                'tags' => [
                    'session-timeout',
                    'security',
                    'javascript',
                ],
            ],
            [
                'title' => 'Product Quick View Popup',
                'slug' => 'product-quick-view-popup',
                'description' => 'A popup showing product details and add-to-cart action without leaving the listing page.',
                'storage_path' => 'popups/product-quick-view-popup',
                'customizable_vars' => [
                    '--accent' => '#92400e',
                ],
                'tags' => [
                    'quick-view',
                    'ecommerce',
                    'javascript',
                ],
            ],
            [
                'title' => 'Loyalty Points Earned Popup',
                'slug' => 'loyalty-points-popup',
                'description' => 'A celebratory popup confirming points/rewards earned from a purchase or action.',
                'storage_path' => 'popups/loyalty-points-popup',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'loyalty-points',
                    'celebratory',
                    'javascript',
                ],
            ],
            [
                'title' => 'App Update Available Popup',
                'slug' => 'update-available-popup',
                'description' => 'A popup notifying the user a new version is available with changelog highlights and an update button.',
                'storage_path' => 'popups/update-available-popup',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'app-update',
                    'changelog',
                    'javascript',
                ],
            ],
            [
                'title' => 'Unsaved Changes Warning Popup',
                'slug' => 'confirm-leave-page-popup',
                'description' => 'A popup that warns the user they have unsaved changes before navigating away, the classic \'are you sure\' guard.',
                'storage_path' => 'popups/confirm-leave-page-popup',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'unsaved-changes',
                    'guard',
                    'javascript',
                ],
            ],
            [
                'title' => 'Location-Based Currency Popup',
                'slug' => 'location-detection-popup',
                'description' => 'A popup suggesting a different currency/region based on detected location, with switch/dismiss options.',
                'storage_path' => 'popups/location-detection-popup',
                'customizable_vars' => [
                    '--accent' => '#ea580c',
                ],
                'tags' => [
                    'location-detection',
                    'currency',
                    'javascript',
                ],
            ],
            [
                'title' => 'Two-Step Email Capture Popup',
                'slug' => 'two-step-popup-flow',
                'description' => 'A popup that first asks for an interest category, then reveals the email field, a higher-converting two-step pattern.',
                'storage_path' => 'popups/two-step-popup-flow',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'two-step',
                    'lead-capture',
                    'javascript',
                ],
            ],
            [
                'title' => 'Mock Browser Notification Popup',
                'slug' => 'browser-notification-popup',
                'description' => 'A popup mimicking a native OS/browser push notification style, with icon, title and message.',
                'storage_path' => 'popups/browser-notification-popup',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'browser-notification',
                    'os-style',
                    'javascript',
                ],
            ],
            [
                'title' => 'Free Resource Download Popup',
                'slug' => 'download-resource-popup',
                'description' => 'A lead-magnet style popup offering a free downloadable resource in exchange for an email.',
                'storage_path' => 'popups/download-resource-popup',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'lead-magnet',
                    'download',
                    'javascript',
                ],
            ],
            [
                'title' => 'Rate Us App Store Popup',
                'slug' => 'rate-app-store-popup',
                'description' => 'A popup asking the user to rate the app/site on an app store, common after positive engagement signals.',
                'storage_path' => 'popups/rate-app-store-popup',
                'customizable_vars' => [
                    '--star-color' => '#f59e0b',
                ],
                'tags' => [
                    'rate-app',
                    'app-store',
                    'javascript',
                ],
            ],
            [
                'title' => 'New Feature Announcement Popup',
                'slug' => 'feature-announcement-popup',
                'description' => 'A popup highlighting a single new product feature with a screenshot placeholder and CTA.',
                'storage_path' => 'popups/feature-announcement-popup',
                'customizable_vars' => [
                    '--accent' => '#4338ca',
                ],
                'tags' => [
                    'feature-announcement',
                    'whats-new',
                    'javascript',
                ],
            ],
            [
                'title' => 'Forgot Password Confirmation Popup',
                'slug' => 'password-strength-popup',
                'description' => 'A popup confirming a password reset email has been sent, with a resend option.',
                'storage_path' => 'popups/password-strength-popup',
                'customizable_vars' => [
                    '--accent' => '#0284c7',
                ],
                'tags' => [
                    'password-reset',
                    'email-confirmation',
                    'javascript',
                ],
            ],
            [
                'title' => 'Dark Mode Themed Popup',
                'slug' => 'dark-mode-popup',
                'description' => 'A general-purpose popup styled for dark-themed applications, with subtle borders instead of shadows.',
                'storage_path' => 'popups/dark-mode-popup',
                'customizable_vars' => [
                    '--accent' => '#f87171',
                ],
                'tags' => [
                    'dark-mode',
                    'confirm-delete',
                    'javascript',
                ],
            ],
            [
                'title' => 'Currency Selector Popup',
                'slug' => 'multi-currency-select-popup',
                'description' => 'A popup letting users pick their preferred display currency from a grid of options.',
                'storage_path' => 'popups/multi-currency-select-popup',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'currency-selector',
                    'grid-select',
                    'javascript',
                ],
            ],
            [
                'title' => 'Terms of Service Update Popup',
                'slug' => 'terms-update-popup',
                'description' => 'A popup informing users that the terms of service have changed, requiring acknowledgment to continue.',
                'storage_path' => 'popups/terms-update-popup',
                'customizable_vars' => [
                    '--accent' => '#1e40af',
                ],
                'tags' => [
                    'terms-update',
                    'legal',
                    'javascript',
                ],
            ],
            [
                'title' => 'Invite Team Members Popup',
                'slug' => 'invite-team-popup',
                'description' => 'A popup with an email input and \'Add\' button to invite multiple teammates, building a list as you go.',
                'storage_path' => 'popups/invite-team-popup',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'team-invite',
                    'javascript',
                    'list-building',
                ],
            ],
            [
                'title' => 'Autoplay Video Consent Popup',
                'slug' => 'video-autoplay-consent-popup',
                'description' => 'A popup asking permission before autoplaying video with sound, respecting user preference.',
                'storage_path' => 'popups/video-autoplay-consent-popup',
                'customizable_vars' => [
                    '--accent' => '#0ea5e9',
                ],
                'tags' => [
                    'video-consent',
                    'autoplay',
                    'javascript',
                ],
            ],
            [
                'title' => 'Minimal Single-Button Alert Popup',
                'slug' => 'simple-alert-popup',
                'description' => 'The simplest possible popup: a message and one OK button, no fancy styling, the bare-minimum alert pattern.',
                'storage_path' => 'popups/simple-alert-popup',
                'customizable_vars' => [],
                'tags' => [
                    'minimal',
                    'single-button',
                    'javascript',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
