<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "search-bar" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class SearchBarDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'search-bar')->first();

        if (!$section) {
            $this->command?->warn("Section 'search-bar' not found — skipping SearchBarDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Rounded Pill Search Bar',
                'slug' => 'rounded-search-bar',
                'description' => 'A classic fully-rounded search input with a leading magnifier icon.',
                'storage_path' => 'search-bar/rounded-search-bar',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'pill',
                    'rounded',
                    'basic',
                ],
            ],
            [
                'title' => 'Expanding Icon Search Bar',
                'slug' => 'expanding-icon-search-bar',
                'description' => 'A search icon that expands into a full input field on click, via JS width toggle.',
                'storage_path' => 'search-bar/expanding-icon-search-bar',
                'customizable_vars' => [
                    '--accent' => '#111827',
                ],
                'tags' => [
                    'expanding',
                    'javascript',
                    'icon-trigger',
                ],
            ],
            [
                'title' => 'Search Bar with Filter Dropdown',
                'slug' => 'search-with-filters-bar',
                'description' => 'A search bar combined with a category dropdown selector to the left, common in marketplace search.',
                'storage_path' => 'search-bar/search-with-filters-bar',
                'customizable_vars' => [
                    '--accent' => '#0ea5e9',
                ],
                'tags' => [
                    'filter-dropdown',
                    'marketplace',
                    'compound',
                ],
            ],
            [
                'title' => 'Live Autocomplete Search Bar',
                'slug' => 'autocomplete-dropdown-search-bar',
                'description' => 'A search input showing a dropdown of matching suggestions as the user types, via JS filtering.',
                'storage_path' => 'search-bar/autocomplete-dropdown-search-bar',
                'customizable_vars' => [
                    '--accent' => '#4f46e5',
                ],
                'tags' => [
                    'autocomplete',
                    'javascript',
                    'suggestions',
                ],
            ],
            [
                'title' => 'Voice Search Bar',
                'slug' => 'voice-search-bar',
                'description' => 'A search bar with a microphone icon button that visually indicates \'listening\' state on click via JS.',
                'storage_path' => 'search-bar/voice-search-bar',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'voice-search',
                    'javascript',
                    'mic-icon',
                ],
            ],
            [
                'title' => 'Search Bar with Recent History',
                'slug' => 'search-history-bar',
                'description' => 'A search input that shows a dropdown of recent searches on focus, via JS.',
                'storage_path' => 'search-bar/search-history-bar',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'search-history',
                    'javascript',
                    'recent-items',
                ],
            ],
            [
                'title' => 'Search Bar with Category Tabs',
                'slug' => 'category-tabs-search-bar',
                'description' => 'A search bar with category pill tabs beneath it for quick filtering, common in app stores.',
                'storage_path' => 'search-bar/category-tabs-search-bar',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'category-tabs',
                    'filter',
                    'javascript',
                ],
            ],
            [
                'title' => 'Search Bar with Clear Button',
                'slug' => 'clear-button-search-bar',
                'description' => 'A search input showing an \'x\' clear button only when text is present, via JS visibility toggle.',
                'storage_path' => 'search-bar/clear-button-search-bar',
                'customizable_vars' => [
                    '--accent' => '#475569',
                ],
                'tags' => [
                    'clear-button',
                    'javascript',
                    'ux-detail',
                ],
            ],
            [
                'title' => 'Search Bar with Loading Spinner',
                'slug' => 'search-with-loading-bar',
                'description' => 'A search input that shows a small spinner inside it while results are \'loading\', simulated via JS timeout.',
                'storage_path' => 'search-bar/search-with-loading-bar',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'loading-state',
                    'javascript',
                    'spinner',
                ],
            ],
            [
                'title' => 'Command Palette Search (Cmd+K)',
                'slug' => 'command-palette-search-bar',
                'description' => 'A spotlight-style search box opened with Ctrl/Cmd+K, mimicking VS Code/Notion command palettes.',
                'storage_path' => 'search-bar/command-palette-search-bar',
                'customizable_vars' => [
                    '--accent' => '#111827',
                ],
                'tags' => [
                    'command-palette',
                    'javascript',
                    'keyboard-shortcut',
                ],
            ],
            [
                'title' => 'Search Bar with Suggestion Pills',
                'slug' => 'inline-suggestions-pills-search-bar',
                'description' => 'A search bar with quick-pick suggestion pill buttons displayed underneath for common queries.',
                'storage_path' => 'search-bar/inline-suggestions-pills-search-bar',
                'customizable_vars' => [
                    '--accent' => '#f59e0b',
                ],
                'tags' => [
                    'suggestion-pills',
                    'quick-pick',
                    'discoverability',
                ],
            ],
            [
                'title' => 'Minimal Underline Search Bar',
                'slug' => 'underline-search-bar',
                'description' => 'An understated search input with only a bottom border, no box at all, paired with a trailing icon.',
                'storage_path' => 'search-bar/underline-search-bar',
                'customizable_vars' => [
                    '--accent' => '#000000',
                ],
                'tags' => [
                    'minimal',
                    'underline',
                    'css-has',
                ],
            ],
            [
                'title' => 'Dark Mode Search Bar',
                'slug' => 'dark-search-bar',
                'description' => 'A search bar styled for dark interfaces with a subtle glow on focus.',
                'storage_path' => 'search-bar/dark-search-bar',
                'customizable_vars' => [
                    '--accent' => '#38bdf8',
                ],
                'tags' => [
                    'dark-mode',
                    'glow-focus',
                ],
            ],
            [
                'title' => 'Search Bar with Keyboard Hint',
                'slug' => 'search-with-keyboard-hint-bar',
                'description' => 'A search input displaying a \'/\' keyboard shortcut hint inside it, common on docs sites.',
                'storage_path' => 'search-bar/search-with-keyboard-hint-bar',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'keyboard-hint',
                    'docs-site',
                    'css-has',
                ],
            ],
            [
                'title' => 'Search Bar with No-Results State',
                'slug' => 'no-results-state-search-bar',
                'description' => 'A search experience that shows an explicit \'no results found\' message when a query matches nothing, via JS.',
                'storage_path' => 'search-bar/no-results-state-search-bar',
                'customizable_vars' => [
                    '--accent' => '#be123c',
                ],
                'tags' => [
                    'empty-state',
                    'javascript',
                    'no-results',
                ],
            ],
            [
                'title' => 'Gradient Border Search Bar',
                'slug' => 'gradient-border-search-bar',
                'description' => 'A search bar with an eye-catching animated gradient border ring around it.',
                'storage_path' => 'search-bar/gradient-border-search-bar',
                'customizable_vars' => [
                    '--g1' => '#6366f1',
                    '--g2' => '#ec4899',
                ],
                'tags' => [
                    'gradient-border',
                    'dark-mode',
                    'stylish',
                ],
            ],
            [
                'title' => 'Search Bar with Split Button',
                'slug' => 'split-button-search-bar',
                'description' => 'A search input with an attached dropdown button on the right for selecting search scope.',
                'storage_path' => 'search-bar/split-button-search-bar',
                'customizable_vars' => [
                    '--accent' => '#0891b2',
                ],
                'tags' => [
                    'split-button',
                    'scope-selector',
                ],
            ],
            [
                'title' => 'Animated Cycling Placeholder Search Bar',
                'slug' => 'animated-placeholder-search-bar',
                'description' => 'A search input whose placeholder text cycles through several example queries via JS.',
                'storage_path' => 'search-bar/animated-placeholder-search-bar',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'animated-placeholder',
                    'javascript',
                    'cycling-text',
                ],
            ],
            [
                'title' => 'Search Bar with Live Result Count',
                'slug' => 'results-count-search-bar',
                'description' => 'A search bar that shows a live \'X results found\' count below it as the user types, via JS.',
                'storage_path' => 'search-bar/results-count-search-bar',
                'customizable_vars' => [
                    '--accent' => '#4338ca',
                ],
                'tags' => [
                    'result-count',
                    'javascript',
                    'live-feedback',
                ],
            ],
            [
                'title' => 'Shadow Elevate on Focus Search Bar',
                'slug' => 'shadow-elevate-search-bar',
                'description' => 'A search input that lifts with a stronger shadow when focused, giving tactile depth feedback.',
                'storage_path' => 'search-bar/shadow-elevate-search-bar',
                'customizable_vars' => [
                    '--accent' => '#1d4ed8',
                ],
                'tags' => [
                    'elevation',
                    'focus-state',
                    'depth',
                ],
            ],
            [
                'title' => 'Multi-Tag Filter Search Bar',
                'slug' => 'multi-select-tag-search-bar',
                'description' => 'A search bar that lets you add multiple filter tags inline before the text cursor, via JS.',
                'storage_path' => 'search-bar/multi-select-tag-search-bar',
                'customizable_vars' => [
                    '--accent' => '#ea580c',
                ],
                'tags' => [
                    'multi-tag',
                    'filter',
                    'javascript',
                ],
            ],
            [
                'title' => 'Search with Attached Round Button',
                'slug' => 'rounded-icon-button-search-bar',
                'description' => 'A square input with a circular search button overlapping its right edge for a distinctive layered look.',
                'storage_path' => 'search-bar/rounded-icon-button-search-bar',
                'customizable_vars' => [
                    '--accent' => '#be185d',
                ],
                'tags' => [
                    'overlapping-button',
                    'layered',
                    'distinctive',
                ],
            ],
            [
                'title' => 'Hero Overlay Search Bar',
                'slug' => 'transparent-overlay-search-bar',
                'description' => 'A large, semi-transparent search bar designed to sit over a hero background image, common on travel/job sites.',
                'storage_path' => 'search-bar/transparent-overlay-search-bar',
                'customizable_vars' => [
                    '--accent' => '#0ea5e9',
                ],
                'tags' => [
                    'hero-search',
                    'travel-style',
                    'large-cta',
                ],
            ],
            [
                'title' => 'Recent + Trending Search Dropdown',
                'slug' => 'recent-and-trending-search-bar',
                'description' => 'A search bar dropdown split into \'Recent\' and \'Trending\' sections, common on e-commerce platforms.',
                'storage_path' => 'search-bar/recent-and-trending-search-bar',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'recent-trending',
                    'javascript',
                    'ecommerce',
                ],
            ],
            [
                'title' => 'Search Bar Shake on Empty Submit',
                'slug' => 'search-error-shake-bar',
                'description' => 'A search bar that shakes if the user hits Enter on an empty field, providing instant visual feedback via JS.',
                'storage_path' => 'search-bar/search-error-shake-bar',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'error-feedback',
                    'javascript',
                    'shake',
                ],
            ],
            [
                'title' => 'Search Bar with Subtitle',
                'slug' => 'two-line-search-bar',
                'description' => 'A search input with a small descriptive subtitle line above it, common on landing page heroes.',
                'storage_path' => 'search-bar/two-line-search-bar',
                'customizable_vars' => [
                    '--accent' => '#0d9488',
                ],
                'tags' => [
                    'with-subtitle',
                    'hero-style',
                    'landing-page',
                ],
            ],
            [
                'title' => 'Search Bar with View Toggle',
                'slug' => 'search-toggle-grid-list-bar',
                'description' => 'A search input paired with grid/list view toggle buttons, common on browsing/catalog pages.',
                'storage_path' => 'search-bar/search-toggle-grid-list-bar',
                'customizable_vars' => [
                    '--accent' => '#334155',
                ],
                'tags' => [
                    'view-toggle',
                    'grid-list',
                    'javascript',
                ],
            ],
            [
                'title' => 'Flat Icon Search Bar',
                'slug' => 'rounded-flat-icon-search-bar',
                'description' => 'A super-minimal flat search bar with no border at all, relying only on a subtle background fill.',
                'storage_path' => 'search-bar/rounded-flat-icon-search-bar',
                'customizable_vars' => [
                    '--bg-fill' => '#f1f5f9',
                ],
                'tags' => [
                    'flat',
                    'borderless',
                    'subtle-fill',
                ],
            ],
            [
                'title' => 'Search Bar with Operator Tooltip',
                'slug' => 'search-with-tooltip-shortcuts-bar',
                'description' => 'A search bar showing a tooltip on focus explaining advanced search operators like quotes and minus signs.',
                'storage_path' => 'search-bar/search-with-tooltip-shortcuts-bar',
                'customizable_vars' => [
                    '--accent' => '#4338ca',
                ],
                'tags' => [
                    'tooltip',
                    'advanced-search',
                    'javascript',
                ],
            ],
            [
                'title' => 'Search Bar with Scope Breadcrumb',
                'slug' => 'breadcrumb-search-bar',
                'description' => 'A search bar showing the current search scope as a removable breadcrumb chip before the input, e.g. searching within a folder.',
                'storage_path' => 'search-bar/breadcrumb-search-bar',
                'customizable_vars' => [
                    '--accent' => '#ea580c',
                ],
                'tags' => [
                    'breadcrumb',
                    'scoped-search',
                    'javascript',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
