<?php

namespace Database\Seeders\Designs;

use App\Models\Design;
use App\Models\Section;
use Illuminate\Database\Seeder;

/**
 * Seeds all designs for the "ui-components" section.
 * Generated by the design generator — see /database/seeders/Designs for
 * the full list of per-section seeders, all dispatched from DesignSeeder.
 */
class UiComponentsDesignSeeder extends Seeder
{
    public function run(): void
    {
        $section = Section::where('slug', 'ui-components')->first();

        if (!$section) {
            $this->command?->warn("Section 'ui-components' not found — skipping UiComponentsDesignSeeder.");
            return;
        }

        $designs = [
            [
                'title' => 'Avatar with Status Badge',
                'slug' => 'avatar-badge-component',
                'description' => 'A circular avatar with a small colored online/offline status dot in the corner.',
                'storage_path' => 'ui-components/avatar-badge-component',
                'customizable_vars' => [
                    '--online-color' => '#16a34a',
                ],
                'tags' => [
                    'avatar',
                    'status-indicator',
                ],
            ],
            [
                'title' => 'Breadcrumb Navigation',
                'slug' => 'breadcrumb-component',
                'description' => 'A standard breadcrumb trail showing the current page hierarchy with separators.',
                'storage_path' => 'ui-components/breadcrumb-component',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'breadcrumb',
                    'navigation',
                ],
            ],
            [
                'title' => 'Status Badge Pills',
                'slug' => 'badge-pill-component',
                'description' => 'A row of small colored pill badges used to label statuses like Active, Pending, Closed.',
                'storage_path' => 'ui-components/badge-pill-component',
                'customizable_vars' => [],
                'tags' => [
                    'badges',
                    'status-labels',
                ],
            ],
            [
                'title' => 'FAQ Accordion List',
                'slug' => 'accordion-faq-component',
                'description' => 'A list of frequently asked questions where each item expands to reveal its answer, via JS.',
                'storage_path' => 'ui-components/accordion-faq-component',
                'customizable_vars' => [
                    '--accent' => '#4f46e5',
                ],
                'tags' => [
                    'accordion',
                    'faq',
                    'javascript',
                ],
            ],
            [
                'title' => 'Hover Tooltip',
                'slug' => 'tooltip-component',
                'description' => 'A small dark tooltip that appears above an element on hover, pure CSS.',
                'storage_path' => 'ui-components/tooltip-component',
                'customizable_vars' => [],
                'tags' => [
                    'tooltip',
                    'css-only',
                ],
            ],
            [
                'title' => 'Stepper Progress Indicator',
                'slug' => 'progress-steps-component',
                'description' => 'A horizontal multi-step progress component showing numbered circles connected by lines.',
                'storage_path' => 'ui-components/progress-steps-component',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'stepper',
                    'progress',
                    'wizard',
                ],
            ],
            [
                'title' => 'Star Rating Display',
                'slug' => 'rating-display-component',
                'description' => 'A read-only star rating display showing a fractional rating with review count.',
                'storage_path' => 'ui-components/rating-display-component',
                'customizable_vars' => [
                    '--star-color' => '#f59e0b',
                ],
                'tags' => [
                    'rating-display',
                    'read-only',
                ],
            ],
            [
                'title' => 'Underline Tabs Component',
                'slug' => 'tabs-component',
                'description' => 'A horizontal tab navigation with a sliding underline indicator, via JS.',
                'storage_path' => 'ui-components/tabs-component',
                'customizable_vars' => [
                    '--accent' => '#7c3aed',
                ],
                'tags' => [
                    'tabs',
                    'javascript',
                    'navigation',
                ],
            ],
            [
                'title' => 'Dismissible Alert Banner',
                'slug' => 'alert-banner-component',
                'description' => 'A colored alert banner with an icon and a close button that removes it via JS.',
                'storage_path' => 'ui-components/alert-banner-component',
                'customizable_vars' => [
                    '--alert-bg' => '#fffbeb',
                    '--alert-text' => '#92400e',
                ],
                'tags' => [
                    'alert',
                    'dismissible',
                    'javascript',
                ],
            ],
            [
                'title' => 'Pagination Controls',
                'slug' => 'pagination-component',
                'description' => 'A numbered pagination component with previous/next arrows and an active page indicator.',
                'storage_path' => 'ui-components/pagination-component',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'pagination',
                    'navigation',
                ],
            ],
            [
                'title' => 'Overlapping Avatar Group',
                'slug' => 'avatar-group-component',
                'description' => 'A cluster of overlapping circular avatars with a \'+N\' overflow counter, common in collaborative apps.',
                'storage_path' => 'ui-components/avatar-group-component',
                'customizable_vars' => [
                    '--accent' => '#db2777',
                ],
                'tags' => [
                    'avatar-group',
                    'overlapping',
                ],
            ],
            [
                'title' => 'Removable Filter Chips',
                'slug' => 'chip-filter-component',
                'description' => 'A row of active filter chips that can be individually removed by clicking their x, via JS.',
                'storage_path' => 'ui-components/chip-filter-component',
                'customizable_vars' => [
                    '--accent' => '#0f766e',
                ],
                'tags' => [
                    'chips',
                    'filter',
                    'javascript',
                ],
            ],
            [
                'title' => 'Collapsible Sidebar Group',
                'slug' => 'collapsible-sidebar-section',
                'description' => 'A sidebar navigation section header that expands/collapses its child links, via JS.',
                'storage_path' => 'ui-components/collapsible-sidebar-section',
                'customizable_vars' => [
                    '--accent' => '#4f46e5',
                ],
                'tags' => [
                    'sidebar',
                    'collapsible',
                    'javascript',
                ],
            ],
            [
                'title' => 'Divider with Center Text',
                'slug' => 'divider-with-text',
                'description' => 'A horizontal divider line with text (\'OR\') centered inside it, common between login methods.',
                'storage_path' => 'ui-components/divider-with-text',
                'customizable_vars' => [],
                'tags' => [
                    'divider',
                    'minimal',
                ],
            ],
            [
                'title' => 'Stacked Toast Notifications',
                'slug' => 'toast-stack-component',
                'description' => 'Multiple toast notifications stacking vertically in the corner, each dismissible and auto-removing, via JS.',
                'storage_path' => 'ui-components/toast-stack-component',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'toast-stack',
                    'javascript',
                    'notifications',
                ],
            ],
            [
                'title' => 'Toggle Switch List',
                'slug' => 'toggle-switch-list-component',
                'description' => 'A vertical list of labeled toggle switches, a smaller building block reusable across settings pages.',
                'storage_path' => 'ui-components/toggle-switch-list-component',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'toggle-list',
                    'settings-block',
                ],
            ],
            [
                'title' => 'Empty State Illustration',
                'slug' => 'empty-state-component',
                'description' => 'A placeholder shown when a list/table has no content, with icon, message, and a primary action button.',
                'storage_path' => 'ui-components/empty-state-component',
                'customizable_vars' => [
                    '--accent' => '#6366f1',
                ],
                'tags' => [
                    'empty-state',
                    'placeholder',
                ],
            ],
            [
                'title' => 'Simple Data Table',
                'slug' => 'data-table-row-component',
                'description' => 'A minimal data table with header row, sortable-style column headers, and zebra-striped rows.',
                'storage_path' => 'ui-components/data-table-row-component',
                'customizable_vars' => [
                    '--header-bg' => '#f9fafb',
                ],
                'tags' => [
                    'table',
                    'data-display',
                ],
            ],
            [
                'title' => 'Keyboard Key Display Component',
                'slug' => 'kbd-shortcut-display',
                'description' => 'A small standalone styled <kbd> element group used to display keyboard combinations inline in text.',
                'storage_path' => 'ui-components/kbd-shortcut-display',
                'customizable_vars' => [],
                'tags' => [
                    'kbd-display',
                    'inline',
                    'minimal',
                ],
            ],
            [
                'title' => 'Collapsible Code Block',
                'slug' => 'collapsible-code-block',
                'description' => 'A code snippet display block with a \'Show more\' expand toggle for long code, via JS.',
                'storage_path' => 'ui-components/collapsible-code-block',
                'customizable_vars' => [],
                'tags' => [
                    'code-block',
                    'javascript',
                    'expand',
                ],
            ],
            [
                'title' => 'Theme Color Swatch Grid',
                'slug' => 'color-swatch-grid',
                'description' => 'A grid display of design-system color tokens with their hex labels, a documentation-style component.',
                'storage_path' => 'ui-components/color-swatch-grid',
                'customizable_vars' => [],
                'tags' => [
                    'color-tokens',
                    'design-system',
                ],
            ],
            [
                'title' => 'Notification Bell with Counter',
                'slug' => 'notification-bell-component',
                'description' => 'A bell icon button with a small badge counter showing unread notifications.',
                'storage_path' => 'ui-components/notification-bell-component',
                'customizable_vars' => [
                    '--accent' => '#dc2626',
                ],
                'tags' => [
                    'notification-bell',
                    'badge-counter',
                ],
            ],
            [
                'title' => 'Vertical Divider with Labels',
                'slug' => 'vertical-divider-component',
                'description' => 'A vertical line divider used between two inline label/value pairs, common in stat rows.',
                'storage_path' => 'ui-components/vertical-divider-component',
                'customizable_vars' => [],
                'tags' => [
                    'divider',
                    'stats-row',
                ],
            ],
            [
                'title' => 'Input Field with Leading Icon',
                'slug' => 'input-with-icon-component',
                'description' => 'A reusable text input building block with an embedded leading icon, the base unit for many forms.',
                'storage_path' => 'ui-components/input-with-icon-component',
                'customizable_vars' => [
                    '--accent' => '#2563eb',
                ],
                'tags' => [
                    'input-component',
                    'icon',
                    'css-has',
                ],
            ],
            [
                'title' => 'Selectable Card List',
                'slug' => 'card-list-toggle-component',
                'description' => 'A list of selectable option cards where only one can be active at a time, like radio buttons but styled as cards.',
                'storage_path' => 'ui-components/card-list-toggle-component',
                'customizable_vars' => [
                    '--accent' => '#16a34a',
                ],
                'tags' => [
                    'selectable-cards',
                    'javascript',
                    'radio-alternative',
                ],
            ],
            [
                'title' => 'Button with Inline Loading State',
                'slug' => 'loading-button-state-component',
                'description' => 'A reusable button component that swaps its own label for a spinner while an action is in flight.',
                'storage_path' => 'ui-components/loading-button-state-component',
                'customizable_vars' => [
                    '--accent' => '#4338ca',
                ],
                'tags' => [
                    'button-component',
                    'loading-state',
                    'javascript',
                ],
            ],
            [
                'title' => 'Read More Text Truncation',
                'slug' => 'expandable-text-component',
                'description' => 'A paragraph of text that\'s truncated with a \'Read more\' link to expand it fully, via JS.',
                'storage_path' => 'ui-components/expandable-text-component',
                'customizable_vars' => [
                    '--accent' => '#0ea5e9',
                ],
                'tags' => [
                    'read-more',
                    'truncation',
                    'javascript',
                ],
            ],
            [
                'title' => 'Feature List with Icons',
                'slug' => 'icon-text-list-component',
                'description' => 'A vertical list of features, each paired with a small checkmark or icon, common on pricing pages.',
                'storage_path' => 'ui-components/icon-text-list-component',
                'customizable_vars' => [
                    '--check-color' => '#16a34a',
                ],
                'tags' => [
                    'feature-list',
                    'checklist',
                ],
            ],
            [
                'title' => 'Copy to Clipboard Field',
                'slug' => 'copy-to-clipboard-component',
                'description' => 'A read-only text field with an adjacent copy button that gives visual confirmation, via JS.',
                'storage_path' => 'ui-components/copy-to-clipboard-component',
                'customizable_vars' => [
                    '--accent' => '#1e293b',
                ],
                'tags' => [
                    'copy-to-clipboard',
                    'javascript',
                    'code-snippet',
                ],
            ],
            [
                'title' => 'Segmented Multi-Color Progress Bar',
                'slug' => 'segmented-progress-bar-component',
                'description' => 'A progress bar divided into multiple colored segments representing different categories, like a storage usage breakdown.',
                'storage_path' => 'ui-components/segmented-progress-bar-component',
                'customizable_vars' => [],
                'tags' => [
                    'segmented-progress',
                    'storage-breakdown',
                    'data-viz',
                ],
            ],
        ];

        foreach ($designs as $design) {
            Design::query()->updateOrCreate(
                ['storage_path' => $design['storage_path']],
                $design + ['section_id' => $section->id, 'is_published' => true]
            );
        }
    }
}
